// Code generated by Scenery. DO NOT EDIT.
package serviceserviceadapter

import (
	"context"
	implementation "example.com/basicapp/service"
	contract "example.com/basicapp/service/scenerycontract"
	"fmt"
	"net/http"
	scenery "scenery.sh"
	sceneryruntime "scenery.sh/runtime"
)

const ContractRevision = "sha256:0178beaba6dd02083568054d1314d2af6a8033c27b7704f882c191331d3baa32"
const PackageIdentity = "service"
const PackageContractABIRevision = "sha256:aa04ac9d2ed99ae3002b3f46fbd82756533dd3497f2f4ee8d54c4ac70d001fc6"

type serviceImplementation interface {
	Echo(context.Context, contract.EchoInput) (contract.EchoOutcome, error)
}

type serviceAdapter struct{ native serviceImplementation }

var service *serviceAdapter

func (adapter *serviceAdapter) Echo(ctx context.Context, input contract.EchoInput) (contract.EchoOutcome, error) {
	if adapter == nil || adapter.native == nil {
		return nil, fmt.Errorf("service is not initialized")
	}
	native := adapter.native
	return native.Echo(ctx, input)
}

func Register(registry scenery.Registry) error {
	return registry.Register("service/service/service/adapter", sceneryruntime.ContractRegistration{
		ContractRevision: ContractRevision, PackageContractABIRevision: PackageContractABIRevision, RuntimeABI: sceneryruntime.ContractRuntimeABI,
		ProviderABIs: map[string]string{}, CoveredAddresses: []string{"service/binding/echo_http", "service/execution/echo_direct", "service/operation/echo", "service/service/service"},
		Apply: func() error {
			if contract.PackageIdentity != PackageIdentity {
				return fmt.Errorf("package identity mismatch")
			}
			if contract.PackageContractABIRevision != PackageContractABIRevision {
				return fmt.Errorf("package contract ABI mismatch")
			}
			if err := sceneryruntime.RegisterNativeService(sceneryruntime.NativeServiceRegistration{Address: "service/service/service", Initialize: func(ctx context.Context) error {
				input := contract.ServiceConstructorInput{}
				value, err := implementation.NewService(ctx, input)
				if err != nil {
					return err
				}
				if value == nil {
					return fmt.Errorf("constructor returned nil service")
				}
				service = &serviceAdapter{native: value}
				return nil
			}}); err != nil {
				return err
			}
			if err := sceneryruntime.RegisterEndpointChecked(&sceneryruntime.Endpoint{Service: "service", Name: "EchoHttp", Access: sceneryruntime.Public, Path: "/echo", Methods: []string{"POST"},
				ContractPolicy: &sceneryruntime.ContractHTTPPolicy{BindingAddress: "service/binding/echo_http", GatewayAddress: "app/http_gateway/public_api", CORS: "none", AllowedOrigins: []string{}, Forwarded: "reject", TrustedProxyPrefixes: []string{}, MaxRequestHeaderBytes: 65536, MaxResponseBytes: 16777216, CompressionAlgorithms: []string{"gzip"}, CompressionThreshold: 1024, TotalInvocationTimeoutNanos: 2400000000000, ReadTimeoutNanos: 30000000000, WriteTimeoutNanos: 30000000000, IdleTimeoutNanos: 120000000000, AuthorizationStrategy: "public", AuthorizationRuleCount: 0, AuthorizationRules: []sceneryruntime.ContractAuthorizationRule{}, PipelineSteps: []string{}, FrameworkGuarantee: "framework_enforced", TransportStatuses: map[string]int{"admission.rate_limited": 429, "result.ok": 200, "system.internal": 500, "transport.invalid_request": 400, "transport.not_acceptable": 406, "transport.unsupported_media_type": 415}},
				DecodeContractRequest: func(request *http.Request, pathValues map[string]string) (sceneryruntime.ContractDecodedRequest, error) {
					input, err := sceneryruntime.DecodeContractInput[contract.EchoInput](request, pathValues, sceneryruntime.ContractRequestSchema{Mappings: []sceneryruntime.ContractInputMapping{}, ContextMappings: []sceneryruntime.ContractContextMapping{}, Body: &sceneryruntime.ContractBodyMapping{Codec: "json", Target: "", Type: "record.echo_input", DecodeValue: func(data []byte, target any) error {
						return scenery.UnmarshalContractValue(data, target, "record.echo_input")
					}, Include: []string(nil), Except: []string(nil), AcceptedMediaTypes: []string{}, SupportedContentEncoding: []string{}, MaxCompressedBytes: 8388608, MaxDecompressedBytes: 16777216, Fields: []sceneryruntime.ContractInputMapping{}, MultipartParts: []sceneryruntime.ContractMultipartPart{}, MaxMultipartParts: 128}, TransportStatuses: map[string]int{"admission.rate_limited": 429, "system.internal": 500, "transport.invalid_request": 400, "transport.not_acceptable": 406, "transport.unsupported_media_type": 415}})
					return sceneryruntime.ContractDecodedRequest{Payload: input}, err
				},
				Invoke: func(ctx context.Context, _ []any, payload any) (any, error) {
					if service == nil {
						return nil, sceneryruntime.ContractSystemError(fmt.Errorf("service is not initialized"))
					}
					copied, err := contract.CloneEchoInput(payload.(contract.EchoInput))
					if err != nil {
						return nil, sceneryruntime.ContractSystemError(err)
					}
					outcome, err := service.Echo(ctx, copied)
					if err != nil {
						if outcome != nil {
							return nil, sceneryruntime.ContractSystemError(fmt.Errorf("handler returned outcome and error"))
						}
						return nil, sceneryruntime.ContractSystemError(err)
					}
					if outcome == nil {
						return nil, sceneryruntime.ContractSystemError(fmt.Errorf("handler returned nil outcome without error"))
					}
					cloned, err := contract.CloneEchoOutcome(outcome)
					if err != nil {
						return nil, sceneryruntime.ContractSystemError(err)
					}
					if err := sceneryruntime.PublishContractOperationOutcome(ctx, "service/operation/echo", cloned); err != nil {
						return nil, sceneryruntime.ContractSystemError(err)
					}
					return cloned, nil
				},
				EncodeContractOutcome: func(request *http.Request, outcome any) (sceneryruntime.ContractHTTPResponse, error) {
					_ = request
					switch typed := outcome.(type) {
					case contract.EchoOk:
						response, err := sceneryruntime.EncodeContractRepresentationWithOptions(request, 200, typed.Value, "json", []string{"application/json"}, sceneryruntime.ContractResponseOptions{MaxBytes: 16777216, CompressionAlgorithms: []string{"gzip"}, CompressionThreshold: 1024, TypeExpression: "record.echo_result", EncodeValue: func(value any) ([]byte, error) { return scenery.MarshalContractValue(value, "record.echo_result") }})
						if err != nil {
							return sceneryruntime.ContractHTTPResponse{}, err
						}
						return response, nil
					default:
						return sceneryruntime.ContractHTTPResponse{}, fmt.Errorf("handler returned an unknown outcome %T", outcome)
					}
				},
			}); err != nil {
				return err
			}
			return nil
		},
	})
}
