// Code generated by Scenery vNext. DO NOT EDIT.
package composition

import (
	adapter0 "example.test/nativeapp/internal/scenerygen/house_house_adapter"
	scenery "scenery.sh"
)

const ContractRevision = "sha256:bdcdc3efe46a7ed61994badb8c55c0f7b5a6b7f8311be7f3512efe47c91ea0ae"

var RequiredAddresses = []string{"house/binding/process_scene_http", "house/binding/process_scene_internal", "house/execution/process_scene_direct", "house/operation/process_scene", "house/service/house"}

var RequiredProviderABIs = map[string]string{}

func Register(registry scenery.Registry) error {
	if err := adapter0.Register(registry); err != nil {
		return err
	}
	return nil
}
