// Code generated by Scenery vNext. DO NOT EDIT.
package composition

import (
	adapter0 "example.test/nativeapp/internal/scenerygen/house_house_adapter"
	scenery "scenery.sh"
)

const ContractRevision = "sha256:fe7e93d91bc599c07fea0d0416d3219745e3c8018251d3b96804d84327115f6c"

var RequiredAddresses = []string{"house/binding/process_scene_http", "house/binding/process_scene_internal", "house/execution/process_scene_direct", "house/operation/process_scene", "house/service/house"}

var RequiredProviderABIs = map[string]string{}

func Register(registry scenery.Registry) error {
	if err := adapter0.Register(registry); err != nil {
		return err
	}
	return nil
}
