// Code generated by Scenery. DO NOT EDIT.
package serviceserviceadapter

import (
	"context"
	implementation "example.com/storagebasic/service"
	contract "example.com/storagebasic/service/scenerycontract"
	"fmt"
	"net/http"
	scenery "scenery.sh"
	sceneryruntime "scenery.sh/runtime"
)

const ContractRevision = "sha256:2872b4e15d35fd5d413196a1f7e00df02a884c991a53903ac5d2227d710cdb1c"
const PackageIdentity = "service"
const PackageContractABIRevision = "sha256:e26f525ca795b22a4a5a4c511ac07b2b58b212188230d3bd4a09ec5838ded3a0"

type serviceImplementation interface {
	PublicStorageProbe(context.Context, contract.PublicStorageProbeInput) (contract.PublicStorageProbeOutcome, error)
	ReadPublicStorageProbe(context.Context, contract.ReadPublicStorageProbeInput) (contract.ReadPublicStorageProbeOutcome, error)
}

type serviceAdapter struct{ native serviceImplementation }

var service *serviceAdapter

func (adapter *serviceAdapter) PublicStorageProbe(ctx context.Context, input contract.PublicStorageProbeInput) (contract.PublicStorageProbeOutcome, error) {
	if adapter == nil || adapter.native == nil {
		return nil, fmt.Errorf("service is not initialized")
	}
	native := adapter.native
	return native.PublicStorageProbe(ctx, input)
}

func (adapter *serviceAdapter) ReadPublicStorageProbe(ctx context.Context, input contract.ReadPublicStorageProbeInput) (contract.ReadPublicStorageProbeOutcome, error) {
	if adapter == nil || adapter.native == nil {
		return nil, fmt.Errorf("service is not initialized")
	}
	native := adapter.native
	return native.ReadPublicStorageProbe(ctx, input)
}

func Register(registry scenery.Registry) error {
	return registry.Register("service/service/service/adapter", sceneryruntime.ContractRegistration{
		ContractRevision: ContractRevision, PackageContractABIRevision: PackageContractABIRevision, RuntimeABI: sceneryruntime.ContractRuntimeABI,
		ProviderABIs: map[string]string{}, CoveredAddresses: []string{"service/binding/public_storage_probe_http", "service/binding/read_public_storage_probe_http", "service/execution/public_storage_probe_direct", "service/execution/read_public_storage_probe_direct", "service/operation/public_storage_probe", "service/operation/read_public_storage_probe", "service/service/service"},
		Apply: func() error {
			if contract.PackageIdentity != PackageIdentity {
				return fmt.Errorf("package identity mismatch")
			}
			if contract.PackageContractABIRevision != PackageContractABIRevision {
				return fmt.Errorf("package contract ABI mismatch")
			}
			if err := sceneryruntime.RegisterNativeService(sceneryruntime.NativeServiceRegistration{Address: "service/service/service", Initialize: func(ctx context.Context) error {
				input := contract.ServiceConstructorInput{}
				value, err := implementation.NewService(ctx, input)
				if err != nil {
					return err
				}
				if value == nil {
					return fmt.Errorf("constructor returned nil service")
				}
				service = &serviceAdapter{native: value}
				return nil
			}}); err != nil {
				return err
			}
			if err := sceneryruntime.RegisterEndpointChecked(&sceneryruntime.Endpoint{Service: "service", Name: "PublicStorageProbeHttp", Access: sceneryruntime.Public, Path: "/storage/probe-public", Methods: []string{"POST"},
				ContractPolicy: &sceneryruntime.ContractHTTPPolicy{BindingAddress: "service/binding/public_storage_probe_http", GatewayAddress: "app/http_gateway/public_api", CORS: "none", AllowedOrigins: []string{}, Forwarded: "reject", TrustedProxyPrefixes: []string{}, MaxRequestHeaderBytes: 65536, MaxResponseBytes: 16777216, CompressionAlgorithms: []string{"gzip"}, CompressionThreshold: 1024, TotalInvocationTimeoutNanos: 2400000000000, ReadTimeoutNanos: 30000000000, WriteTimeoutNanos: 30000000000, IdleTimeoutNanos: 120000000000, AuthorizationStrategy: "public", AuthorizationRuleCount: 0, AuthorizationRules: []sceneryruntime.ContractAuthorizationRule{}, PipelineSteps: []string{}, FrameworkGuarantee: "framework_enforced", TransportStatuses: map[string]int{"admission.rate_limited": 429, "result.ok": 200, "system.internal": 500, "transport.invalid_request": 400, "transport.not_acceptable": 406}},
				DecodeContractRequest: func(request *http.Request, pathValues map[string]string) (sceneryruntime.ContractDecodedRequest, error) {
					input, err := sceneryruntime.DecodeContractInput[contract.PublicStorageProbeInput](request, pathValues, sceneryruntime.ContractRequestSchema{Mappings: []sceneryruntime.ContractInputMapping{}, ContextMappings: []sceneryruntime.ContractContextMapping{}, Body: nil, TransportStatuses: map[string]int{"admission.rate_limited": 429, "system.internal": 500, "transport.invalid_request": 400, "transport.not_acceptable": 406}})
					return sceneryruntime.ContractDecodedRequest{Payload: input}, err
				},
				Invoke: func(ctx context.Context, _ []any, payload any) (any, error) {
					if service == nil {
						return nil, sceneryruntime.ContractSystemError(fmt.Errorf("service is not initialized"))
					}
					copied, err := contract.ClonePublicStorageProbeInput(payload.(contract.PublicStorageProbeInput))
					if err != nil {
						return nil, sceneryruntime.ContractSystemError(err)
					}
					outcome, err := service.PublicStorageProbe(ctx, copied)
					if err != nil {
						if outcome != nil {
							return nil, sceneryruntime.ContractSystemError(fmt.Errorf("handler returned outcome and error"))
						}
						return nil, sceneryruntime.ContractSystemError(err)
					}
					if outcome == nil {
						return nil, sceneryruntime.ContractSystemError(fmt.Errorf("handler returned nil outcome without error"))
					}
					cloned, err := contract.ClonePublicStorageProbeOutcome(outcome)
					if err != nil {
						return nil, sceneryruntime.ContractSystemError(err)
					}
					if err := sceneryruntime.PublishContractOperationOutcome(ctx, "service/operation/public_storage_probe", cloned); err != nil {
						return nil, sceneryruntime.ContractSystemError(err)
					}
					return cloned, nil
				},
				EncodeContractOutcome: func(request *http.Request, outcome any) (sceneryruntime.ContractHTTPResponse, error) {
					_ = request
					switch typed := outcome.(type) {
					case contract.PublicStorageProbeOk:
						response, err := sceneryruntime.EncodeContractRepresentationWithOptions(request, 200, typed.Value, "json", []string{"application/json"}, sceneryruntime.ContractResponseOptions{MaxBytes: 16777216, CompressionAlgorithms: []string{"gzip"}, CompressionThreshold: 1024, TypeExpression: "record.object_summary", EncodeValue: func(value any) ([]byte, error) { return scenery.MarshalContractValue(value, "record.object_summary") }})
						if err != nil {
							return sceneryruntime.ContractHTTPResponse{}, err
						}
						return response, nil
					default:
						return sceneryruntime.ContractHTTPResponse{}, fmt.Errorf("handler returned an unknown outcome %T", outcome)
					}
				},
			}); err != nil {
				return err
			}
			if err := sceneryruntime.RegisterEndpointChecked(&sceneryruntime.Endpoint{Service: "service", Name: "ReadPublicStorageProbeHttp", Access: sceneryruntime.Public, Path: "/storage/probe-public", Methods: []string{"GET"},
				ContractPolicy: &sceneryruntime.ContractHTTPPolicy{BindingAddress: "service/binding/read_public_storage_probe_http", GatewayAddress: "app/http_gateway/public_api", CORS: "none", AllowedOrigins: []string{}, Forwarded: "reject", TrustedProxyPrefixes: []string{}, MaxRequestHeaderBytes: 65536, MaxResponseBytes: 16777216, CompressionAlgorithms: []string{"gzip"}, CompressionThreshold: 1024, TotalInvocationTimeoutNanos: 2400000000000, ReadTimeoutNanos: 30000000000, WriteTimeoutNanos: 30000000000, IdleTimeoutNanos: 120000000000, AuthorizationStrategy: "public", AuthorizationRuleCount: 0, AuthorizationRules: []sceneryruntime.ContractAuthorizationRule{}, PipelineSteps: []string{}, FrameworkGuarantee: "framework_enforced", TransportStatuses: map[string]int{"admission.rate_limited": 429, "result.ok": 200, "system.internal": 500, "transport.invalid_request": 400, "transport.not_acceptable": 406}},
				DecodeContractRequest: func(request *http.Request, pathValues map[string]string) (sceneryruntime.ContractDecodedRequest, error) {
					input, err := sceneryruntime.DecodeContractInput[contract.ReadPublicStorageProbeInput](request, pathValues, sceneryruntime.ContractRequestSchema{Mappings: []sceneryruntime.ContractInputMapping{}, ContextMappings: []sceneryruntime.ContractContextMapping{}, Body: nil, TransportStatuses: map[string]int{"admission.rate_limited": 429, "system.internal": 500, "transport.invalid_request": 400, "transport.not_acceptable": 406}})
					return sceneryruntime.ContractDecodedRequest{Payload: input}, err
				},
				Invoke: func(ctx context.Context, _ []any, payload any) (any, error) {
					if service == nil {
						return nil, sceneryruntime.ContractSystemError(fmt.Errorf("service is not initialized"))
					}
					copied, err := contract.CloneReadPublicStorageProbeInput(payload.(contract.ReadPublicStorageProbeInput))
					if err != nil {
						return nil, sceneryruntime.ContractSystemError(err)
					}
					outcome, err := service.ReadPublicStorageProbe(ctx, copied)
					if err != nil {
						if outcome != nil {
							return nil, sceneryruntime.ContractSystemError(fmt.Errorf("handler returned outcome and error"))
						}
						return nil, sceneryruntime.ContractSystemError(err)
					}
					if outcome == nil {
						return nil, sceneryruntime.ContractSystemError(fmt.Errorf("handler returned nil outcome without error"))
					}
					cloned, err := contract.CloneReadPublicStorageProbeOutcome(outcome)
					if err != nil {
						return nil, sceneryruntime.ContractSystemError(err)
					}
					if err := sceneryruntime.PublishContractOperationOutcome(ctx, "service/operation/read_public_storage_probe", cloned); err != nil {
						return nil, sceneryruntime.ContractSystemError(err)
					}
					return cloned, nil
				},
				EncodeContractOutcome: func(request *http.Request, outcome any) (sceneryruntime.ContractHTTPResponse, error) {
					_ = request
					switch typed := outcome.(type) {
					case contract.ReadPublicStorageProbeOk:
						response, err := sceneryruntime.EncodeContractRepresentationWithOptions(request, 200, typed.Value, "json", []string{"application/json"}, sceneryruntime.ContractResponseOptions{MaxBytes: 16777216, CompressionAlgorithms: []string{"gzip"}, CompressionThreshold: 1024, TypeExpression: "record.object_summary", EncodeValue: func(value any) ([]byte, error) { return scenery.MarshalContractValue(value, "record.object_summary") }})
						if err != nil {
							return sceneryruntime.ContractHTTPResponse{}, err
						}
						return response, nil
					default:
						return sceneryruntime.ContractHTTPResponse{}, fmt.Errorf("handler returned an unknown outcome %T", outcome)
					}
				},
			}); err != nil {
				return err
			}
			return nil
		},
	})
}
