package uireport

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	appcfg "scenery.sh/internal/app"
)

// Collect scans configured frontend roots without modifying the target app.
func Collect(appRoot string, cfg appcfg.Config, frontendFilter string) (Report, error) {
	names := make([]string, 0, len(cfg.Frontends))
	for name := range cfg.Frontends {
		names = append(names, name)
	}
	sort.Strings(names)

	if frontendFilter != "" {
		if _, ok := cfg.Frontends[frontendFilter]; !ok {
			return Report{}, fmt.Errorf("frontend %q is not configured", frontendFilter)
		}
		names = []string{frontendFilter}
	}

	report := Report{Frontends: make([]FrontendReport, 0, len(names))}
	for _, name := range names {
		frontend := cfg.Frontends[name]
		item := FrontendReport{
			Name:         name,
			Root:         filepath.ToSlash(filepath.Clean(frontend.Root)),
			DesignSystem: "none",
			Files:        []FileReport{},
		}
		if strings.TrimSpace(frontend.Root) == "" {
			item.Root = ""
			report.Frontends = append(report.Frontends, item)
			continue
		}
		files, err := collectFrontendFiles(appRoot, frontend.Root)
		if err != nil {
			return Report{}, fmt.Errorf("frontend %q: %w", name, err)
		}
		scanned := Scan(files)
		hasDesignSystem := false
		for _, file := range scanned {
			if file.designSystemImports > 0 {
				hasDesignSystem = true
				break
			}
		}
		if hasDesignSystem {
			item.DesignSystem = "astryx"
			item.Files = scanned
			item.Totals = aggregate(scanned)
		}
		report.Frontends = append(report.Frontends, item)
	}
	return report, nil
}

func collectFrontendFiles(appRoot, configuredRoot string) ([]SourceFile, error) {
	appAbs, err := filepath.Abs(appRoot)
	if err != nil {
		return nil, err
	}
	frontendAbs, err := filepath.Abs(filepath.Join(appAbs, configuredRoot))
	if err != nil {
		return nil, err
	}
	if !pathWithin(appAbs, frontendAbs) {
		return nil, fmt.Errorf("root %q escapes the app root", configuredRoot)
	}
	info, err := os.Stat(frontendAbs)
	if err != nil {
		return nil, err
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("root %q is not a directory", configuredRoot)
	}
	if resolvedApp, resolveErr := filepath.EvalSymlinks(appAbs); resolveErr == nil {
		if resolvedFrontend, resolveFrontendErr := filepath.EvalSymlinks(frontendAbs); resolveFrontendErr == nil && !pathWithin(resolvedApp, resolvedFrontend) {
			return nil, fmt.Errorf("root %q resolves outside the app root", configuredRoot)
		}
	}

	var files []SourceFile
	err = filepath.WalkDir(frontendAbs, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if path != frontendAbs && excludedDirectory(entry.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if !isReactSource(entry.Name()) {
			return nil
		}
		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		if isGeneratedSource(content) {
			return nil
		}
		relative, relErr := filepath.Rel(frontendAbs, path)
		if relErr != nil {
			return relErr
		}
		files = append(files, SourceFile{Path: filepath.ToSlash(relative), Content: content})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

func pathWithin(root, candidate string) bool {
	relative, err := filepath.Rel(root, candidate)
	return err == nil && relative != ".." && !strings.HasPrefix(relative, ".."+string(filepath.Separator))
}

func excludedDirectory(name string) bool {
	if strings.HasPrefix(name, ".") {
		return true
	}
	switch name {
	case "node_modules", "generated", "scenery-ui", "dist", "build", "coverage", "__tests__":
		return true
	default:
		return false
	}
}

func isReactSource(name string) bool {
	lower := strings.ToLower(name)
	if !strings.HasSuffix(lower, ".tsx") && !strings.HasSuffix(lower, ".jsx") {
		return false
	}
	return !strings.Contains(lower, ".test.") &&
		!strings.Contains(lower, ".spec.") &&
		!strings.HasSuffix(lower, "_test.tsx") &&
		!strings.HasSuffix(lower, "_test.jsx")
}

func isGeneratedSource(content []byte) bool {
	trimmed := strings.TrimSpace(string(content))
	return strings.HasPrefix(trimmed, "// Code generated by Scenery. DO NOT EDIT.") ||
		strings.HasPrefix(trimmed, "/* Code generated by Scenery. DO NOT EDIT. */")
}
