// Code generated by Scenery vNext. DO NOT EDIT.
package composition

import (
	adapter0 "example.com/storagebasic/internal/scenerygen/service_service_adapter"
	scenery "scenery.sh"
)

const ContractRevision = "sha256:9fc22974ac02542ff7b31fa7b556f410395cdedb5b613f7c7e2bb73056b5241b"

var RequiredAddresses = []string{"service/binding/public_storage_probe_http", "service/binding/read_public_storage_probe_http", "service/execution/public_storage_probe_direct", "service/execution/read_public_storage_probe_direct", "service/operation/public_storage_probe", "service/operation/read_public_storage_probe", "service/service/service"}

var RequiredProviderABIs = map[string]string{}

func Register(registry scenery.Registry) error {
	if err := adapter0.Register(registry); err != nil {
		return err
	}
	return nil
}
