// Code generated by Scenery. DO NOT EDIT.
package composition

import (
	adapter0 "example.com/storagebasic/internal/scenerygen/service_service_adapter"
	scenery "scenery.sh"
)

const ContractRevision = "sha256:50426c5811f184cc12eab3202e5b2a4ee06756eddb3ffe944066102f842bc30e"

var RequiredAddresses = []string{"service/binding/public_storage_probe_http", "service/binding/read_public_storage_probe_http", "service/execution/public_storage_probe_direct", "service/execution/read_public_storage_probe_direct", "service/operation/public_storage_probe", "service/operation/read_public_storage_probe", "service/service/service"}

var RequiredProviderABIs = map[string]string{}

func Register(registry scenery.Registry) error {
	if err := adapter0.Register(registry); err != nil {
		return err
	}
	return nil
}
