package clientgen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"scenery.sh/internal/wire"
	"scenery.sh/internal/wiremodel"
)

func (g *tsGenerator) render() ([]byte, error) {
	slug := strings.TrimSpace(g.opts.AppSlug)
	if slug == "" {
		slug = strings.TrimSpace(g.app.Name)
	}
	if slug == "" {
		slug = "scenery"
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by scenery. DO NOT EDIT.\n\n")
	buf.WriteString("/* eslint-disable */\n")
	buf.WriteString("/* jshint ignore:start */\n")
	buf.WriteString("/* jslint-disable */\n\n")
	buf.WriteString("export type BaseURL = string\n\n")
	buf.WriteString(`export const Local: BaseURL = "http://localhost:4000"` + "\n\n")
	buf.WriteString("export function Environment(name: string): BaseURL {\n")
	buf.WriteString(fmt.Sprintf("    return `https://${name}-%s.encr.app`\n", slug))
	buf.WriteString("}\n\n")
	buf.WriteString("export function PreviewEnv(pr: number | string): BaseURL {\n")
	buf.WriteString("    return Environment(`pr${pr}`)\n")
	buf.WriteString("}\n\n")
	buf.WriteString(`const BROWSER = typeof globalThis === "object" && ("window" in globalThis)` + "\n\n")
	capabilities := wiremodel.AppCapabilities(g.app)
	buf.WriteString(fmt.Sprintf("const SCENERY_WIRE_SCHEMA_HASH = %q\n", capabilities.SchemaHash))
	buf.WriteString(fmt.Sprintf("const CLIENT_APP_SLUG = %q\n", slug))
	buf.WriteString(fmt.Sprintf("const SCENERY_WIRE_CONTENT_TYPE = %q\n", wire.ContentType))
	buf.WriteString(fmt.Sprintf("const SCENERY_WIRE_JSON_CONTENT_TYPE = %q\n\n", wire.JSONContentType))

	serviceNames := make([]string, 0, len(g.namespaces))
	serviceNames = append(serviceNames, namespaceNamesWithMethods(g.namespaces)...)
	if g.opts.StandardAuth {
		serviceNames = appendMissing(serviceNames, "auth", "users")
	}
	sort.Strings(serviceNames)

	buf.WriteString("export default class Client {\n")
	buf.WriteString("    public readonly storage: StorageClient\n")
	for _, svcName := range serviceNames {
		buf.WriteString(fmt.Sprintf("    public readonly %s: %s.ServiceClient\n", svcName, svcName))
	}
	buf.WriteString("    private readonly options: ClientOptions\n")
	buf.WriteString("    private readonly target: string\n\n")
	buf.WriteString("    constructor(target: string, token?: string)\n")
	buf.WriteString("    constructor(target: BaseURL, options?: ClientOptions)\n")
	buf.WriteString(`    constructor(target: string | BaseURL = "prod", options?: string | ClientOptions) {` + "\n")
	buf.WriteString(`        if (!target.startsWith("http://") && !target.startsWith("https://")) {` + "\n")
	buf.WriteString("            target = Environment(target)\n")
	buf.WriteString("        }\n\n")
	buf.WriteString(`        if (typeof options === "string") {` + "\n")
	buf.WriteString("            options = { auth: options }\n")
	buf.WriteString("        }\n\n")
	buf.WriteString("        this.target = target\n")
	buf.WriteString("        this.options = options ?? {}\n")
	buf.WriteString("        const base = new BaseClient(this.target, this.options)\n")
	buf.WriteString("        this.storage = new StorageClient(base)\n")
	for _, svcName := range serviceNames {
		buf.WriteString(fmt.Sprintf("        this.%s = new %s.ServiceClient(base)\n", svcName, svcName))
	}
	buf.WriteString("    }\n\n")
	buf.WriteString("    public with(options: ClientOptions): Client {\n")
	buf.WriteString("        return new Client(this.target, {\n")
	buf.WriteString("            ...this.options,\n")
	buf.WriteString("            ...options,\n")
	buf.WriteString("        })\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	buf.WriteString("export interface ClientOptions {\n")
	buf.WriteString("    fetcher?: Fetcher\n")
	buf.WriteString(`    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }` + "\n")
	buf.WriteString("    auth?: string | AuthDataGenerator\n")
	buf.WriteString("    transport?: SceneryTransport\n")
	buf.WriteString("    disableCapabilityPreflight?: boolean\n")
	buf.WriteString("    wireRecovery?: boolean\n")
	buf.WriteString("}\n\n")

	namespaceNames := make([]string, 0, len(g.namespaces))
	for name := range g.namespaces {
		namespaceNames = append(namespaceNames, name)
	}
	sort.Strings(namespaceNames)
	for _, name := range namespaceNames {
		if !tsIdentifier.MatchString(name) {
			continue
		}
		ns := g.namespaces[name]
		if len(ns.methods) == 0 && len(ns.typeOrder) == 0 {
			continue
		}
		buf.WriteString(fmt.Sprintf("export namespace %s {\n", ns.Name))
		for _, typeName := range ns.typeOrder {
			def := ns.types[typeName]
			if def == "" {
				continue
			}
			buf.WriteString(indentBlock(def, 1))
			buf.WriteString("\n\n")
		}
		if len(ns.methods) > 0 {
			buf.WriteString("    export class ServiceClient {\n")
			buf.WriteString("        private baseClient: BaseClient\n\n")
			buf.WriteString("        constructor(baseClient: BaseClient) {\n")
			buf.WriteString("            this.baseClient = baseClient\n")
			for _, method := range ns.methods {
				for _, name := range methodNamesFromRendered(method) {
					buf.WriteString(fmt.Sprintf("            this.%s = this.%s.bind(this)\n", name, name))
				}
			}
			buf.WriteString("        }\n\n")
			for i, method := range ns.methods {
				buf.WriteString(indentBlock(method, 2))
				if i != len(ns.methods)-1 {
					buf.WriteString("\n\n")
				}
			}
			buf.WriteString("\n    }\n")
		}
		buf.WriteString("}\n\n")
	}
	if g.opts.StandardAuth {
		writeStandardAuthNamespaces(&buf)
	}

	writeStorageClient(&buf)

	buf.WriteString("export type JSONValue = string | number | boolean | null | JSONValue[] | {[key: string]: JSONValue}\n\n")
	buf.WriteString("function encodeQuery(parts: Record<string, string | string[]>): string {\n")
	buf.WriteString("    const pairs: string[] = []\n")
	buf.WriteString("    for (const key in parts) {\n")
	buf.WriteString("        const val = (Array.isArray(parts[key]) ? parts[key] : [parts[key]]) as string[]\n")
	buf.WriteString("        for (const v of val) {\n")
	buf.WriteString("            pairs.push(`${key}=${encodeURIComponent(v)}`)\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return pairs.join(\"&\")\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// @ts-ignore - TS ignore because makeRecord is not always used\n")
	buf.WriteString("function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {\n")
	buf.WriteString("    for (const key in record) {\n")
	buf.WriteString("        if (record[key] === undefined) {\n")
	buf.WriteString("            delete record[key]\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return record as Record<K, V>\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodePathWildcard(value: string): string {\n")
	buf.WriteString("    return value.split(\"/\").map((part) => encodeURIComponent(part)).join(\"/\")\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodeQueryValue(value: unknown): string | string[] | undefined {\n")
	buf.WriteString("    if (value === undefined || value === null) {\n")
	buf.WriteString("        return undefined\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (Array.isArray(value)) {\n")
	buf.WriteString("        return value.map((item) => String(item))\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (typeof value === \"object\") {\n")
	buf.WriteString("        return JSON.stringify(value)\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return String(value)\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodeHeaderValue(value: unknown): string | undefined {\n")
	buf.WriteString("    if (value === undefined || value === null) {\n")
	buf.WriteString("        return undefined\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (Array.isArray(value)) {\n")
	buf.WriteString("        return value.map((item) => String(item)).join(\",\")\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (typeof value === \"object\") {\n")
	buf.WriteString("        return JSON.stringify(value)\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return String(value)\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodeCookieHeader(values: Record<string, string>): string | undefined {\n")
	buf.WriteString("    const pairs: string[] = []\n")
	buf.WriteString("    for (const key in values) {\n")
	buf.WriteString("        pairs.push(`${encodeURIComponent(key)}=${encodeURIComponent(values[key])}`)\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (pairs.length === 0) {\n")
	buf.WriteString("        return undefined\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return pairs.join(\"; \")\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// Keep helper symbols referenced for strict TS noUnusedLocals.\n")
	buf.WriteString("void makeRecord\n")
	buf.WriteString("void encodePathWildcard\n")
	buf.WriteString("void encodeQueryValue\n")
	buf.WriteString("void encodeHeaderValue\n")
	buf.WriteString("void encodeCookieHeader\n\n")
	buf.WriteString(`export type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {` + "\n")
	buf.WriteString("    headers?: Record<string, string>\n")
	buf.WriteString("    query?: Record<string, string | string[]>\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export interface APIResponse<T> {\n")
	buf.WriteString("    data: T\n")
	buf.WriteString("    headers: Headers\n")
	buf.WriteString("    status: number\n")
	buf.WriteString("    response: Response\n")
	buf.WriteString("    txid: Txid | null\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export type Txid = number\n\n")
	buf.WriteString("export type SceneryTransport = \"auto\" | \"json\" | \"binary\" | \"binary-strict\" | \"wire-json\" | \"wire-json-strict\"\n\n")
	buf.WriteString("export type AuthDataGenerator = () =>\n")
	buf.WriteString("  | string\n")
	buf.WriteString("  | Promise<string | undefined>\n")
	buf.WriteString("  | undefined\n\n")
	buf.WriteString("export type Fetcher = typeof fetch\n\n")
	buf.WriteString("const boundFetch = fetch.bind(globalThis)\n\n")
	buf.WriteString("class BaseClient {\n")
	buf.WriteString("    readonly baseURL: string\n")
	buf.WriteString("    readonly fetcher: Fetcher\n")
	buf.WriteString("    readonly headers: Record<string, string>\n")
	buf.WriteString(`    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }` + "\n")
	buf.WriteString("    readonly authGenerator?: AuthDataGenerator\n\n")
	buf.WriteString("    readonly transport: SceneryTransport\n")
	buf.WriteString("    readonly disableCapabilityPreflight: boolean\n")
	buf.WriteString("    readonly wireRecovery: boolean\n")
	buf.WriteString("    private capabilitiesPromise?: Promise<WireCapabilities | null>\n")
	buf.WriteString("    private readonly wireEndpointCache = new Map<string, boolean>()\n\n")
	buf.WriteString("    constructor(baseURL: string, options: ClientOptions) {\n")
	buf.WriteString("        this.baseURL = baseURL\n")
	buf.WriteString("        this.headers = {}\n")
	buf.WriteString("        if (!BROWSER) {\n")
	buf.WriteString(fmt.Sprintf("            this.headers[\"User-Agent\"] = %q\n", slug+"-Generated-TS-Client (scenery)"))
	buf.WriteString("        }\n")
	buf.WriteString("        this.requestInit = options.requestInit ?? {}\n")
	buf.WriteString("        this.fetcher = options.fetcher ?? boundFetch\n")
	buf.WriteString("        this.transport = options.transport ?? \"auto\"\n")
	buf.WriteString("        this.disableCapabilityPreflight = options.disableCapabilityPreflight ?? false\n")
	buf.WriteString("        this.wireRecovery = options.wireRecovery ?? false\n")
	buf.WriteString("        if (options.auth !== undefined) {\n")
	buf.WriteString("            const auth = options.auth\n")
	buf.WriteString("            if (typeof auth === \"function\") {\n")
	buf.WriteString("                this.authGenerator = auth\n")
	buf.WriteString("            } else {\n")
	buf.WriteString("                this.authGenerator = () => auth\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    async getAuthData(): Promise<CallParameters | undefined> {\n")
	buf.WriteString("        let authData: string | undefined\n")
	buf.WriteString("        if (this.authGenerator) {\n")
	buf.WriteString("            const maybePromise = this.authGenerator()\n")
	buf.WriteString("            if (maybePromise instanceof Promise) {\n")
	buf.WriteString("                authData = await maybePromise\n")
	buf.WriteString("            } else {\n")
	buf.WriteString("                authData = maybePromise\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if (!authData) {\n")
	buf.WriteString("            return undefined\n")
	buf.WriteString("        }\n")
	buf.WriteString("        return { headers: { Authorization: \"Bearer \" + authData } }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callTypedEndpoint(spec: TypedEndpointCall): Promise<Response | unknown> {\n")
	buf.WriteString("        if (this.transport === \"json\" || !spec.binaryAvailable) {\n")
	buf.WriteString("            if (this.transport === \"binary-strict\" && !spec.binaryAvailable) {\n")
	buf.WriteString("                throw new SceneryWireFallbackError(`wire transport unavailable for ${spec.endpointID}`)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if (this.transport === \"wire-json-strict\") {\n")
	buf.WriteString("            return await this.callWireJSONAPI(spec)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if ((this.transport === \"auto\" || this.transport === \"binary\") && !this.disableCapabilityPreflight) {\n")
	buf.WriteString("            let endpointAvailable = this.wireEndpointCache.get(spec.endpointID)\n")
	buf.WriteString("            if (endpointAvailable === undefined) {\n")
	buf.WriteString("                const capabilities = await this.getWireCapabilities()\n")
	buf.WriteString("                const endpoint = capabilities?.endpoints?.[spec.endpointID]\n")
	buf.WriteString("                endpointAvailable = !!capabilities && capabilities.wire_schema_hash === SCENERY_WIRE_SCHEMA_HASH && !!endpoint?.available && endpoint.schema_hash === spec.schemaHash\n")
	buf.WriteString("                this.wireEndpointCache.set(spec.endpointID, endpointAvailable)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (!endpointAvailable) {\n")
	buf.WriteString("                return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            if (this.transport === \"wire-json\") {\n")
	buf.WriteString("                return await this.callWireJSONAPI(spec)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            return await this.callWireAPI(spec)\n")
	buf.WriteString("        } catch (err) {\n")
	buf.WriteString("            if (err instanceof APIError) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (this.transport !== \"binary-strict\" && !(err instanceof SceneryWireFallbackError)) {\n")
	buf.WriteString("                return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (this.transport !== \"binary-strict\" && err instanceof SceneryWireFallbackError && spec.safeJSONRetry) {\n")
	buf.WriteString("                return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw err\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callTypedEndpointWithMeta(spec: TypedEndpointCall): Promise<TypedEndpointResultWithMeta> {\n")
	buf.WriteString("        if (this.transport === \"json\" || !spec.binaryAvailable) {\n")
	buf.WriteString("            if (this.transport === \"binary-strict\" && !spec.binaryAvailable) {\n")
	buf.WriteString("                throw new SceneryWireFallbackError(`wire transport unavailable for ${spec.endpointID}`)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            return this.callTypedAPIWithMeta(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if (this.transport === \"wire-json-strict\") {\n")
	buf.WriteString("            return await this.callWireJSONAPIWithMeta(spec)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if ((this.transport === \"auto\" || this.transport === \"binary\") && !this.disableCapabilityPreflight) {\n")
	buf.WriteString("            let endpointAvailable = this.wireEndpointCache.get(spec.endpointID)\n")
	buf.WriteString("            if (endpointAvailable === undefined) {\n")
	buf.WriteString("                const capabilities = await this.getWireCapabilities()\n")
	buf.WriteString("                const endpoint = capabilities?.endpoints?.[spec.endpointID]\n")
	buf.WriteString("                endpointAvailable = !!capabilities && capabilities.wire_schema_hash === SCENERY_WIRE_SCHEMA_HASH && !!endpoint?.available && endpoint.schema_hash === spec.schemaHash\n")
	buf.WriteString("                this.wireEndpointCache.set(spec.endpointID, endpointAvailable)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (!endpointAvailable) {\n")
	buf.WriteString("                return this.callTypedAPIWithMeta(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            if (this.transport === \"wire-json\") {\n")
	buf.WriteString("                return await this.callWireJSONAPIWithMeta(spec)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            return await this.callWireAPIWithMeta(spec)\n")
	buf.WriteString("        } catch (err) {\n")
	buf.WriteString("            if (err instanceof APIError) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (this.transport !== \"binary-strict\" && !(err instanceof SceneryWireFallbackError)) {\n")
	buf.WriteString("                return this.callTypedAPIWithMeta(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (this.transport !== \"binary-strict\" && err instanceof SceneryWireFallbackError && spec.safeJSONRetry) {\n")
	buf.WriteString("                return this.callTypedAPIWithMeta(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw err\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async callWireJSONAPI(spec: TypedEndpointCall): Promise<unknown> {\n")
	buf.WriteString("        const body = spec.payloadJSON ?? \"null\"\n")
	buf.WriteString("        const wireHeaders: Record<string, string> = {\n")
	buf.WriteString("            ...spec.params?.headers,\n")
	buf.WriteString("            \"Content-Type\": SCENERY_WIRE_JSON_CONTENT_TYPE,\n")
	buf.WriteString("            \"X-Scenery-Wire-Schema-Hash\": spec.schemaHash,\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if (spec.pathParams !== undefined) {\n")
	buf.WriteString("            wireHeaders[\"X-Scenery-Wire-Path-Params\"] = JSON.stringify(spec.pathParams)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        const response = await this.callAPI(\"POST\", spec.wirePath, body, {\n")
	buf.WriteString("            ...spec.params,\n")
	buf.WriteString("            headers: wireHeaders,\n")
	buf.WriteString("        })\n")
	buf.WriteString("        return await response.json()\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async callWireJSONAPIWithMeta(spec: TypedEndpointCall): Promise<TypedEndpointResultWithMeta> {\n")
	buf.WriteString("        const body = spec.payloadJSON ?? \"null\"\n")
	buf.WriteString("        const wireHeaders: Record<string, string> = {\n")
	buf.WriteString("            ...spec.params?.headers,\n")
	buf.WriteString("            \"Content-Type\": SCENERY_WIRE_JSON_CONTENT_TYPE,\n")
	buf.WriteString("            \"X-Scenery-Wire-Schema-Hash\": spec.schemaHash,\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if (spec.pathParams !== undefined) {\n")
	buf.WriteString("            wireHeaders[\"X-Scenery-Wire-Path-Params\"] = JSON.stringify(spec.pathParams)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        const response = await this.callAPI(\"POST\", spec.wirePath, body, {\n")
	buf.WriteString("            ...spec.params,\n")
	buf.WriteString("            headers: wireHeaders,\n")
	buf.WriteString("        })\n")
	buf.WriteString("        return {\n")
	buf.WriteString("            body: await response.json(),\n")
	buf.WriteString("            headers: response.headers,\n")
	buf.WriteString("            status: response.status,\n")
	buf.WriteString("            response,\n")
	buf.WriteString("            txid: txidFromHeaders(response.headers),\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async callWireAPI(spec: TypedEndpointCall): Promise<unknown> {\n")
	buf.WriteString("        const callID = this.wireRecovery ? makeSceneryCallID() : \"\"\n")
	buf.WriteString("        const payload = encodeSceneryWireRequest(spec)\n")
	buf.WriteString("        const wireHeaders: Record<string, string> = {\n")
	buf.WriteString("            ...spec.params?.headers,\n")
	buf.WriteString("            \"Content-Type\": SCENERY_WIRE_CONTENT_TYPE,\n")
	buf.WriteString("            \"X-Scenery-Wire-Schema-Hash\": spec.schemaHash,\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if (callID !== \"\") {\n")
	buf.WriteString("            wireHeaders[\"X-Scenery-Call-ID\"] = callID\n")
	buf.WriteString("        }\n")
	buf.WriteString("        const wireParams: CallParameters = {\n")
	buf.WriteString("            ...spec.params,\n")
	buf.WriteString("            headers: wireHeaders,\n")
	buf.WriteString("        }\n")
	buf.WriteString("        let response: Response\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            response = await this.callAPI(\"POST\", spec.wirePath, payload as BodyInit, wireParams)\n")
	buf.WriteString("        } catch (err) {\n")
	buf.WriteString("            if (err instanceof APIError) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw err\n")
	buf.WriteString("        }\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            return await response.json()\n")
	buf.WriteString("        } catch (err) {\n")
	buf.WriteString("            if (err instanceof APIError) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (callID !== \"\") {\n")
	buf.WriteString("                const recovered = await this.recoverWireCall(callID)\n")
	buf.WriteString("                if (recovered) {\n")
	buf.WriteString("                    return resultFromRecoveredWire(recovered)\n")
	buf.WriteString("                }\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (spec.safeJSONRetry) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw new SceneryWireFallbackError(`wire response decode failed for ${spec.endpointID}: ${String(err)}`)\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async callWireAPIWithMeta(spec: TypedEndpointCall): Promise<TypedEndpointResultWithMeta> {\n")
	buf.WriteString("        const callID = this.wireRecovery ? makeSceneryCallID() : \"\"\n")
	buf.WriteString("        const payload = encodeSceneryWireRequest(spec)\n")
	buf.WriteString("        const wireHeaders: Record<string, string> = {\n")
	buf.WriteString("            ...spec.params?.headers,\n")
	buf.WriteString("            \"Content-Type\": SCENERY_WIRE_CONTENT_TYPE,\n")
	buf.WriteString("            \"X-Scenery-Wire-Schema-Hash\": spec.schemaHash,\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if (callID !== \"\") {\n")
	buf.WriteString("            wireHeaders[\"X-Scenery-Call-ID\"] = callID\n")
	buf.WriteString("        }\n")
	buf.WriteString("        const wireParams: CallParameters = {\n")
	buf.WriteString("            ...spec.params,\n")
	buf.WriteString("            headers: wireHeaders,\n")
	buf.WriteString("        }\n")
	buf.WriteString("        let response: Response\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            response = await this.callAPI(\"POST\", spec.wirePath, payload as BodyInit, wireParams)\n")
	buf.WriteString("        } catch (err) {\n")
	buf.WriteString("            if (err instanceof APIError) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw err\n")
	buf.WriteString("        }\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            return {\n")
	buf.WriteString("                body: await response.json(),\n")
	buf.WriteString("                headers: response.headers,\n")
	buf.WriteString("                status: response.status,\n")
	buf.WriteString("                response,\n")
	buf.WriteString("                txid: txidFromHeaders(response.headers),\n")
	buf.WriteString("            }\n")
	buf.WriteString("        } catch (err) {\n")
	buf.WriteString("            if (err instanceof APIError) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (callID !== \"\") {\n")
	buf.WriteString("                const recovered = await this.recoverWireCall(callID)\n")
	buf.WriteString("                if (recovered) {\n")
	buf.WriteString("                    return {\n")
	buf.WriteString("                        body: resultFromRecoveredWire(recovered),\n")
	buf.WriteString("                        headers: response.headers,\n")
	buf.WriteString("                        status: response.status,\n")
	buf.WriteString("                        response,\n")
	buf.WriteString("                        txid: txidFromHeaders(response.headers),\n")
	buf.WriteString("                    }\n")
	buf.WriteString("                }\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (spec.safeJSONRetry) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw new SceneryWireFallbackError(`wire response decode failed for ${spec.endpointID}: ${String(err)}`)\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async getWireCapabilities(): Promise<WireCapabilities | null> {\n")
	buf.WriteString("        if (!this.capabilitiesPromise) {\n")
	buf.WriteString("            this.capabilitiesPromise = (async () => {\n")
	buf.WriteString("                try {\n")
	buf.WriteString("                    const response = await this.callAPI(\"GET\", \"/_wire/capabilities\")\n")
	buf.WriteString("                    return await response.json() as WireCapabilities\n")
	buf.WriteString("                } catch {\n")
	buf.WriteString("                    return null\n")
	buf.WriteString("                }\n")
	buf.WriteString("            })()\n")
	buf.WriteString("        }\n")
	buf.WriteString("        return this.capabilitiesPromise\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async recoverWireCall(callID: string): Promise<RecoveredWireResponse | null> {\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            const response = await this.callAPI(\"GET\", `/_wire/recover/${encodeURIComponent(callID)}`)\n")
	buf.WriteString("            return await response.json() as RecoveredWireResponse\n")
	buf.WriteString("        } catch {\n")
	buf.WriteString("            return null\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callTypedAPI(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<Response> {\n")
	buf.WriteString("        return this.callAPI(method, path, body, {\n")
	buf.WriteString("            ...params,\n")
	buf.WriteString("            headers: { \"Content-Type\": \"application/json\", ...params?.headers },\n")
	buf.WriteString("        })\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callTypedAPIWithMeta(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<TypedEndpointResultWithMeta> {\n")
	buf.WriteString("        const response = await this.callTypedAPI(method, path, body, params)\n")
	buf.WriteString("        return {\n")
	buf.WriteString("            body: response,\n")
	buf.WriteString("            headers: response.headers,\n")
	buf.WriteString("            status: response.status,\n")
	buf.WriteString("            response,\n")
	buf.WriteString("            txid: txidFromHeaders(response.headers),\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callAPI(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<Response> {\n")
	buf.WriteString("        const response = await this.fetchAPI(method, path, body, params)\n")
	buf.WriteString("        if (!response.ok) {\n")
	buf.WriteString("            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }\n")
	buf.WriteString("            try {\n")
	buf.WriteString("                const text = await response.text()\n")
	buf.WriteString("                try {\n")
	buf.WriteString("                    const jsonBody = JSON.parse(text)\n")
	buf.WriteString("                    if (isAPIErrorResponse(jsonBody)) {\n")
	buf.WriteString("                        body = jsonBody\n")
	buf.WriteString("                    } else {\n")
	buf.WriteString("                        body.message += \": \" + JSON.stringify(jsonBody)\n")
	buf.WriteString("                    }\n")
	buf.WriteString("                } catch {\n")
	buf.WriteString("                    body.message += \": \" + text\n")
	buf.WriteString("                }\n")
	buf.WriteString("            } catch (err) {\n")
	buf.WriteString("                body.message += \": \" + String(err)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw new APIError(response.status, body)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        return response\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async fetchAPI(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<Response> {\n")
	buf.WriteString("        let { query, headers, ...rest } = params ?? {}\n")
	buf.WriteString("        const init = {\n")
	buf.WriteString("            ...this.requestInit,\n")
	buf.WriteString("            ...rest,\n")
	buf.WriteString("            method,\n")
	buf.WriteString("            body: body ?? null,\n")
	buf.WriteString("        }\n")
	buf.WriteString("        init.headers = { ...this.headers, ...init.headers, ...headers }\n")
	buf.WriteString("        const authData = await this.getAuthData()\n")
	buf.WriteString("        if (authData) {\n")
	buf.WriteString("            if (authData.query) {\n")
	buf.WriteString("                query = { ...query, ...authData.query }\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (authData.headers) {\n")
	buf.WriteString("                init.headers = { ...init.headers, ...authData.headers }\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("        const queryString = query ? \"?\" + encodeQuery(query) : \"\"\n")
	buf.WriteString("        return await this.fetcher(this.baseURL + path + queryString, init)\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")
	buf.WriteString(`interface TypedEndpointCall {
    endpointID: string
    wirePath: string
    schemaHash: string
    binaryAvailable: boolean
    safeJSONRetry: boolean
    method: string
    path: string
    pathParams?: Record<string, unknown>
    payload?: unknown
    jsonBody?: RequestInit["body"]
    payloadJSON?: string
    params?: CallParameters
}

interface WireCapabilities {
    wire_schema_hash: string
    endpoints: Record<string, {
        available: boolean
        schema_hash?: string
    }>
}

interface RecoveredWireResponse {
    status: number
    result?: unknown
    error?: APIErrorResponse
}

interface TypedEndpointResultWithMeta {
    body: unknown
    headers: Headers
    status: number
    response: Response
    txid?: Txid | null
}

export interface SyncObservationContext {
    app?: string
    appRoot?: string
    sessionID?: string
    apiURL?: string
    syncURL?: string
    syncStreamID?: string
    source?: string
    timeoutMs?: number
    details?: Record<string, unknown>
}

export type TxidObserver = (txid: Txid, timeoutMs?: number) => boolean | Promise<boolean>

export interface SyncObservationDiagnostic {
    kind: "sync_observation_failure"
    mutation_committed: true
    txid: Txid | null
    app?: string
    app_root?: string
    session_id?: string
    api_url?: string
    sync_url?: string
    sync_stream_id?: string
    source?: string
    timeout_ms?: number
    details?: Record<string, unknown>
    observer_error?: {
        name?: string
        message: string
    }
}

export class SceneryWireFallbackError extends Error {
    constructor(message: string) {
        super(message)
        Object.defineProperty(this, "name", {
            value: "SceneryWireFallbackError",
            enumerable: false,
            configurable: true,
        })
        if ((Object as any).setPrototypeOf === undefined) {
            ;(this as any).__proto__ = SceneryWireFallbackError.prototype
        } else {
            Object.setPrototypeOf(this, SceneryWireFallbackError.prototype)
        }
    }
}

export class SyncObservationError extends Error {
    public readonly kind = "sync_observation_failure"
    public readonly mutationCommitted = true
    public readonly txid: Txid | null
    public readonly diagnostic: SyncObservationDiagnostic
    public readonly cause?: unknown

    constructor(txid: Txid | null, context?: SyncObservationContext, cause?: unknown) {
        const diagnostic = buildSyncObservationDiagnostic(txid, context, cause)
        super(formatSyncObservationMessage(diagnostic))
        Object.defineProperty(this, "name", {
            value: "SyncObservationError",
            enumerable: false,
            configurable: true,
        })
        if ((Object as any).setPrototypeOf === undefined) {
            ;(this as any).__proto__ = SyncObservationError.prototype
        } else {
            Object.setPrototypeOf(this, SyncObservationError.prototype)
        }
        if ((Error as any).captureStackTrace !== undefined) {
            ;(Error as any).captureStackTrace(this, this.constructor)
        }
        this.txid = txid
        this.diagnostic = diagnostic
        this.cause = cause
    }
}

export function isSyncObservationError(err: any): err is SyncObservationError {
    return err instanceof SyncObservationError || !!err && err.kind === "sync_observation_failure"
}

export function txidFromHeaders(headers: Headers): Txid | null {
    const raw = headers.get("x-txid") ?? headers.get("X-Txid") ?? headers.get("X-TXID")
    if (!raw) {
        return null
    }
    const parsed = Number(raw)
    return Number.isFinite(parsed) ? parsed : null
}

export function requireTxidFromHeaders(headers: Headers): Txid {
    const txid = txidFromHeaders(headers)
    if (txid === null) {
        throw new SyncObservationError(null, { source: "response-headers" })
    }
    return txid
}

export function txidFromAPIResponse<T>(response: APIResponse<T>): Txid | null {
    return response.txid ?? txidFromHeaders(response.headers)
}

export function requireTxidFromAPIResponse<T>(response: APIResponse<T>): Txid {
    const txid = txidFromAPIResponse(response)
    if (txid === null) {
        throw new SyncObservationError(null, contextFromAPIResponse(response, { source: "api-response" }))
    }
    return txid
}

export async function observeAPIResponseTxid<T>(response: APIResponse<T>, observer: TxidObserver, context?: SyncObservationContext): Promise<APIResponse<T>> {
    const mergedContext = contextFromAPIResponse(response, context)
    const txid = txidFromAPIResponse(response)
    if (txid === null) {
        throw new SyncObservationError(null, mergedContext)
    }
    try {
        const observed = await observer(txid, mergedContext.timeoutMs)
        if (!observed) {
            throw new SyncObservationError(txid, mergedContext, new Error("txid was not observed"))
        }
        return response
    } catch (err) {
        if (err instanceof SyncObservationError) {
            throw err
        }
        throw new SyncObservationError(txid, mergedContext, err)
    }
}

function contextFromAPIResponse<T>(response: APIResponse<T>, context?: SyncObservationContext): SyncObservationContext {
    return {
        ...inferSyncObservationContext(response.response.url),
        ...context,
    }
}

function inferSyncObservationContext(apiURL?: string): SyncObservationContext {
    const context: SyncObservationContext = { app: CLIENT_APP_SLUG }
    if (!apiURL) {
        return context
    }
    context.apiURL = apiURL
    const match = /^https?:\/\/api\.([^.]+)\.[^/:]+(?:\.[^/:]+)*(?::\d+)?(?:\/|$)/.exec(apiURL)
    if (match) {
        context.sessionID = match[1]
        context.syncURL = apiURL.replace("://api.", "://sync.").replace(/\/[^/]*$/, "/")
    }
    return context
}

function buildSyncObservationDiagnostic(txid: Txid | null, context?: SyncObservationContext, cause?: unknown): SyncObservationDiagnostic {
    const diagnostic: SyncObservationDiagnostic = {
        kind: "sync_observation_failure",
        mutation_committed: true,
        txid,
    }
    if (context?.app) diagnostic.app = context.app
    if (context?.appRoot) diagnostic.app_root = context.appRoot
    if (context?.sessionID) diagnostic.session_id = context.sessionID
    if (context?.apiURL) diagnostic.api_url = context.apiURL
    if (context?.syncURL) diagnostic.sync_url = context.syncURL
    if (context?.syncStreamID) diagnostic.sync_stream_id = context.syncStreamID
    if (context?.source) diagnostic.source = context.source
    if (context?.timeoutMs !== undefined) diagnostic.timeout_ms = context.timeoutMs
    if (context?.details) diagnostic.details = context.details
    const observerError = observerErrorDiagnostic(cause)
    if (observerError) {
        diagnostic.observer_error = observerError
    }
    return diagnostic
}

function observerErrorDiagnostic(cause: unknown): { name?: string; message: string } | undefined {
    if (cause === undefined || cause === null) {
        return undefined
    }
    if (cause instanceof Error) {
        return { name: cause.name, message: cause.message }
    }
    return { message: String(cause) }
}

function formatSyncObservationMessage(diagnostic: SyncObservationDiagnostic): string {
    const txid = diagnostic.txid === null ? "unknown txid" : "txid " + String(diagnostic.txid)
    const parts = ["sync observation failed after committed API mutation (" + txid + ")"]
    const details = [
        diagnostic.app ? "app=" + diagnostic.app : "",
        diagnostic.session_id ? "session=" + diagnostic.session_id : "",
        diagnostic.sync_url ? "sync=" + diagnostic.sync_url : "",
        diagnostic.sync_stream_id ? "stream=" + diagnostic.sync_stream_id : "",
    ].filter((part) => part !== "")
    if (details.length > 0) {
        parts.push(details.join(" "))
    }
    if (diagnostic.observer_error?.message) {
        parts.push("observer=" + diagnostic.observer_error.message)
    }
    return parts.join("; ")
}

function makeSceneryCallID(): string {
    const random = new Uint8Array(16)
    const cryptoObj = (globalThis as any).crypto
    if (cryptoObj?.getRandomValues) {
        cryptoObj.getRandomValues(random)
    } else {
        for (let i = 0; i < random.length; i++) {
            random[i] = Math.floor(Math.random() * 256)
        }
    }
    return Array.from(random).map((b) => b.toString(16).padStart(2, "0")).join("")
}

async function decodeTypedResponse(value: Response | unknown): Promise<unknown> {
    if (value instanceof Response) {
        return await value.json()
    }
    return value
}

async function decodeTypedAPIResponse(value: TypedEndpointResultWithMeta): Promise<APIResponse<unknown>> {
    return {
        data: await decodeTypedResponse(value.body),
        headers: value.headers,
        status: value.status,
        response: value.response,
        txid: value.txid ?? txidFromHeaders(value.headers),
    }
}

function typedVoidAPIResponse(value: TypedEndpointResultWithMeta): APIResponse<void> {
    return {
        data: undefined,
        headers: value.headers,
        status: value.status,
        response: value.response,
        txid: value.txid ?? txidFromHeaders(value.headers),
    }
}

function mergeCallParameters(base?: CallParameters, generated?: CallParameters): CallParameters | undefined {
    if (!base) {
        return generated
    }
    if (!generated) {
        return base
    }
    const query = base.query || generated.query ? { ...base.query, ...generated.query } : undefined
    const headers = base.headers || generated.headers ? { ...base.headers, ...generated.headers } : undefined
    return {
        ...base,
        ...generated,
        query,
        headers,
    }
}

function resultFromRecoveredWire(recovered: RecoveredWireResponse): unknown {
    if (recovered.error) {
        throw new APIError(recovered.status || 500, recovered.error)
    }
    return recovered.result ?? null
}

function resultFromWireEnvelope(envelope: any): unknown {
    if (!envelope || typeof envelope !== "object") {
        throw new Error("invalid wire response envelope")
    }
    const status = typeof envelope.status === "number" ? envelope.status : 200
    if (envelope.ok === false) {
        throw new APIError(status, normalizeAPIErrorResponse(envelope.error, status))
    }
    if (typeof envelope.result_json === "string") {
        return JSON.parse(envelope.result_json)
    }
    return envelope.result ?? null
}

function resultFromWireFrame(value: unknown): unknown {
    if (!isSceneryWireFrameResponse(value)) {
        return resultFromWireEnvelope(value)
    }
    const status = value.status || 200
    const payload = value.payloadJSON === "" ? null : JSON.parse(value.payloadJSON)
    if (value.error) {
        throw new APIError(status, normalizeAPIErrorResponse(payload, status))
    }
    return payload
}

function normalizeAPIErrorResponse(value: any, status: number): APIErrorResponse {
    if (isAPIErrorResponse(value)) {
        return value
    }
    return { code: ErrCode.Unknown, message: ` + "`request failed: status ${status}`" + ` }
}

const sceneryWireTextEncoder = new TextEncoder()
const sceneryWireTextDecoder = new TextDecoder()
const sceneryWireMagic = new Uint8Array([80, 87, 66, 49])
const sceneryWireFrameMagic = new Uint8Array([80, 87, 66, 50])
const sceneryWireEmptyBytes = new Uint8Array(0)
const sceneryWireStringCache = new Map<string, Uint8Array>()

void encodeSceneryWire
void decodeSceneryWireResponse
void resultFromWireFrame
void decodeTypedAPIResponse
void typedVoidAPIResponse
void mergeCallParameters

interface SceneryWireFrameResponse {
    __sceneryWireFrame: true
    status: number
    error: boolean
    payloadJSON: string
}

function isSceneryWireFrameResponse(value: unknown): value is SceneryWireFrameResponse {
    return !!value && typeof value === "object" && (value as any).__sceneryWireFrame === true
}

function encodeSceneryWireRequest(spec: TypedEndpointCall): Uint8Array {
    const schema = sceneryWireEmptyBytes
    const pathParams = spec.pathParams === undefined ? sceneryWireEmptyBytes : encodeSceneryWireString(JSON.stringify(spec.pathParams))
    const payload = spec.payloadJSON === undefined ? sceneryWireEmptyBytes : encodeSceneryWireString(spec.payloadJSON)
    const writer = new SceneryWireWriter(sceneryWireFrameMagic.length + schema.length + pathParams.length + payload.length + 30)
    writer.bytes(sceneryWireFrameMagic)
    writer.sizedBytes(schema)
    writer.sizedBytes(pathParams)
    writer.sizedBytes(payload)
    return writer.finish()
}

function encodeSceneryWire(value: unknown): Uint8Array {
    const writer = new SceneryWireWriter()
    writer.bytes(sceneryWireMagic)
    writeSceneryWireValue(writer, value)
    return writer.finish()
}

async function decodeSceneryWireResponse(response: Response): Promise<unknown> {
    const data = new Uint8Array(await response.arrayBuffer())
    if (hasSceneryWireMagic(data, sceneryWireFrameMagic)) {
        return decodeSceneryWireFrame(data)
    }
    return decodeSceneryWire(data)
}

function decodeSceneryWire(data: Uint8Array): unknown {
    if (!hasSceneryWireMagic(data, sceneryWireMagic)) {
        throw new Error("invalid wire payload")
    }
    const reader = new SceneryWireReader(data.subarray(sceneryWireMagic.length))
    const value = reader.value()
    if (!reader.done()) {
        throw new Error("trailing wire payload")
    }
    return value
}

function decodeSceneryWireFrame(data: Uint8Array): SceneryWireFrameResponse {
    const reader = new SceneryWireReader(data.subarray(sceneryWireFrameMagic.length))
    const status = reader.uvarint()
    const flags = reader.byte()
    const payloadJSON = sceneryWireTextDecoder.decode(reader.sizedBytes())
    if (!reader.done()) {
        throw new Error("trailing wire frame payload")
    }
    return {
        __sceneryWireFrame: true,
        status,
        error: (flags & 1) !== 0,
        payloadJSON,
    }
}

function hasSceneryWireMagic(data: Uint8Array, magic: Uint8Array): boolean {
    if (data.length < magic.length) {
        return false
    }
    for (let i = 0; i < magic.length; i++) {
        if (data[i] !== magic[i]) {
            return false
        }
    }
    return true
}

function writeSceneryWireValue(writer: SceneryWireWriter, value: unknown): void {
    if (value === undefined || value === null) {
        writer.byte(0)
        return
    }
    if (typeof value === "boolean") {
        writer.byte(value ? 2 : 1)
        return
    }
    if (typeof value === "number") {
        if (!Number.isFinite(value)) {
            throw new Error("non-finite numbers cannot be encoded")
        }
        writer.byte(3)
        writer.float64(value)
        return
    }
    if (typeof value === "string") {
        writer.byte(4)
        writer.string(value)
        return
    }
    if (Array.isArray(value)) {
        writer.byte(5)
        writer.uvarint(value.length)
        for (const item of value) {
            writeSceneryWireValue(writer, item)
        }
        return
    }
    if (value instanceof Date) {
        writer.byte(4)
        writer.string(value.toISOString())
        return
    }
    if (typeof value === "object") {
        const record = value as Record<string, unknown>
        const keys = Object.keys(record).filter((key) => record[key] !== undefined)
        writer.byte(6)
        writer.uvarint(keys.length)
        for (const key of keys) {
            writer.string(key)
            writeSceneryWireValue(writer, record[key])
        }
        return
    }
    throw new Error(` + "`unsupported wire value: ${typeof value}`" + `)
}

class SceneryWireWriter {
    private data: Uint8Array
    private view: DataView
    private offset = 0

    constructor(size = 1024) {
        this.data = new Uint8Array(size)
        this.view = new DataView(this.data.buffer)
    }

    byte(value: number): void {
        this.reserve(1)
        this.data[this.offset++] = value & 0xff
    }

    bytes(value: Uint8Array): void {
        this.reserve(value.length)
        this.data.set(value, this.offset)
        this.offset += value.length
    }

    string(value: string): void {
        this.sizedBytes(encodeSceneryWireString(value))
    }

    sizedBytes(value: Uint8Array): void {
        this.uvarint(value.length)
        this.bytes(value)
    }

    uvarint(value: number): void {
        let v = Math.trunc(value)
        while (v >= 0x80) {
            this.byte((v & 0x7f) | 0x80)
            v = Math.floor(v / 128)
        }
        this.byte(v)
    }

    float64(value: number): void {
        this.reserve(8)
        this.view.setFloat64(this.offset, value, true)
        this.offset += 8
    }

    finish(): Uint8Array {
        return this.data.subarray(0, this.offset)
    }

    private reserve(extra: number): void {
        const required = this.offset + extra
        if (required <= this.data.length) {
            return
        }
        let nextSize = this.data.length
        while (nextSize < required) {
            nextSize *= 2
        }
        const next = new Uint8Array(nextSize)
        next.set(this.data)
        this.data = next
        this.view = new DataView(this.data.buffer)
    }
}

function encodeSceneryWireString(value: string): Uint8Array {
    if (value.length <= 8192) {
        const cached = sceneryWireStringCache.get(value)
        if (cached !== undefined) {
            return cached
        }
        const encoded = sceneryWireTextEncoder.encode(value)
        if (sceneryWireStringCache.size < 1024) {
            sceneryWireStringCache.set(value, encoded)
        }
        return encoded
    }
    return sceneryWireTextEncoder.encode(value)
}

class SceneryWireReader {
    private offset = 0
    private readonly view: DataView

    constructor(private readonly data: Uint8Array) {
        this.view = new DataView(data.buffer, data.byteOffset, data.byteLength)
    }

    done(): boolean {
        return this.offset === this.data.length
    }

    value(): unknown {
        const tag = this.byte()
        switch (tag) {
            case 0:
                return null
            case 1:
                return false
            case 2:
                return true
            case 3:
                return this.float64()
            case 4:
                return this.string()
            case 5: {
                const count = this.uvarint()
                const items: unknown[] = []
                for (let i = 0; i < count; i++) {
                    items.push(this.value())
                }
                return items
            }
            case 6: {
                const count = this.uvarint()
                const obj: Record<string, unknown> = {}
                for (let i = 0; i < count; i++) {
                    const key = this.string()
                    obj[key] = this.value()
                }
                return obj
            }
            default:
                throw new Error(` + "`unknown wire tag ${tag}`" + `)
        }
    }

    byte(): number {
        if (this.offset >= this.data.length) {
            throw new Error("truncated wire payload")
        }
        return this.data[this.offset++]
    }

    uvarint(): number {
        let value = 0
        let shift = 0
        for (;;) {
            const b = this.byte()
            value += (b & 0x7f) * Math.pow(2, shift)
            if ((b & 0x80) === 0) {
                return value
            }
            shift += 7
            if (shift > 63) {
                throw new Error("invalid wire length")
            }
        }
    }

    sizedBytes(): Uint8Array {
        const length = this.uvarint()
        if (this.offset + length > this.data.length) {
            throw new Error("truncated wire bytes")
        }
        const out = this.data.subarray(this.offset, this.offset + length)
        this.offset += length
        return out
    }

    string(): string {
        return sceneryWireTextDecoder.decode(this.sizedBytes())
    }

    float64(): number {
        if (this.offset + 8 > this.data.length) {
            throw new Error("truncated wire number")
        }
        const value = this.view.getFloat64(this.offset, true)
        this.offset += 8
        return value
    }
}

`)
	buf.WriteString("interface APIErrorResponse {\n")
	buf.WriteString("    code: ErrCode\n")
	buf.WriteString("    message: string\n")
	buf.WriteString("    details?: any\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function isAPIErrorResponse(err: any): err is APIErrorResponse {\n")
	buf.WriteString("    return (\n")
	buf.WriteString("        err !== undefined && err !== null &&\n")
	buf.WriteString("        isErrCode(err.code) &&\n")
	buf.WriteString("        typeof err.message === \"string\" &&\n")
	buf.WriteString("        (err.details === undefined || err.details === null || typeof err.details === \"object\")\n")
	buf.WriteString("    )\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function isErrCode(code: any): code is ErrCode {\n")
	buf.WriteString("    return code !== undefined && Object.values(ErrCode).includes(code)\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export class APIError extends Error {\n")
	buf.WriteString("    public readonly status: number\n")
	buf.WriteString("    public readonly code: ErrCode\n")
	buf.WriteString("    public readonly details?: any\n\n")
	buf.WriteString("    constructor(status: number, response: APIErrorResponse) {\n")
	buf.WriteString("        super(response.message)\n")
	buf.WriteString("        Object.defineProperty(this, \"name\", {\n")
	buf.WriteString("            value: \"APIError\",\n")
	buf.WriteString("            enumerable: false,\n")
	buf.WriteString("            configurable: true,\n")
	buf.WriteString("        })\n")
	buf.WriteString("        if ((Object as any).setPrototypeOf === undefined) {\n")
	buf.WriteString("            ;(this as any).__proto__ = APIError.prototype\n")
	buf.WriteString("        } else {\n")
	buf.WriteString("            Object.setPrototypeOf(this, APIError.prototype)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if ((Error as any).captureStackTrace !== undefined) {\n")
	buf.WriteString("            ;(Error as any).captureStackTrace(this, this.constructor)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        this.status = status\n")
	buf.WriteString("        this.code = response.code\n")
	buf.WriteString("        this.details = response.details\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export function isAPIError(err: any): err is APIError {\n")
	buf.WriteString("    return err instanceof APIError\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export enum ErrCode {\n")
	for _, item := range []struct {
		Name  string
		Value string
	}{
		{"OK", "ok"},
		{"Canceled", "canceled"},
		{"Unknown", "unknown"},
		{"InvalidArgument", "invalid_argument"},
		{"DeadlineExceeded", "deadline_exceeded"},
		{"NotFound", "not_found"},
		{"AlreadyExists", "already_exists"},
		{"PermissionDenied", "permission_denied"},
		{"ResourceExhausted", "resource_exhausted"},
		{"FailedPrecondition", "failed_precondition"},
		{"Aborted", "aborted"},
		{"OutOfRange", "out_of_range"},
		{"Unimplemented", "unimplemented"},
		{"Internal", "internal"},
		{"Unavailable", "unavailable"},
		{"DataLoss", "data_loss"},
		{"Unauthenticated", "unauthenticated"},
		{"Conflict", "conflict"},
	} {
		buf.WriteString(fmt.Sprintf("    %s = %q,\n", item.Name, item.Value))
	}
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

func writeStorageClient(buf *bytes.Buffer) {
	buf.WriteString(`export interface StorageObject {
    store: string
    key: string
    size_bytes: number
    content_type?: string
    etag?: string
    sha256?: string
    modified_at: string
    metadata?: Record<string, string>
}

export interface StorageListPage {
    objects: StorageObject[]
    prefixes?: string[]
    next_cursor?: string
}

export interface StorageListOptions {
    prefix?: string
    delimiter?: string
    cursor?: string
    limit?: number
}

export interface StoragePutOptions {
    contentType?: string
    ifNoneMatch?: boolean
}

export interface StorageGetOptions {
    range?: string
}

export class StorageClient {
    private readonly baseClient: BaseClient

    constructor(baseClient: BaseClient) {
        this.baseClient = baseClient
        this.store = this.store.bind(this)
        this.list = this.list.bind(this)
        this.put = this.put.bind(this)
        this.get = this.get.bind(this)
        this.getText = this.getText.bind(this)
        this.getBlob = this.getBlob.bind(this)
        this.head = this.head.bind(this)
        this.delete = this.delete.bind(this)
        this.deletePrefix = this.deletePrefix.bind(this)
    }

    public store(name = "app"): StorageStoreClient {
        return new StorageStoreClient(this.baseClient, name)
    }

    public async list(store: string, options?: StorageListOptions, params?: CallParameters): Promise<StorageListPage> {
        return await this.store(store).list(options, params)
    }

    public async put(store: string, key: string, body: BodyInit, options?: StoragePutOptions, params?: CallParameters): Promise<StorageObject> {
        return await this.store(store).put(key, body, options, params)
    }

    public async get(store: string, key: string, options?: StorageGetOptions, params?: CallParameters): Promise<Response> {
        return await this.store(store).get(key, options, params)
    }

    public async getText(store: string, key: string, options?: StorageGetOptions, params?: CallParameters): Promise<string> {
        return await this.store(store).getText(key, options, params)
    }

    public async getBlob(store: string, key: string, options?: StorageGetOptions, params?: CallParameters): Promise<Blob> {
        return await this.store(store).getBlob(key, options, params)
    }

    public async head(store: string, key: string, params?: CallParameters): Promise<Response> {
        return await this.store(store).head(key, params)
    }

    public async delete(store: string, key: string, params?: CallParameters): Promise<void> {
        await this.store(store).delete(key, params)
    }

    public async deletePrefix(store: string, prefix: string, params?: CallParameters): Promise<void> {
        await this.store(store).deletePrefix(prefix, params)
    }
}

export class StorageStoreClient {
    private readonly baseClient: BaseClient
    public readonly name: string

    constructor(baseClient: BaseClient, name = "app") {
        this.baseClient = baseClient
        this.name = name
        this.list = this.list.bind(this)
        this.put = this.put.bind(this)
        this.get = this.get.bind(this)
        this.getText = this.getText.bind(this)
        this.getBlob = this.getBlob.bind(this)
        this.head = this.head.bind(this)
        this.delete = this.delete.bind(this)
        this.deletePrefix = this.deletePrefix.bind(this)
    }

    public async list(options?: StorageListOptions, params?: CallParameters): Promise<StorageListPage> {
        const query = makeRecord<string, string>({
            prefix: options?.prefix,
            delimiter: options?.delimiter,
            cursor: options?.cursor,
            limit: options?.limit === undefined ? undefined : String(options.limit),
        })
        const response = await this.baseClient.callAPI("GET", this.storePath(), undefined, mergeCallParameters(params, { query }))
        return await response.json() as StorageListPage
    }

    public async put(key: string, body: BodyInit, options?: StoragePutOptions, params?: CallParameters): Promise<StorageObject> {
        const headers = makeRecord<string, string>({
            "Content-Type": options?.contentType,
            "If-None-Match": options?.ifNoneMatch ? "*" : undefined,
        })
        const response = await this.baseClient.callAPI("PUT", this.objectPath(key), body, mergeCallParameters(params, { headers }))
        return await response.json() as StorageObject
    }

    public async get(key: string, options?: StorageGetOptions, params?: CallParameters): Promise<Response> {
        const headers = makeRecord<string, string>({
            Range: options?.range,
        })
        return await this.baseClient.callAPI("GET", this.objectPath(key), undefined, mergeCallParameters(params, { headers }))
    }

    public async getText(key: string, options?: StorageGetOptions, params?: CallParameters): Promise<string> {
        return await (await this.get(key, options, params)).text()
    }

    public async getBlob(key: string, options?: StorageGetOptions, params?: CallParameters): Promise<Blob> {
        return await (await this.get(key, options, params)).blob()
    }

    public async head(key: string, params?: CallParameters): Promise<Response> {
        return await this.baseClient.callAPI("HEAD", this.objectPath(key), undefined, params)
    }

    public async delete(key: string, params?: CallParameters): Promise<void> {
        await this.baseClient.callAPI("DELETE", this.objectPath(key), undefined, params)
    }

    public async deletePrefix(prefix: string, params?: CallParameters): Promise<void> {
        await this.baseClient.callAPI("DELETE", this.objectPath(prefix), undefined, mergeCallParameters(params, { query: { recursive: "true" } }))
    }

    private storePath(): string {
        return "/__scenery/storage/" + encodeURIComponent(this.name)
    }

    private objectPath(key: string): string {
        return this.storePath() + "/" + encodePathWildcard(key)
    }
}

`)
}
