package clientgen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

func (g *tsGenerator) render() ([]byte, error) {
	slug := strings.TrimSpace(g.opts.AppSlug)
	if slug == "" {
		slug = strings.TrimSpace(g.app.Name)
	}
	if slug == "" {
		slug = "scenery"
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by scenery. DO NOT EDIT.\n\n")
	buf.WriteString("/* eslint-disable */\n")
	buf.WriteString("/* jshint ignore:start */\n")
	buf.WriteString("/* jslint-disable */\n\n")
	buf.WriteString("export type BaseURL = string\n\n")
	buf.WriteString(`export const Local: BaseURL = "http://localhost:4000"` + "\n\n")
	buf.WriteString("export function Environment(name: string): BaseURL {\n")
	buf.WriteString(fmt.Sprintf("    return `https://${name}-%s.encr.app`\n", slug))
	buf.WriteString("}\n\n")
	buf.WriteString("export function PreviewEnv(pr: number | string): BaseURL {\n")
	buf.WriteString("    return Environment(`pr${pr}`)\n")
	buf.WriteString("}\n\n")
	buf.WriteString(`const BROWSER = typeof globalThis === "object" && ("window" in globalThis)` + "\n\n")
	serviceNames := make([]string, 0, len(g.namespaces))
	serviceNames = append(serviceNames, namespaceNamesWithMethods(g.namespaces)...)
	if g.opts.StandardAuth {
		serviceNames = appendMissing(serviceNames, "auth", "users")
	}
	sort.Strings(serviceNames)

	buf.WriteString("export default class Client {\n")
	buf.WriteString("    public readonly storage: StorageClient\n")
	for _, svcName := range serviceNames {
		buf.WriteString(fmt.Sprintf("    public readonly %s: %s.ServiceClient\n", svcName, svcName))
	}
	buf.WriteString("    private readonly options: ClientOptions\n")
	buf.WriteString("    private readonly target: string\n\n")
	buf.WriteString("    constructor(target: string, token?: string)\n")
	buf.WriteString("    constructor(target: BaseURL, options?: ClientOptions)\n")
	buf.WriteString(`    constructor(target: string | BaseURL = "prod", options?: string | ClientOptions) {` + "\n")
	buf.WriteString(`        if (!target.startsWith("http://") && !target.startsWith("https://")) {` + "\n")
	buf.WriteString("            target = Environment(target)\n")
	buf.WriteString("        }\n\n")
	buf.WriteString(`        if (typeof options === "string") {` + "\n")
	buf.WriteString("            options = { auth: options }\n")
	buf.WriteString("        }\n\n")
	buf.WriteString("        this.target = target\n")
	buf.WriteString("        this.options = options ?? {}\n")
	buf.WriteString("        const base = new BaseClient(this.target, this.options)\n")
	buf.WriteString("        this.storage = new StorageClient(base)\n")
	for _, svcName := range serviceNames {
		buf.WriteString(fmt.Sprintf("        this.%s = new %s.ServiceClient(base)\n", svcName, svcName))
	}
	buf.WriteString("    }\n\n")
	buf.WriteString("    public with(options: ClientOptions): Client {\n")
	buf.WriteString("        return new Client(this.target, {\n")
	buf.WriteString("            ...this.options,\n")
	buf.WriteString("            ...options,\n")
	buf.WriteString("        })\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	buf.WriteString("export interface ClientOptions {\n")
	buf.WriteString("    fetcher?: Fetcher\n")
	buf.WriteString(`    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }` + "\n")
	buf.WriteString("    auth?: string | AuthDataGenerator\n")
	buf.WriteString("}\n\n")

	namespaceNames := make([]string, 0, len(g.namespaces))
	for name := range g.namespaces {
		namespaceNames = append(namespaceNames, name)
	}
	sort.Strings(namespaceNames)
	for _, name := range namespaceNames {
		if !tsIdentifier.MatchString(name) {
			continue
		}
		ns := g.namespaces[name]
		if len(ns.methods) == 0 && len(ns.typeOrder) == 0 {
			continue
		}
		buf.WriteString(fmt.Sprintf("export namespace %s {\n", ns.Name))
		for _, typeName := range ns.typeOrder {
			def := ns.types[typeName]
			if def == "" {
				continue
			}
			buf.WriteString(indentBlock(def, 1))
			buf.WriteString("\n\n")
		}
		if len(ns.methods) > 0 {
			buf.WriteString("    export class ServiceClient {\n")
			buf.WriteString("        private baseClient: BaseClient\n\n")
			buf.WriteString("        constructor(baseClient: BaseClient) {\n")
			buf.WriteString("            this.baseClient = baseClient\n")
			for _, method := range ns.methods {
				for _, name := range methodNamesFromRendered(method) {
					buf.WriteString(fmt.Sprintf("            this.%s = this.%s.bind(this)\n", name, name))
				}
			}
			buf.WriteString("        }\n\n")
			for i, method := range ns.methods {
				buf.WriteString(indentBlock(method, 2))
				if i != len(ns.methods)-1 {
					buf.WriteString("\n\n")
				}
			}
			buf.WriteString("\n    }\n")
		}
		buf.WriteString("}\n\n")
	}
	if g.opts.StandardAuth {
		writeStandardAuthNamespaces(&buf, g.opts.StandardAuthGoogle)
	}

	writeStorageClient(&buf)

	buf.WriteString("export type JSONValue = string | number | boolean | null | JSONValue[] | {[key: string]: JSONValue}\n\n")
	buf.WriteString("function encodeQuery(parts: Record<string, string | string[]>): string {\n")
	buf.WriteString("    const pairs: string[] = []\n")
	buf.WriteString("    for (const key in parts) {\n")
	buf.WriteString("        const val = (Array.isArray(parts[key]) ? parts[key] : [parts[key]]) as string[]\n")
	buf.WriteString("        for (const v of val) {\n")
	buf.WriteString("            pairs.push(`${key}=${encodeURIComponent(v)}`)\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return pairs.join(\"&\")\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// @ts-ignore - TS ignore because makeRecord is not always used\n")
	buf.WriteString("function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {\n")
	buf.WriteString("    for (const key in record) {\n")
	buf.WriteString("        if (record[key] === undefined) {\n")
	buf.WriteString("            delete record[key]\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return record as Record<K, V>\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodePathWildcard(value: string): string {\n")
	buf.WriteString("    return value.split(\"/\").map((part) => encodeURIComponent(part)).join(\"/\")\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodeQueryValue(value: unknown): string | string[] | undefined {\n")
	buf.WriteString("    if (value === undefined || value === null) {\n")
	buf.WriteString("        return undefined\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (Array.isArray(value)) {\n")
	buf.WriteString("        return value.map((item) => String(item))\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (typeof value === \"object\") {\n")
	buf.WriteString("        return JSON.stringify(value)\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return String(value)\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodeHeaderValue(value: unknown): string | undefined {\n")
	buf.WriteString("    if (value === undefined || value === null) {\n")
	buf.WriteString("        return undefined\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (Array.isArray(value)) {\n")
	buf.WriteString("        return value.map((item) => String(item)).join(\",\")\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (typeof value === \"object\") {\n")
	buf.WriteString("        return JSON.stringify(value)\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return String(value)\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodeCookieHeader(values: Record<string, string>): string | undefined {\n")
	buf.WriteString("    const pairs: string[] = []\n")
	buf.WriteString("    for (const key in values) {\n")
	buf.WriteString("        pairs.push(`${encodeURIComponent(key)}=${encodeURIComponent(values[key])}`)\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (pairs.length === 0) {\n")
	buf.WriteString("        return undefined\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return pairs.join(\"; \")\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// Keep helper symbols referenced for strict TS noUnusedLocals.\n")
	buf.WriteString("void makeRecord\n")
	buf.WriteString("void encodePathWildcard\n")
	buf.WriteString("void encodeQueryValue\n")
	buf.WriteString("void encodeHeaderValue\n")
	buf.WriteString("void encodeCookieHeader\n\n")
	buf.WriteString(`export type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {` + "\n")
	buf.WriteString("    headers?: Record<string, string>\n")
	buf.WriteString("    query?: Record<string, string | string[]>\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export interface APIResponse<T> {\n")
	buf.WriteString("    data: T\n")
	buf.WriteString("    headers: Headers\n")
	buf.WriteString("    status: number\n")
	buf.WriteString("    response: Response\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export type AuthDataGenerator = () =>\n")
	buf.WriteString("  | string\n")
	buf.WriteString("  | Promise<string | undefined>\n")
	buf.WriteString("  | undefined\n\n")
	buf.WriteString("export type Fetcher = typeof fetch\n\n")
	buf.WriteString("const boundFetch = fetch.bind(globalThis)\n\n")
	buf.WriteString("class BaseClient {\n")
	buf.WriteString("    readonly baseURL: string\n")
	buf.WriteString("    readonly fetcher: Fetcher\n")
	buf.WriteString("    readonly headers: Record<string, string>\n")
	buf.WriteString(`    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }` + "\n")
	buf.WriteString("    readonly authGenerator?: AuthDataGenerator\n\n")
	buf.WriteString("    constructor(baseURL: string, options: ClientOptions) {\n")
	buf.WriteString("        this.baseURL = baseURL\n")
	buf.WriteString("        this.headers = {}\n")
	buf.WriteString("        if (!BROWSER) {\n")
	buf.WriteString(fmt.Sprintf("            this.headers[\"User-Agent\"] = %q\n", slug+"-Generated-TS-Client (scenery)"))
	buf.WriteString("        }\n")
	buf.WriteString("        this.requestInit = options.requestInit ?? {}\n")
	buf.WriteString("        this.fetcher = options.fetcher ?? boundFetch\n")
	buf.WriteString("        if (options.auth !== undefined) {\n")
	buf.WriteString("            const auth = options.auth\n")
	buf.WriteString("            if (typeof auth === \"function\") {\n")
	buf.WriteString("                this.authGenerator = auth\n")
	buf.WriteString("            } else {\n")
	buf.WriteString("                this.authGenerator = () => auth\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    async getAuthData(): Promise<CallParameters | undefined> {\n")
	buf.WriteString("        let authData: string | undefined\n")
	buf.WriteString("        if (this.authGenerator) {\n")
	buf.WriteString("            const maybePromise = this.authGenerator()\n")
	buf.WriteString("            if (maybePromise instanceof Promise) {\n")
	buf.WriteString("                authData = await maybePromise\n")
	buf.WriteString("            } else {\n")
	buf.WriteString("                authData = maybePromise\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if (!authData) {\n")
	buf.WriteString("            return undefined\n")
	buf.WriteString("        }\n")
	buf.WriteString("        return { headers: { Authorization: \"Bearer \" + authData } }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callTypedEndpoint(spec: TypedEndpointCall): Promise<Response | unknown> {\n")
	buf.WriteString("        return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callTypedEndpointWithMeta(spec: TypedEndpointCall): Promise<TypedEndpointResultWithMeta> {\n")
	buf.WriteString("        return this.callTypedAPIWithMeta(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callTypedAPI(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<Response> {\n")
	buf.WriteString("        return this.callAPI(method, path, body, {\n")
	buf.WriteString("            ...params,\n")
	buf.WriteString("            headers: { \"Content-Type\": \"application/json\", ...params?.headers },\n")
	buf.WriteString("        })\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callTypedAPIWithMeta(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<TypedEndpointResultWithMeta> {\n")
	buf.WriteString("        const response = await this.callTypedAPI(method, path, body, params)\n")
	buf.WriteString("        return {\n")
	buf.WriteString("            body: response,\n")
	buf.WriteString("            headers: response.headers,\n")
	buf.WriteString("            status: response.status,\n")
	buf.WriteString("            response,\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callAPI(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<Response> {\n")
	buf.WriteString("        const response = await this.fetchAPI(method, path, body, params)\n")
	buf.WriteString("        if (!response.ok) {\n")
	buf.WriteString("            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }\n")
	buf.WriteString("            try {\n")
	buf.WriteString("                const text = await response.text()\n")
	buf.WriteString("                try {\n")
	buf.WriteString("                    const jsonBody = JSON.parse(text)\n")
	buf.WriteString("                    if (isAPIErrorResponse(jsonBody)) {\n")
	buf.WriteString("                        body = jsonBody\n")
	buf.WriteString("                    } else {\n")
	buf.WriteString("                        body.message += \": \" + JSON.stringify(jsonBody)\n")
	buf.WriteString("                    }\n")
	buf.WriteString("                } catch {\n")
	buf.WriteString("                    body.message += \": \" + text\n")
	buf.WriteString("                }\n")
	buf.WriteString("            } catch (err) {\n")
	buf.WriteString("                body.message += \": \" + String(err)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw new APIError(response.status, body)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        return response\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async fetchAPI(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<Response> {\n")
	buf.WriteString("        let { query, headers, ...rest } = params ?? {}\n")
	buf.WriteString("        const init = {\n")
	buf.WriteString("            ...this.requestInit,\n")
	buf.WriteString("            ...rest,\n")
	buf.WriteString("            method,\n")
	buf.WriteString("            body: body ?? null,\n")
	buf.WriteString("        }\n")
	buf.WriteString("        init.headers = { ...this.headers, ...init.headers, ...headers }\n")
	buf.WriteString("        const authData = await this.getAuthData()\n")
	buf.WriteString("        if (authData) {\n")
	buf.WriteString("            if (authData.query) {\n")
	buf.WriteString("                query = { ...query, ...authData.query }\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (authData.headers) {\n")
	buf.WriteString("                init.headers = { ...init.headers, ...authData.headers }\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("        const queryString = query ? \"?\" + encodeQuery(query) : \"\"\n")
	buf.WriteString("        return await this.fetcher(this.baseURL + path + queryString, init)\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")
	buf.WriteString(`interface TypedEndpointCall {
    method: string
    path: string
    payload?: unknown
    jsonBody?: RequestInit["body"]
    params?: CallParameters
}

interface TypedEndpointResultWithMeta {
    body: unknown
    headers: Headers
    status: number
    response: Response
}

async function decodeTypedResponse(value: Response | unknown): Promise<unknown> {
    if (value instanceof Response) {
        return await value.json()
    }
    return value
}

async function decodeTypedAPIResponse(value: TypedEndpointResultWithMeta): Promise<APIResponse<unknown>> {
    return {
        data: await decodeTypedResponse(value.body),
        headers: value.headers,
        status: value.status,
        response: value.response,
    }
}

function typedVoidAPIResponse(value: TypedEndpointResultWithMeta): APIResponse<void> {
    return {
        data: undefined,
        headers: value.headers,
        status: value.status,
        response: value.response,
    }
}

function mergeCallParameters(base?: CallParameters, generated?: CallParameters): CallParameters | undefined {
    if (!base) {
        return generated
    }
    if (!generated) {
        return base
    }
    const query = base.query || generated.query ? { ...base.query, ...generated.query } : undefined
    const headers = base.headers || generated.headers ? { ...base.headers, ...generated.headers } : undefined
    return {
        ...base,
        ...generated,
        query,
        headers,
    }
}

void decodeTypedAPIResponse
void typedVoidAPIResponse
void mergeCallParameters

`)
	buf.WriteString("interface APIErrorResponse {\n")
	buf.WriteString("    code: ErrCode\n")
	buf.WriteString("    message: string\n")
	buf.WriteString("    details?: any\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function isAPIErrorResponse(err: any): err is APIErrorResponse {\n")
	buf.WriteString("    return (\n")
	buf.WriteString("        err !== undefined && err !== null &&\n")
	buf.WriteString("        isErrCode(err.code) &&\n")
	buf.WriteString("        typeof err.message === \"string\" &&\n")
	buf.WriteString("        (err.details === undefined || err.details === null || typeof err.details === \"object\")\n")
	buf.WriteString("    )\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function isErrCode(code: any): code is ErrCode {\n")
	buf.WriteString("    return code !== undefined && Object.values(ErrCode).includes(code)\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export class APIError extends Error {\n")
	buf.WriteString("    public readonly status: number\n")
	buf.WriteString("    public readonly code: ErrCode\n")
	buf.WriteString("    public readonly details?: any\n\n")
	buf.WriteString("    constructor(status: number, response: APIErrorResponse) {\n")
	buf.WriteString("        super(response.message)\n")
	buf.WriteString("        Object.defineProperty(this, \"name\", {\n")
	buf.WriteString("            value: \"APIError\",\n")
	buf.WriteString("            enumerable: false,\n")
	buf.WriteString("            configurable: true,\n")
	buf.WriteString("        })\n")
	buf.WriteString("        if ((Object as any).setPrototypeOf === undefined) {\n")
	buf.WriteString("            ;(this as any).__proto__ = APIError.prototype\n")
	buf.WriteString("        } else {\n")
	buf.WriteString("            Object.setPrototypeOf(this, APIError.prototype)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if ((Error as any).captureStackTrace !== undefined) {\n")
	buf.WriteString("            ;(Error as any).captureStackTrace(this, this.constructor)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        this.status = status\n")
	buf.WriteString("        this.code = response.code\n")
	buf.WriteString("        this.details = response.details\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export function isAPIError(err: any): err is APIError {\n")
	buf.WriteString("    return err instanceof APIError\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export enum ErrCode {\n")
	for _, item := range []struct {
		Name  string
		Value string
	}{
		{"OK", "ok"},
		{"Canceled", "canceled"},
		{"Unknown", "unknown"},
		{"InvalidArgument", "invalid_argument"},
		{"DeadlineExceeded", "deadline_exceeded"},
		{"NotFound", "not_found"},
		{"AlreadyExists", "already_exists"},
		{"PermissionDenied", "permission_denied"},
		{"ResourceExhausted", "resource_exhausted"},
		{"FailedPrecondition", "failed_precondition"},
		{"Aborted", "aborted"},
		{"OutOfRange", "out_of_range"},
		{"Unimplemented", "unimplemented"},
		{"Internal", "internal"},
		{"Unavailable", "unavailable"},
		{"DataLoss", "data_loss"},
		{"Unauthenticated", "unauthenticated"},
		{"Conflict", "conflict"},
		{"GoogleReauthRequired", "google_reauth_required"},
		{"GoogleScopeMissing", "google_scope_missing"},
	} {
		buf.WriteString(fmt.Sprintf("    %s = %q,\n", item.Name, item.Value))
	}
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

func writeStorageClient(buf *bytes.Buffer) {
	buf.WriteString(`export interface StorageObject {
    store: string
    key: string
    size_bytes: number
    content_type?: string
    etag?: string
    sha256?: string
    modified_at: string
    metadata?: Record<string, string>
}

export interface StorageListPage {
    objects: StorageObject[]
    prefixes?: string[]
    next_cursor?: string
}

export interface StorageListOptions {
    prefix?: string
    delimiter?: string
    cursor?: string
    limit?: number
}

export interface StoragePutOptions {
    contentType?: string
    ifNoneMatch?: boolean
}

export interface StorageGetOptions {
    range?: string
}

export class StorageClient {
    private readonly baseClient: BaseClient

    constructor(baseClient: BaseClient) {
        this.baseClient = baseClient
        this.store = this.store.bind(this)
        this.list = this.list.bind(this)
        this.put = this.put.bind(this)
        this.get = this.get.bind(this)
        this.getText = this.getText.bind(this)
        this.getBlob = this.getBlob.bind(this)
        this.head = this.head.bind(this)
        this.delete = this.delete.bind(this)
        this.deletePrefix = this.deletePrefix.bind(this)
    }

    public store(name = "app"): StorageStoreClient {
        return new StorageStoreClient(this.baseClient, name)
    }

    public async list(store: string, options?: StorageListOptions, params?: CallParameters): Promise<StorageListPage> {
        return await this.store(store).list(options, params)
    }

    public async put(store: string, key: string, body: BodyInit, options?: StoragePutOptions, params?: CallParameters): Promise<StorageObject> {
        return await this.store(store).put(key, body, options, params)
    }

    public async get(store: string, key: string, options?: StorageGetOptions, params?: CallParameters): Promise<Response> {
        return await this.store(store).get(key, options, params)
    }

    public async getText(store: string, key: string, options?: StorageGetOptions, params?: CallParameters): Promise<string> {
        return await this.store(store).getText(key, options, params)
    }

    public async getBlob(store: string, key: string, options?: StorageGetOptions, params?: CallParameters): Promise<Blob> {
        return await this.store(store).getBlob(key, options, params)
    }

    public async head(store: string, key: string, params?: CallParameters): Promise<Response> {
        return await this.store(store).head(key, params)
    }

    public async delete(store: string, key: string, params?: CallParameters): Promise<void> {
        await this.store(store).delete(key, params)
    }

    public async deletePrefix(store: string, prefix: string, params?: CallParameters): Promise<void> {
        await this.store(store).deletePrefix(prefix, params)
    }
}

export class StorageStoreClient {
    private readonly baseClient: BaseClient
    public readonly name: string

    constructor(baseClient: BaseClient, name = "app") {
        this.baseClient = baseClient
        this.name = name
        this.list = this.list.bind(this)
        this.put = this.put.bind(this)
        this.get = this.get.bind(this)
        this.getText = this.getText.bind(this)
        this.getBlob = this.getBlob.bind(this)
        this.head = this.head.bind(this)
        this.delete = this.delete.bind(this)
        this.deletePrefix = this.deletePrefix.bind(this)
    }

    public async list(options?: StorageListOptions, params?: CallParameters): Promise<StorageListPage> {
        const query = makeRecord<string, string>({
            prefix: options?.prefix,
            delimiter: options?.delimiter,
            cursor: options?.cursor,
            limit: options?.limit === undefined ? undefined : String(options.limit),
        })
        const response = await this.baseClient.callAPI("GET", this.storePath(), undefined, mergeCallParameters(params, { query }))
        return await response.json() as StorageListPage
    }

    public async put(key: string, body: BodyInit, options?: StoragePutOptions, params?: CallParameters): Promise<StorageObject> {
        const headers = makeRecord<string, string>({
            "Content-Type": options?.contentType,
            "If-None-Match": options?.ifNoneMatch ? "*" : undefined,
        })
        const response = await this.baseClient.callAPI("PUT", this.objectPath(key), body, mergeCallParameters(params, { headers }))
        return await response.json() as StorageObject
    }

    public async get(key: string, options?: StorageGetOptions, params?: CallParameters): Promise<Response> {
        const headers = makeRecord<string, string>({
            Range: options?.range,
        })
        return await this.baseClient.callAPI("GET", this.objectPath(key), undefined, mergeCallParameters(params, { headers }))
    }

    public async getText(key: string, options?: StorageGetOptions, params?: CallParameters): Promise<string> {
        return await (await this.get(key, options, params)).text()
    }

    public async getBlob(key: string, options?: StorageGetOptions, params?: CallParameters): Promise<Blob> {
        return await (await this.get(key, options, params)).blob()
    }

    public async head(key: string, params?: CallParameters): Promise<Response> {
        return await this.baseClient.callAPI("HEAD", this.objectPath(key), undefined, params)
    }

    public async delete(key: string, params?: CallParameters): Promise<void> {
        await this.baseClient.callAPI("DELETE", this.objectPath(key), undefined, params)
    }

    public async deletePrefix(prefix: string, params?: CallParameters): Promise<void> {
        await this.baseClient.callAPI("DELETE", this.objectPath(prefix), undefined, mergeCallParameters(params, { query: { recursive: "true" } }))
    }

    private storePath(): string {
        return "/__scenery/storage/" + encodeURIComponent(this.name)
    }

    private objectPath(key: string): string {
        return this.storePath() + "/" + encodePathWildcard(key)
    }
}

`)
}
