// Code generated by Scenery. DO NOT EDIT.
package househouseadapter

import (
	"context"
	implementation "example.test/nativeapp/house"
	contract "example.test/nativeapp/house/scenerycontract"
	"fmt"
	"net/http"
	scenery "scenery.sh"
	sceneryruntime "scenery.sh/runtime"
)

const ContractRevision = "sha256:1fd62db00ac84b74cc80b7a04e0bae8975bd97e79d44662b85a110169b0347de"
const PackageIdentity = "house"
const PackageContractABIRevision = "sha256:76f2aa33a3093803149d651d1ef3c49b46eb9abbba6adf798b4d4b13815f5b10"

type serviceImplementation interface {
	ProcessScene(context.Context, contract.ProcessSceneInput) (contract.ProcessSceneOutcome, error)
}

type serviceAdapter struct{ native serviceImplementation }

var service *serviceAdapter

func (adapter *serviceAdapter) ProcessScene(ctx context.Context, input contract.ProcessSceneInput) (contract.ProcessSceneOutcome, error) {
	if adapter == nil || adapter.native == nil {
		return nil, fmt.Errorf("service is not initialized")
	}
	native := adapter.native
	return native.ProcessScene(ctx, input)
}

type selfInternalClient struct{}

func (selfInternalClient) Invoke(ctx context.Context, invocation scenery.Invocation, input contract.ProcessSceneInput) (contract.ProcessSceneOutcome, error) {
	copied, err := contract.CloneProcessSceneInput(input)
	if err != nil {
		return nil, fmt.Errorf("copy internal client input: %w", err)
	}
	value, err := sceneryruntime.InvokeContractBindingFrom(ctx, "house/binding/process_scene_internal", "house", invocation, copied)
	if err != nil {
		return nil, err
	}
	typed, ok := value.(contract.ProcessSceneOutcome)
	if !ok {
		return nil, fmt.Errorf("binding returned %T, want contract.ProcessSceneOutcome", value)
	}
	cloned, err := contract.CloneProcessSceneOutcome(typed)
	if err != nil {
		return nil, fmt.Errorf("copy internal client outcome: %w", err)
	}
	return cloned, nil
}

func renderProcessSceneCLIOutcome(outcome contract.ProcessSceneOutcome) (sceneryruntime.ContractCLIOutcome, error) {
	raw, err := contract.MarshalProcessSceneOutcome(outcome)
	if err != nil {
		return sceneryruntime.ContractCLIOutcome{}, sceneryruntime.ContractSystemError(err)
	}
	kind, name, payload, err := scenery.DecodeContractOutcomeEnvelope(raw)
	if err != nil {
		return sceneryruntime.ContractCLIOutcome{}, sceneryruntime.ContractSystemError(err)
	}
	return sceneryruntime.ContractCLIOutcome{Kind: kind, Name: name, Payload: payload}, nil
}

func Register(registry scenery.Registry) error {
	return registry.Register("house/service/house/adapter", sceneryruntime.ContractRegistration{
		ContractRevision: ContractRevision, PackageContractABIRevision: PackageContractABIRevision, RuntimeABI: sceneryruntime.ContractRuntimeABI,
		ProviderABIs: map[string]string{}, CoveredAddresses: []string{"house/binding/process_scene_http", "house/binding/process_scene_internal", "house/execution/process_scene_direct", "house/operation/process_scene", "house/service/house"},
		Apply: func() error {
			if contract.PackageIdentity != PackageIdentity {
				return fmt.Errorf("package identity mismatch")
			}
			if contract.PackageContractABIRevision != PackageContractABIRevision {
				return fmt.Errorf("package contract ABI mismatch")
			}
			if err := sceneryruntime.RegisterNativeService(sceneryruntime.NativeServiceRegistration{Address: "house/service/house", Initialize: func(ctx context.Context) error {
				input := contract.HouseConstructorInput{}
				input.Clients.Self = selfInternalClient{}
				value, err := implementation.NewService(ctx, input)
				if err != nil {
					return err
				}
				if value == nil {
					return fmt.Errorf("constructor returned nil service")
				}
				service = &serviceAdapter{native: value}
				return nil
			}}); err != nil {
				return err
			}
			if err := sceneryruntime.RegisterContractInternalBindingWithPolicy(sceneryruntime.ContractInternalBindingRegistration{Address: "house/binding/process_scene_internal", Visibility: "application", Package: "house", Policy: &sceneryruntime.ContractHTTPPolicy{BindingAddress: "house/binding/process_scene_internal", AuthorizationStrategy: "public", AuthorizationRuleCount: 0, AuthorizationRules: []sceneryruntime.ContractAuthorizationRule{}, PipelineSteps: []string{}}, DecodeInput: func(data []byte) (any, error) { return contract.UnmarshalProcessSceneInput(data) }, EncodeOutput: func(value any) ([]byte, error) {
				typed, ok := value.(contract.ProcessSceneOutcome)
				if !ok {
					return nil, fmt.Errorf("internal binding output has type %T", value)
				}
				return contract.MarshalProcessSceneOutcome(typed)
			}, Invoke: func(ctx context.Context, _ any, input any) (any, error) {
				if service == nil {
					return nil, sceneryruntime.ContractSystemError(fmt.Errorf("service is not initialized"))
				}
				typed, ok := input.(contract.ProcessSceneInput)
				if !ok {
					return nil, sceneryruntime.ContractSystemError(fmt.Errorf("internal binding input has type %T", input))
				}
				copied, err := contract.CloneProcessSceneInput(typed)
				if err != nil {
					return nil, sceneryruntime.ContractSystemError(err)
				}
				outcome, err := service.ProcessScene(ctx, copied)
				if err != nil {
					if outcome != nil {
						return nil, sceneryruntime.ContractSystemError(fmt.Errorf("handler returned outcome and error"))
					}
					return nil, sceneryruntime.ContractSystemError(err)
				}
				if outcome == nil {
					return nil, sceneryruntime.ContractSystemError(fmt.Errorf("handler returned nil outcome without error"))
				}
				cloned, err := contract.CloneProcessSceneOutcome(outcome)
				if err != nil {
					return nil, sceneryruntime.ContractSystemError(err)
				}
				if err := sceneryruntime.PublishContractOperationOutcome(ctx, "house/operation/process_scene", cloned); err != nil {
					return nil, sceneryruntime.ContractSystemError(err)
				}
				return cloned, nil
			}}); err != nil {
				return err
			}
			if err := sceneryruntime.RegisterContractCLIBinding(sceneryruntime.ContractCLIBindingRegistration{Address: "house/binding/process_scene_cli", Command: []string{"house", "process-scene"}, Policy: &sceneryruntime.ContractHTTPPolicy{BindingAddress: "house/binding/process_scene_cli", AuthorizationStrategy: "local_developer", AuthorizationRuleCount: 0, AuthorizationRules: []sceneryruntime.ContractAuthorizationRule{}, PipelineSteps: []string{}}, Invoke: func(ctx context.Context, input []byte) (sceneryruntime.ContractCLIOutcome, error) {
				typed, err := contract.UnmarshalProcessSceneInput(input)
				if err != nil {
					return sceneryruntime.ContractCLIOutcome{}, sceneryruntime.ContractCLIInvalidInput(err)
				}
				typed, err = contract.CloneProcessSceneInput(typed)
				if err != nil {
					return sceneryruntime.ContractCLIOutcome{}, sceneryruntime.ContractCLIInvalidInput(err)
				}
				value, err := sceneryruntime.InvokeContractPolicy(ctx, &sceneryruntime.ContractHTTPPolicy{BindingAddress: "house/binding/process_scene_cli", AuthorizationStrategy: "local_developer", AuthorizationRuleCount: 0, AuthorizationRules: []sceneryruntime.ContractAuthorizationRule{}, PipelineSteps: []string{}}, typed, func(callCtx context.Context) (any, error) {
					if service == nil {
						return nil, sceneryruntime.ContractSystemError(fmt.Errorf("service is not initialized"))
					}
					outcome, err := service.ProcessScene(callCtx, typed)
					if err != nil {
						if outcome != nil {
							return nil, sceneryruntime.ContractSystemError(fmt.Errorf("handler returned outcome and error"))
						}
						return nil, sceneryruntime.ContractSystemError(err)
					}
					if outcome == nil {
						return nil, sceneryruntime.ContractSystemError(fmt.Errorf("handler returned nil outcome"))
					}
					return outcome, nil
				})
				if err != nil {
					return sceneryruntime.ContractCLIOutcome{}, err
				}
				outcome, ok := value.(contract.ProcessSceneOutcome)
				if !ok {
					return sceneryruntime.ContractCLIOutcome{}, sceneryruntime.ContractSystemError(fmt.Errorf("CLI binding returned %T, want contract.ProcessSceneOutcome", value))
				}
				return renderProcessSceneCLIOutcome(outcome)
			}}); err != nil {
				return err
			}
			if err := sceneryruntime.RegisterEndpointChecked(&sceneryruntime.Endpoint{Service: "house", Name: "ProcessSceneHttp", Access: sceneryruntime.Public, Path: "/api/house/process", Methods: []string{"POST"},
				ContractPolicy: &sceneryruntime.ContractHTTPPolicy{BindingAddress: "house/binding/process_scene_http", GatewayAddress: "app/http_gateway/public_api", CORS: "none", AllowedOrigins: []string{}, Forwarded: "reject", TrustedProxyPrefixes: []string{}, MaxRequestHeaderBytes: 65536, MaxResponseBytes: 16777216, CompressionAlgorithms: []string{"gzip"}, CompressionThreshold: 1024, TotalInvocationTimeoutNanos: 2400000000000, ReadTimeoutNanos: 30000000000, WriteTimeoutNanos: 30000000000, IdleTimeoutNanos: 120000000000, AuthorizationStrategy: "public", AuthorizationRuleCount: 0, AuthorizationRules: []sceneryruntime.ContractAuthorizationRule{}, PipelineSteps: []string{}, FrameworkGuarantee: "framework_enforced", TransportStatuses: map[string]int{"admission.rate_limited": 429, "result.processed": 200, "system.internal": 500, "transport.invalid_request": 400, "transport.not_acceptable": 406, "transport.unsupported_media_type": 415}},
				DecodeContractRequest: func(request *http.Request, pathValues map[string]string) (sceneryruntime.ContractDecodedRequest, error) {
					input, err := sceneryruntime.DecodeContractInput[contract.ProcessSceneInput](request, pathValues, sceneryruntime.ContractRequestSchema{Mappings: []sceneryruntime.ContractInputMapping{}, ContextMappings: []sceneryruntime.ContractContextMapping{}, Body: &sceneryruntime.ContractBodyMapping{Codec: "json", Target: "", Type: "record.process_scene_input", DecodeValue: func(data []byte, target any) error {
						return scenery.UnmarshalContractValue(data, target, "record.process_scene_input")
					}, Include: []string(nil), Except: []string(nil), AcceptedMediaTypes: []string{}, SupportedContentEncoding: []string{}, MaxCompressedBytes: 8388608, MaxDecompressedBytes: 16777216, Fields: []sceneryruntime.ContractInputMapping{}, MultipartParts: []sceneryruntime.ContractMultipartPart{}, MaxMultipartParts: 128}, TransportStatuses: map[string]int{"admission.rate_limited": 429, "system.internal": 500, "transport.invalid_request": 400, "transport.not_acceptable": 406, "transport.unsupported_media_type": 415}})
					return sceneryruntime.ContractDecodedRequest{Payload: input}, err
				},
				Invoke: func(ctx context.Context, _ []any, payload any) (any, error) {
					if service == nil {
						return nil, sceneryruntime.ContractSystemError(fmt.Errorf("service is not initialized"))
					}
					copied, err := contract.CloneProcessSceneInput(payload.(contract.ProcessSceneInput))
					if err != nil {
						return nil, sceneryruntime.ContractSystemError(err)
					}
					outcome, err := service.ProcessScene(ctx, copied)
					if err != nil {
						if outcome != nil {
							return nil, sceneryruntime.ContractSystemError(fmt.Errorf("handler returned outcome and error"))
						}
						return nil, sceneryruntime.ContractSystemError(err)
					}
					if outcome == nil {
						return nil, sceneryruntime.ContractSystemError(fmt.Errorf("handler returned nil outcome without error"))
					}
					cloned, err := contract.CloneProcessSceneOutcome(outcome)
					if err != nil {
						return nil, sceneryruntime.ContractSystemError(err)
					}
					if err := sceneryruntime.PublishContractOperationOutcome(ctx, "house/operation/process_scene", cloned); err != nil {
						return nil, sceneryruntime.ContractSystemError(err)
					}
					return cloned, nil
				},
				EncodeContractOutcome: func(request *http.Request, outcome any) (sceneryruntime.ContractHTTPResponse, error) {
					_ = request
					switch typed := outcome.(type) {
					case contract.ProcessSceneProcessed:
						response, err := sceneryruntime.EncodeContractRepresentationWithOptions(request, 200, typed.Value, "json", []string{"application/json"}, sceneryruntime.ContractResponseOptions{MaxBytes: 16777216, CompressionAlgorithms: []string{"gzip"}, CompressionThreshold: 1024, TypeExpression: "record.process_scene_result", EncodeValue: func(value any) ([]byte, error) {
							return scenery.MarshalContractValue(value, "record.process_scene_result")
						}})
						if err != nil {
							return sceneryruntime.ContractHTTPResponse{}, err
						}
						return response, nil
					default:
						return sceneryruntime.ContractHTTPResponse{}, fmt.Errorf("handler returned an unknown outcome %T", outcome)
					}
				},
			}); err != nil {
				return err
			}
			return nil
		},
	})
}
