package vnext

import "strings"

func renderTSRuntime() string {
	return strings.ReplaceAll(renderTSRuntimePublic()+renderTSRuntimeInternals()+renderTSRuntimeValidation(), "§", "`")
}

func renderTSRuntimePublic() string {
	return `// Code generated by Scenery vNext. DO NOT EDIT.
import type {
  DateString,
  DateTimeString,
  DecimalString,
  DurationString,
  JsonNumber,
  JsonValue,
  RelativePathString,
  URLString,
  UUIDString,
} from "./types.js";

export class SceneryClientError extends Error {
  constructor(
    readonly code: string,
    readonly bindingAddress: string,
    message: string,
    readonly cause?: unknown,
  ) {
    super(message);
    this.name = "SceneryClientError";
  }

  toJSON(): Readonly<{ name: string; code: string; bindingAddress: string; message: string }> {
    return Object.freeze({ name: this.name, code: this.code, bindingAddress: this.bindingAddress, message: this.message });
  }
}

export interface CallOptions {
  readonly signal?: AbortSignal;
  readonly headers?: Readonly<Record<string, string>>;
}

export interface AuthenticationOptions {
  readonly authorization?: string;
  readonly credentials?: RequestCredentials;
}

export interface RetryRuntime {
  readonly now: () => number;
  readonly sleep: (milliseconds: number, signal?: AbortSignal) => Promise<void>;
}

export interface RetryPolicy {
  readonly maximumAttempts: number;
  readonly statuses: readonly number[];
  readonly maximumDelayMilliseconds: number;
}

export interface MultipartPartDescriptor {
  readonly name: string;
  readonly property: string;
  readonly kind: "text" | "bytes" | "file";
  readonly mediaTypes: readonly string[];
  readonly maxBytes: number;
  readonly multiple: boolean;
  readonly optional: boolean;
  readonly retainFilename: boolean;
  readonly value: TypeDescriptor;
  readonly fileProperties?: Readonly<{ bytes: string; filename: string; mediaType: string }>;
}

export interface MultipartBodyDescriptor {
  readonly value: TypeDescriptor;
  readonly parts: readonly MultipartPartDescriptor[];
  readonly maxParts: number;
  readonly maxBytes: number;
}

export type TypeDescriptor =
  | { readonly kind: "primitive"; readonly name: string }
  | { readonly kind: "named"; readonly name: string }
  | { readonly kind: "optional"; readonly value: TypeDescriptor }
  | { readonly kind: "nullable"; readonly value: TypeDescriptor }
  | { readonly kind: "list"; readonly value: TypeDescriptor }
  | { readonly kind: "set"; readonly value: TypeDescriptor }
  | { readonly kind: "map"; readonly value: TypeDescriptor }
  | { readonly kind: "tuple"; readonly values: readonly TypeDescriptor[] }
  | {
      readonly kind: "record";
      readonly fields: readonly FieldDescriptor[];
      readonly preserveUnknown: boolean;
      readonly validations?: readonly ValidationDescriptor[];
    }
  | { readonly kind: "enum"; readonly values: readonly string[]; readonly open: boolean }
  | {
      readonly kind: "union";
      readonly discriminator: string;
      readonly variants: Readonly<Record<string, TypeDescriptor>>;
      readonly open: boolean;
    };

export interface FieldDescriptor {
  readonly property: string;
  readonly wire: string;
  readonly value: TypeDescriptor;
  readonly optional: boolean;
  readonly constraints?: ConstraintDescriptor;
}

export interface ConstraintDescriptor {
  readonly minimum?: string;
  readonly maximum?: string;
  readonly min_length?: number | string;
  readonly max_length?: number | string;
  readonly pattern?: string;
  readonly format?: string;
  readonly min_items?: number | string;
  readonly max_items?: number | string;
  readonly unique_items?: boolean;
  readonly sensitive?: boolean;
  readonly immutable?: boolean;
  readonly deprecated?: unknown;
}

export interface ValidationDescriptor {
  readonly name: string;
  readonly source: string;
  readonly expression: ValidationExpression;
  readonly code: string;
  readonly message: string;
  readonly path: string;
}

export type ValidationExpression =
  | { readonly kind: "literal"; readonly type: "null" | "bool" | "string" | "number"; readonly value?: boolean | string }
  | { readonly kind: "value" }
  | { readonly kind: "attribute"; readonly source: ValidationExpression; readonly name: string }
  | { readonly kind: "index"; readonly collection: ValidationExpression; readonly key: ValidationExpression }
  | { readonly kind: "call"; readonly name: string; readonly arguments: readonly ValidationExpression[] }
  | { readonly kind: "binary"; readonly operator: string; readonly left: ValidationExpression; readonly right: ValidationExpression }
  | { readonly kind: "unary"; readonly operator: string; readonly value: ValidationExpression }
  | { readonly kind: "conditional"; readonly condition: ValidationExpression; readonly true_result: ValidationExpression; readonly false_result: ValidationExpression }
  | { readonly kind: "tuple"; readonly values: readonly ValidationExpression[] }
  | { readonly kind: "object"; readonly entries: readonly { readonly key: ValidationExpression; readonly value: ValidationExpression }[] }
  | { readonly kind: "template"; readonly parts: readonly ValidationExpression[] };

export type TypeRegistry = Readonly<Record<string, TypeDescriptor>>;

const jsonNumbers = new WeakSet<object>();
const forbiddenObjectKeys = new Set(["__proto__", "prototype", "constructor"]);
const frameworkHeaders = new Set([
  "authorization",
  "connection",
  "content-length",
  "content-type",
  "cookie",
  "forwarded",
  "host",
  "traceparent",
  "tracestate",
]);

export function jsonNumber(coefficient: string, scale: number): JsonNumber {
  const normalized = normalizeJsonNumber(coefficient, scale);
  const value = Object.freeze({ coefficient: normalized.coefficient, scale: normalized.scale }) as JsonNumber;
  jsonNumbers.add(value as object);
  return value;
}

export function isJsonNumber(value: unknown): value is JsonNumber {
  return typeof value === "object" && value !== null && jsonNumbers.has(value);
}

export function freezeMetadata<T>(value: T): Readonly<T> {
  if (typeof value !== "object" || value === null || Object.isFrozen(value)) return value as Readonly<T>;
  for (const item of Object.values(value)) freezeMetadata(item);
  return Object.freeze(value);
}

export function decimal(value: string): DecimalString {
  encodePrimitive(value, "decimal", "$.");
  return value as DecimalString;
}

export function uuid(value: string): UUIDString {
  encodePrimitive(value, "uuid", "$.");
  return value as UUIDString;
}

export function date(value: string): DateString {
  encodePrimitive(value, "date", "$.");
  return value as DateString;
}

export function dateTime(value: string): DateTimeString {
  encodePrimitive(value, "datetime", "$.");
  return value as DateTimeString;
}

export function duration(value: string): DurationString {
  encodePrimitive(value, "duration", "$.");
  return value as DurationString;
}

export function url(value: string): URLString {
  encodePrimitive(value, "url", "$.");
  return value as URLString;
}

export function relativePath(value: string): RelativePathString {
  encodePrimitive(value, "relative_path", "$.");
  return value as RelativePathString;
}

export function parseExactJSON(source: string): JsonValue {
  let offset = 0;
  const whitespace = () => {
    while (offset < source.length && /[\t\n\r ]/.test(source[offset] ?? "")) offset++;
  };
  const fail = (message: string): never => {
    throw new SceneryClientError("contract_violation", "", message);
  };
  const parseString = (): string => {
    const start = offset;
    offset++;
    let escaped = false;
    while (offset < source.length) {
      const character = source[offset] ?? "";
      if (!escaped && character === '"') {
        offset++;
        let value: string;
        try {
          value = JSON.parse(source.slice(start, offset)) as string;
        } catch {
          return fail("invalid JSON string");
        }
        assertUnicodeScalarString(value);
        return value;
      }
      if (!escaped && character.charCodeAt(0) < 0x20) return fail("invalid JSON string");
      escaped = !escaped && character === "\\";
      if (character !== "\\") escaped = false;
      offset++;
    }
    return fail("unterminated JSON string");
  };
  const parseValue = (): JsonValue => {
    whitespace();
    const character = source[offset];
    if (character === '"') return parseString();
    if (character === "[") {
      offset++;
      const values: JsonValue[] = [];
      whitespace();
      if (source[offset] === "]") {
        offset++;
        return Object.freeze(values);
      }
      while (true) {
        values.push(parseValue());
        whitespace();
        if (source[offset] === "]") {
          offset++;
          return Object.freeze(values);
        }
        if (source[offset] !== ",") return fail("invalid JSON array");
        offset++;
      }
    }
    if (character === "{") {
      offset++;
      const value = Object.create(null) as Record<string, JsonValue>;
      const names = new Set<string>();
      whitespace();
      if (source[offset] === "}") {
        offset++;
        return Object.freeze(value);
      }
      while (true) {
        whitespace();
        if (source[offset] !== '"') return fail("invalid JSON object member");
        const name = parseString();
        if (names.has(name)) return fail("duplicate object member");
        assertSafeKey(name);
        names.add(name);
        whitespace();
        if (source[offset] !== ":") return fail("invalid JSON object member");
        offset++;
        value[name] = parseValue();
        whitespace();
        if (source[offset] === "}") {
          offset++;
          return Object.freeze(value);
        }
        if (source[offset] !== ",") return fail("invalid JSON object");
        offset++;
      }
    }
    for (const [token, value] of [["true", true], ["false", false], ["null", null]] as const) {
      if (source.startsWith(token, offset)) {
        offset += token.length;
        return value;
      }
    }
    const match = /^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/.exec(source.slice(offset));
    if (match === null) return fail("invalid JSON value");
    offset += match[0].length;
    return jsonNumberFromToken(match[0]);
  };
  if (source.charCodeAt(0) === 0xfeff) fail("JSON byte-order mark is forbidden");
  const value = parseValue();
  whitespace();
  if (offset !== source.length) fail("trailing bytes after JSON value");
  return value;
}

export function encodeJSON(value: JsonValue): string {
  return encodeExactJSON(value, "$");
}

export function encodeTypedJSON(value: unknown, descriptor: TypeDescriptor, registry: TypeRegistry): string {
  return encodeTypedValue(value, descriptor, registry, "$", new Set());
}

export function encodeRequestBody(
  value: unknown,
  codec: string,
  descriptor: TypeDescriptor,
  registry: TypeRegistry,
): BodyInit {
  if (codec === "json" || codec === "problem_json") return encodeTypedJSON(value, descriptor, registry);
  if (codec === "text") {
    if (typeof value !== "string") invalid("$", "text body requires a string");
    assertUnicodeScalarString(value);
    return value;
  }
  if (codec === "bytes") {
    if (!(value instanceof Uint8Array)) invalid("$", "bytes body requires Uint8Array");
    return new Uint8Array(value);
  }
  const resolved = resolveDescriptor(descriptor, registry, new Set());
  if (resolved.kind !== "record" || !isObject(value)) invalid("$", §${codec} body requires a record§);
  validateRecordRules(value, resolved, registry, "$");
  if (codec === "form") {
    const form = new URLSearchParams();
    for (const field of resolved.fields) {
      const item = value[field.property];
      if (item === undefined && field.optional) continue;
      validateConstraints(item, field.constraints, field.value, registry, §$.${field.property}§);
      const collection = orderedHTTPItems(item, field.value, registry, §$.${field.property}§);
      for (const entry of collection.items) form.append(field.wire, encodeHTTPValue(entry, collection.itemDescriptor, registry));
    }
    return form;
  }
  if (codec === "multipart") invalid("$", "multipart requires a declared part schema");
  invalid("$", "unsupported request body codec");
}

export function encodeMultipartRequestBody(
  value: unknown,
  descriptor: MultipartBodyDescriptor,
  registry: TypeRegistry,
): Readonly<{ body: Uint8Array; contentType: string }> {
  if (!isObject(value) || Array.isArray(value)) invalid("$", "multipart body requires a record");
  encodeTypedValue(value, descriptor.value, registry, "$", new Set());
  if (!Number.isSafeInteger(descriptor.maxParts) || descriptor.maxParts <= 0) invalid("$", "invalid multipart part limit");
  if (!Number.isSafeInteger(descriptor.maxBytes) || descriptor.maxBytes <= 0) invalid("$", "invalid multipart body limit");
  const encoder = new TextEncoder();
  const encodedParts: Array<Readonly<{ header: string; bytes: Uint8Array }>> = [];
  for (const part of descriptor.parts) {
    const item = value[part.property];
    if (item === undefined) {
      if (part.optional) continue;
      invalid(§$.${part.property}§, §missing multipart part ${part.name}§);
    }
    const collection = orderedHTTPItems(item, part.value, registry, §$.${part.property}§);
    if (collection.collection !== part.multiple) invalid(§$.${part.property}§, "multipart multiplicity contradicts the contract");
    if (collection.items.length === 0 && !part.optional) invalid(§$.${part.property}§, "required multipart collection is empty");
    for (const entry of collection.items) {
      let bytes: Uint8Array;
      let filename: string | undefined;
      let contentType: string;
      if (part.kind === "text") {
        bytes = encoder.encode(encodeHTTPValue(entry, collection.itemDescriptor, registry));
        contentType = selectMultipartMediaType(part.mediaTypes, "text/plain");
      } else if (part.kind === "bytes") {
        if (!(entry instanceof Uint8Array)) invalid(§$.${part.property}§, "multipart byte part requires Uint8Array");
        bytes = new Uint8Array(entry);
        contentType = selectMultipartMediaType(part.mediaTypes, "application/octet-stream");
      } else {
        if (part.retainFilename) {
          if (!isObject(entry) || Array.isArray(entry) || part.fileProperties === undefined) invalid(§$.${part.property}§, "multipart file metadata is invalid");
          const rawBytes = entry[part.fileProperties.bytes];
          const rawFilename = entry[part.fileProperties.filename];
          const rawMediaType = entry[part.fileProperties.mediaType];
          if (!(rawBytes instanceof Uint8Array) || typeof rawFilename !== "string" || rawFilename === "" || typeof rawMediaType !== "string") invalid(§$.${part.property}§, "multipart file metadata is invalid");
          bytes = new Uint8Array(rawBytes);
          filename = rawFilename;
          contentType = canonicalMultipartMediaType(rawMediaType, part.mediaTypes);
        } else {
          if (!(entry instanceof Uint8Array)) invalid(§$.${part.property}§, "multipart file part requires Uint8Array");
          bytes = new Uint8Array(entry);
          filename = "blob";
          contentType = selectMultipartMediaType(part.mediaTypes, "application/octet-stream");
        }
      }
      if (bytes.byteLength > part.maxBytes) invalid(§$.${part.property}§, §multipart part ${part.name} exceeds its byte limit§);
      const disposition = §Content-Disposition: form-data; name="${multipartQuoted(part.name)}"${filename === undefined ? "" : §; filename="${multipartQuoted(filename)}"§}§;
      encodedParts.push({ header: §${disposition}\r\nContent-Type: ${contentType}§, bytes });
      if (encodedParts.length > descriptor.maxParts) invalid("$", "multipart part limit exceeded");
    }
  }
  let boundary = "scenery-vnext-boundary";
  while (encodedParts.some((part) => part.header.includes(boundary) || containsByteSequence(part.bytes, encoder.encode(boundary)))) boundary += "x";
  const chunks: Uint8Array[] = [];
  let total = 0;
  const append = (chunk: Uint8Array) => {
    total += chunk.byteLength;
    if (total > descriptor.maxBytes) invalid("$", "multipart body exceeds its byte limit");
    chunks.push(chunk);
  };
  for (const part of encodedParts) {
    append(encoder.encode(§--${boundary}\r\n${part.header}\r\n\r\n§));
    append(part.bytes);
    append(encoder.encode("\r\n"));
  }
  append(encoder.encode(§--${boundary}--\r\n§));
  const body = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) { body.set(chunk, offset); offset += chunk.byteLength; }
  return Object.freeze({ body, contentType: §multipart/form-data; boundary=${boundary}§ });
}

function multipartQuoted(value: string): string {
  assertUnicodeScalarString(value);
  if (value === "" || /[\u0000-\u001f\u007f]/.test(value)) invalid("$", "invalid multipart name or filename");
  return value.replace(/(["\\])/g, "\\$1");
}

function canonicalMultipartMediaType(value: string, allowed: readonly string[]): string {
  const parsed = parseMediaType(value);
  if (parsed.base.includes("*") || Object.keys(parsed.parameters).length > 0 || !multipartMediaAllowed(parsed.base, allowed)) invalid("$", "multipart media type is not accepted");
  return parsed.base;
}

function selectMultipartMediaType(allowed: readonly string[], fallback: string): string {
  if (allowed.length === 0 || multipartMediaAllowed(fallback, allowed)) return fallback;
  for (const value of allowed) {
    const parsed = parseMediaType(value);
    if (!parsed.base.includes("*") && Object.keys(parsed.parameters).length === 0) return parsed.base;
  }
  invalid("$", "multipart media type requires caller metadata");
}

function multipartMediaAllowed(actual: string, allowed: readonly string[]): boolean {
  if (allowed.length === 0) return true;
  const actualParts = parseMediaType(actual).base.split("/");
  return allowed.some((candidate) => {
    const expected = parseMediaType(candidate).base.split("/");
    return (expected[0] === "*" || expected[0] === actualParts[0]) && (expected[1] === "*" || expected[1] === actualParts[1]);
  });
}

function containsByteSequence(value: Uint8Array, sequence: Uint8Array): boolean {
  outer: for (let offset = 0; offset + sequence.length <= value.length; offset++) {
    for (let index = 0; index < sequence.length; index++) if (value[offset + index] !== sequence[index]) continue outer;
    return true;
  }
  return false;
}

type ParsedMediaType = { readonly base: string; readonly parameters: Readonly<Record<string, string>> };

function splitMediaType(value: string): string[] {
  const parts: string[] = [];
  let start = 0;
  let quoted = false;
  let escaped = false;
  for (let index = 0; index < value.length; index++) {
    const character = value[index]!;
    if (escaped) { escaped = false; continue; }
    if (quoted && character === "\\") { escaped = true; continue; }
    if (character === '"') { quoted = !quoted; continue; }
    if (character === ";" && !quoted) { parts.push(value.slice(start, index)); start = index + 1; }
  }
  if (quoted || escaped) throw new Error("invalid quoted media type parameter");
  parts.push(value.slice(start));
  return parts;
}

function mediaTypeToken(value: string): boolean {
  return /^[!#$%&'*+.^_\x60|~0-9A-Za-z-]+$/.test(value);
}

function decodeMediaTypeParameter(value: string): string {
  if (!value.startsWith('"')) {
    if (!mediaTypeToken(value)) throw new Error("invalid media type parameter value");
    return value;
  }
  if (!value.endsWith('"')) throw new Error("invalid quoted media type parameter");
  let decoded = "";
  for (let index = 1; index < value.length - 1; index++) {
    const character = value[index]!;
    if (character === "\\") {
      index++;
      if (index >= value.length - 1) throw new Error("invalid quoted media type escape");
      decoded += value[index]!;
      continue;
    }
    if (character === '"' || character.charCodeAt(0) < 0x20 || character.charCodeAt(0) === 0x7f) throw new Error("invalid quoted media type parameter");
    decoded += character;
  }
  return decoded;
}

function parseMediaType(value: string): ParsedMediaType {
  const parts = splitMediaType(value);
  const base = (parts.shift() ?? "").trim().toLowerCase();
  const baseParts = base.split("/");
  if (baseParts.length !== 2 || !mediaTypeToken(baseParts[0]!) || !mediaTypeToken(baseParts[1]!)) throw new Error("invalid media type");
  const parameters: Record<string, string> = {};
  for (const raw of parts) {
    const separator = raw.indexOf("=");
    if (separator <= 0) throw new Error("invalid media type parameter");
    const name = raw.slice(0, separator).trim().toLowerCase();
    if (!mediaTypeToken(name) || Object.prototype.hasOwnProperty.call(parameters, name)) throw new Error("invalid or duplicate media type parameter");
    let parameter = decodeMediaTypeParameter(raw.slice(separator + 1).trim());
    parameters[name] = name === "charset" ? parameter.toLowerCase() : parameter;
  }
  if (parameters.charset === "utf-8" || parameters.charset === "") delete parameters.charset;
  return { base, parameters };
}

function mediaTypeMatches(actual: string, expected: string): boolean {
  const left = parseMediaType(actual);
  const right = parseMediaType(expected);
  if (left.base !== right.base) return false;
  const leftEntries = Object.entries(left.parameters).sort();
  const rightEntries = Object.entries(right.parameters).sort();
  return JSON.stringify(leftEntries) === JSON.stringify(rightEntries);
}

async function readBoundedResponse(response: Response, maximumBytes: number, bindingAddress: string): Promise<Uint8Array> {
  const declared = response.headers.get("content-length");
  if (declared !== null && (!/^(0|[1-9][0-9]*)$/.test(declared) || BigInt(declared) > BigInt(maximumBytes))) {
    throw new SceneryClientError("contract_violation", bindingAddress, "response exceeds the contract byte limit");
  }
  if (response.body === null) return new Uint8Array();
  const reader = response.body.getReader();
  const chunks: Uint8Array[] = [];
  let total = 0;
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    if (value === undefined) continue;
    total += value.byteLength;
    if (total > maximumBytes) {
      await reader.cancel();
      throw new SceneryClientError("contract_violation", bindingAddress, "response exceeds the contract byte limit");
    }
    chunks.push(value);
  }
  const output = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) { output.set(chunk, offset); offset += chunk.byteLength; }
  return output;
}

export function mergeResponseValue(current: unknown, path: readonly string[], value: unknown, bindingAddress: string): unknown {
	if (value === undefined && path.length > 0) return current;
  if (path.length === 0) {
    if (current !== undefined) throw new SceneryClientError("contract_violation", bindingAddress, "response mappings overlap");
    return value;
  }
  const root = current === undefined ? Object.create(null) as Record<string, unknown> : current;
  if (!isObject(root) || Array.isArray(root)) throw new SceneryClientError("contract_violation", bindingAddress, "response mappings overlap");
  let target = root as Record<string, unknown>;
  for (let index = 0; index < path.length - 1; index++) {
    const segment = path[index]!;
    assertSafeKey(segment);
    const existing = target[segment];
    if (existing === undefined) target[segment] = Object.create(null) as Record<string, unknown>;
    else if (!isObject(existing) || Array.isArray(existing)) throw new SceneryClientError("contract_violation", bindingAddress, "response mappings overlap");
    target = target[segment] as Record<string, unknown>;
  }
  const leaf = path[path.length - 1]!;
  assertSafeKey(leaf);
  if (Object.prototype.hasOwnProperty.call(target, leaf)) throw new SceneryClientError("contract_violation", bindingAddress, "response mappings overlap");
  target[leaf] = value;
  return root;
}

type ResponseHeaderValues = { readonly values: readonly string[]; readonly preservesRepetition: boolean };

function responseHeaderValues(headers: Headers, name: string): ResponseHeaderValues {
  const extended = headers as Headers & {
    getAll?: (name: string) => string[];
    getSetCookie?: () => string[];
    raw?: () => Record<string, string[]>;
  };
  if (name.toLowerCase() === "set-cookie" && typeof extended.getSetCookie === "function") {
    return { values: extended.getSetCookie(), preservesRepetition: true };
  }
  if (typeof extended.getAll === "function") return { values: extended.getAll(name), preservesRepetition: true };
  if (typeof extended.raw === "function") {
    const raw = extended.raw();
    return { values: raw[name.toLowerCase()] ?? raw[name] ?? [], preservesRepetition: true };
  }
  const value = headers.get(name);
  return { values: value === null ? [] : [value], preservesRepetition: false };
}

function responseHTTPWireValue(value: string, descriptor: TypeDescriptor, registry: TypeRegistry, bindingAddress: string): unknown {
  const resolved = unwrapResponseMetadataDescriptor(descriptor, registry, new Set());
  if (resolved.kind === "enum") return value;
  if (resolved.kind !== "primitive") throw new SceneryClientError("contract_violation", bindingAddress, "response metadata requires a scalar codec");
  switch (resolved.name) {
    case "bool":
      if (value !== "true" && value !== "false") throw new SceneryClientError("contract_violation", bindingAddress, "malformed boolean response metadata");
      return value === "true";
    case "int32":
    case "uint32":
    case "float32":
    case "float64":
      return parseExactJSON(value);
    case "json":
      return parseExactJSON(value);
    default:
      return value;
  }
}

function unwrapResponseMetadataDescriptor(descriptor: TypeDescriptor, registry: TypeRegistry, resolving: Set<string>): TypeDescriptor {
  if (descriptor.kind === "named") {
    if (resolving.has(descriptor.name)) throw new Error("recursive response metadata type descriptor");
    const resolved = registry[descriptor.name];
    if (resolved === undefined) throw new Error("missing response metadata type descriptor");
    const next = new Set(resolving);
    next.add(descriptor.name);
    return unwrapResponseMetadataDescriptor(resolved, registry, next);
  }
  if (descriptor.kind === "optional" || descriptor.kind === "nullable") return unwrapResponseMetadataDescriptor(descriptor.value, registry, resolving);
  return descriptor;
}

function responseMetadataIsOptional(descriptor: TypeDescriptor, registry: TypeRegistry, resolving: Set<string>): boolean {
	if (descriptor.kind === "named") {
		if (resolving.has(descriptor.name)) throw new Error("recursive response metadata type descriptor");
		const resolved = registry[descriptor.name];
		if (resolved === undefined) throw new Error("missing response metadata type descriptor");
		const next = new Set(resolving);
		next.add(descriptor.name);
		return responseMetadataIsOptional(resolved, registry, next);
	}
	return descriptor.kind === "optional";
}

export function decodeResponseHeader(
  response: Response,
  name: string,
  encoding: string,
  descriptor: TypeDescriptor,
  registry: TypeRegistry,
  bindingAddress: string,
): unknown {
	try {
		const raw = responseHeaderValues(response.headers, name);
		if (raw.values.length === 0) {
			if (responseMetadataIsOptional(descriptor, registry, new Set())) return undefined;
			throw new SceneryClientError("contract_violation", bindingAddress, §required response header ${name} is absent§);
		}
    const resolved = unwrapResponseMetadataDescriptor(descriptor, registry, new Set());
    const collection = resolved.kind === "list" || resolved.kind === "set";
    if (encoding === "json") {
      if (raw.values.length !== 1) throw new SceneryClientError("contract_violation", bindingAddress, §response header ${name} is repeated§);
      return decodeTypedValue(parseExactJSON(raw.values[0]!), descriptor, registry, §$headers.${name}§, new Set());
    }
    let values = raw.values;
    if (encoding === "comma") values = raw.values.flatMap((item) => item.split(",").map((part) => part.trim()));
    else if (encoding !== "repeated") throw new SceneryClientError("contract_violation", bindingAddress, "unsupported response header encoding");
		if (encoding === "repeated" && !raw.preservesRepetition) {
			throw new SceneryClientError("unsupported_runtime", bindingAddress, §fetch runtime cannot preserve repeated response header ${name}§);
		}
    if (!collection && values.length !== 1) throw new SceneryClientError("contract_violation", bindingAddress, §scalar response header ${name} is repeated§);
    const itemDescriptor = collection ? resolved.value : descriptor;
    const wire = values.map((item) => responseHTTPWireValue(item, itemDescriptor, registry, bindingAddress));
    return decodeTypedValue(collection ? wire : wire[0], descriptor, registry, §$headers.${name}§, new Set());
  } catch (cause) {
    if (cause instanceof SceneryClientError && cause.bindingAddress === bindingAddress) throw cause;
    throw new SceneryClientError("contract_violation", bindingAddress, §malformed response header ${name}§, safeCause(cause));
  }
}

export function decodeResponseCookie(
  response: Response,
  name: string,
  descriptor: TypeDescriptor,
  registry: TypeRegistry,
  bindingAddress: string,
): unknown {
	try {
		const raw = responseHeaderValues(response.headers, "set-cookie");
		if (!raw.preservesRepetition) throw new SceneryClientError("unsupported_runtime", bindingAddress, "fetch runtime does not expose Set-Cookie values");
    const prefix = §${name}=§;
    const matches = raw.values.flatMap((cookie) => {
      const pair = cookie.split(";", 1)[0]!.trim();
      return pair.startsWith(prefix) ? [pair.slice(prefix.length)] : [];
    });
		if (matches.length === 0 && responseMetadataIsOptional(descriptor, registry, new Set())) return undefined;
		if (matches.length !== 1) throw new SceneryClientError("contract_violation", bindingAddress, §response cookie ${name} is absent or duplicated§);
    const decoded = decodeURIComponent(matches[0]!);
    const wire = responseHTTPWireValue(decoded, descriptor, registry, bindingAddress);
    return decodeTypedValue(wire, descriptor, registry, §$cookies.${name}§, new Set());
  } catch (cause) {
    if (cause instanceof SceneryClientError && cause.bindingAddress === bindingAddress) throw cause;
    throw new SceneryClientError("contract_violation", bindingAddress, §malformed response cookie ${name}§, safeCause(cause));
  }
}

export async function decodeResponseBody(
  response: Response,
  codec: string,
  producedMediaTypes: readonly string[],
  descriptor: TypeDescriptor,
  registry: TypeRegistry,
  bindingAddress: string,
  maximumBytes: number,
): Promise<unknown> {
  try {
    const media = response.headers.get("content-type") ?? "";
    if (!producedMediaTypes.some((expected) => mediaTypeMatches(media, expected))) {
      throw new SceneryClientError("contract_violation", bindingAddress, "response content type contradicts the contract");
    }
    const bytes = await readBoundedResponse(response, maximumBytes, bindingAddress);
    if (codec === "bytes") {
      const resolved = resolveDescriptor(descriptor, registry, new Set());
      if (resolved.kind !== "primitive" || resolved.name !== "bytes") throw new SceneryClientError("contract_violation", bindingAddress, "bytes response contradicts its type");
      return bytes;
    }
    const source = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
    if (codec === "text") {
      assertUnicodeScalarString(source);
      return decodeTypedValue(source, descriptor, registry, "$", new Set());
    }
    if (codec !== "json" && codec !== "problem_json") {
      throw new SceneryClientError("contract_violation", bindingAddress, "unsupported response codec");
    }
    return decodeTypedValue(parseExactJSON(source), descriptor, registry, "$", new Set());
  } catch (cause) {
    if (cause instanceof SceneryClientError && cause.bindingAddress === bindingAddress) throw cause;
    throw new SceneryClientError("contract_violation", bindingAddress, "malformed response body", safeCause(cause));
  }
}

export async function assertEmptyResponse(response: Response, bindingAddress: string, maximumBytes: number): Promise<void> {
  if ((await readBoundedResponse(response, maximumBytes, bindingAddress)).byteLength !== 0) {
    throw new SceneryClientError("contract_violation", bindingAddress, "response body contradicts the contract");
  }
}

export async function fetchWithRetry(
  fetchImplementation: typeof globalThis.fetch,
  url: string,
  init: RequestInit,
  signal: AbortSignal | undefined,
  runtime: RetryRuntime,
  policy: RetryPolicy,
): Promise<Response> {
  let lastCause: unknown;
  for (let attempt = 1; attempt <= policy.maximumAttempts; attempt++) {
    if (signal?.aborted) throw new SceneryClientError("cancelled", "", "request cancelled", lastCause);
    try {
      const response = await fetchImplementation(url, replayableRequestInit(init));
      if (attempt === policy.maximumAttempts || !policy.statuses.includes(response.status)) return response;
      const delay = retryDelay(response.headers.get("retry-after"), runtime.now(), policy.maximumDelayMilliseconds);
      await runtime.sleep(delay, signal);
    } catch (cause) {
      if (signal?.aborted) throw new SceneryClientError("cancelled", "", "request cancelled", cause);
      lastCause = cause;
      if (attempt === policy.maximumAttempts) throw cause;
      await runtime.sleep(0, signal);
    }
  }
  throw lastCause;
}

export function mergeHeaders(
  defaults: Readonly<Record<string, string>> | undefined,
  call: Readonly<Record<string, string>> | undefined,
  bindingAddress: string,
): Headers {
  const result = new Headers();
  for (const source of [defaults, call]) {
    for (const [rawName, value] of Object.entries(source ?? {})) {
      const name = rawName.toLowerCase();
      if (frameworkHeaders.has(name) || name.startsWith("x-forwarded-")) {
        throw new SceneryClientError("invalid_options", bindingAddress, "a generic header attempted to override a framework-owned header");
      }
      if (!/^[!#$%&'*+.^_§|~0-9a-z-]+$/.test(name) || /[\r\n]/.test(value)) {
        throw new SceneryClientError("invalid_options", bindingAddress, "invalid request header");
      }
      result.set(name, value);
    }
  }
  return result;
}

export function encodeHTTPValue(value: unknown, descriptor?: TypeDescriptor, registry: TypeRegistry = Object.freeze({})): string {
  if (descriptor !== undefined) return encodeTypedHTTPValue(value, descriptor, registry, new Set());
  if (typeof value === "string") {
    assertUnicodeScalarString(value);
    return value;
  }
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "bigint") return value.toString(10);
  if (typeof value === "number" && Number.isFinite(value) && !Object.is(value, -0)) return String(value);
  throw new SceneryClientError("invalid_input", "", "HTTP scalar value is missing or invalid");
}

export function encodeRFC3986(value: string): string {
  return encodeURIComponent(value).replace(/[!'()*]/g, (character) =>
    §%${character.charCodeAt(0).toString(16).toUpperCase()}§,
  );
}

export function appendPathTail(prefix: string, value: unknown, descriptor: TypeDescriptor, registry: TypeRegistry = Object.freeze({})): string {
  let semantic: string;
  if (value === undefined) {
    const resolved = resolveDescriptor(descriptor, registry, new Set());
    if (resolved.kind !== "optional") throw new SceneryClientError("invalid_input", "", "path tail is missing");
    return prefix === "" ? "/" : prefix;
  }
  semantic = encodeHTTPValue(value, descriptor, registry);
  if (semantic === "") return prefix === "" ? "/" : prefix;
  const segments = semantic.split("/");
  if (segments.some((segment) => segment === "" || segment === "." || segment === ".." || segment.includes("\\"))) {
    throw new SceneryClientError("invalid_input", "", "path tail contains an invalid segment");
  }
  for (const segment of segments) {
    try {
      const decodedAgain = decodeURIComponent(segment);
      if (decodedAgain === "." || decodedAgain === ".." || /[\\/\0]/.test(decodedAgain)) {
        throw new SceneryClientError("invalid_input", "", "path tail contains a hazardous encoded segment");
      }
    } catch (error) {
      if (error instanceof SceneryClientError) throw error;
    }
  }
  return §${prefix}/${segments.map(encodeRFC3986).join("/")}§;
}

export function appendQuery(target: string[], name: string, value: unknown, encoding = "repeated", descriptor?: TypeDescriptor, registry: TypeRegistry = Object.freeze({})): void {
  if (value === undefined) return;
  const encodedName = encodeRFC3986(name);
  if (encoding === "json") {
    const encoded = descriptor === undefined ? encodeJSON(value as JsonValue) : encodeTypedJSON(value, descriptor, registry);
    target.push(§${encodedName}=${encodeRFC3986(encoded)}§);
    return;
  }
  const collection = orderedHTTPItems(value, descriptor, registry, "$query");
  const values = collection.items.map((item) => encodeHTTPValue(item, collection.itemDescriptor, registry));
  if (encoding === "comma") {
    target.push(§${encodedName}=${values.map(encodeRFC3986).join(",")}§);
    return;
  }
  for (const item of values) target.push(§${encodedName}=${encodeRFC3986(item)}§);
}

export function appendHeader(target: Headers, name: string, value: unknown, encoding = "repeated", descriptor?: TypeDescriptor, registry: TypeRegistry = Object.freeze({})): void {
  if (value === undefined) return;
  const collection = orderedHTTPItems(value, descriptor, registry, "$headers");
  const values = collection.items.map((item) => encodeHTTPValue(item, collection.itemDescriptor, registry));
  if (encoding === "comma") target.set(name, values.join(","));
	else {
		if (values.length > 1) throw new SceneryClientError("unsupported_runtime", "", "fetch cannot preserve repeated request header field lines");
		if (values.length === 1) target.set(name, values[0]!);
	}
}

export function appendCookie(target: string[], name: string, value: unknown, descriptor?: TypeDescriptor, registry: TypeRegistry = Object.freeze({})): void {
  if (value === undefined) return;
  if (!/^[!#$%&'*+.^_§|~0-9A-Za-z-]+$/.test(name)) {
    throw new SceneryClientError("invalid_input", "", "invalid cookie name");
  }
  target.push(§${name}=${encodeRFC3986(encodeHTTPValue(value, descriptor, registry))}§);
}

export function isProblemCode(value: unknown, code: string): boolean {
  return isObject(value) && value.code === code;
}

function encodeTypedValue(
  value: unknown,
  descriptor: TypeDescriptor,
  registry: TypeRegistry,
  path: string,
  resolving: Set<string>,
): string {
  if (descriptor.kind === "named") {
    const resolved = registry[descriptor.name];
    if (resolved === undefined || resolving.has(descriptor.name)) invalid(path, "invalid named type descriptor");
    const next = new Set(resolving);
    next.add(descriptor.name);
    return encodeTypedValue(value, resolved, registry, path, next);
  }
  if (descriptor.kind === "optional") {
    if (value === undefined) invalid(path, "optional value is absent outside a record field");
    return encodeTypedValue(value, descriptor.value, registry, path, resolving);
  }
  if (descriptor.kind === "nullable") {
    return value === null ? "null" : encodeTypedValue(value, descriptor.value, registry, path, resolving);
  }
  if (descriptor.kind === "primitive") return encodePrimitive(value, descriptor.name, path);
  if (descriptor.kind === "list" || descriptor.kind === "set") {
    if (!Array.isArray(value)) invalid(path, "expected an array");
    const encoded = value.map((item, index) => encodeTypedValue(item, descriptor.value, registry, §${path}[${index}]§, resolving));
    if (descriptor.kind === "set") {
      encoded.sort(compareUTF8Bytewise);
      for (let index = 1; index < encoded.length; index++) {
        if (encoded[index] === encoded[index - 1]) invalid(path, "duplicate canonical set element");
      }
    }
    return §[${encoded.join(",")}]§;
  }
  if (descriptor.kind === "map") {
    if (!isObject(value) || Array.isArray(value)) invalid(path, "expected a map");
    const members: string[] = [];
    for (const key of Object.keys(value).sort()) {
      assertSafeKey(key);
      members.push(§${JSON.stringify(key)}:${encodeTypedValue(value[key], descriptor.value, registry, §${path}.${key}§, resolving)}§);
    }
    return §{${members.join(",")}}§;
  }
  if (descriptor.kind === "tuple") {
    if (!Array.isArray(value) || value.length !== descriptor.values.length) invalid(path, "tuple length mismatch");
    return §[${descriptor.values.map((item, index) => encodeTypedValue(value[index], item, registry, §${path}[${index}]§, resolving)).join(",")}]§;
  }
  if (descriptor.kind === "enum") {
    if (typeof value !== "string" || (!descriptor.open && !descriptor.values.includes(value))) invalid(path, "invalid enum value");
    return JSON.stringify(value);
  }
  if (descriptor.kind === "union") {
    if (!isObject(value) || typeof value.kind !== "string") invalid(path, "invalid tagged union");
    const variant = descriptor.variants[value.kind];
    let encodedPayload: string;
    if (variant === undefined) {
      if (!descriptor.open || value.unknown !== true) invalid(path, "unknown closed-union variant");
      encodedPayload = encodeExactJSON(value.value as JsonValue, §${path}.value§);
    } else {
      if (value.unknown === true) invalid(path, "known union variant cannot be unknown");
      encodedPayload = encodeTypedValue(value.value, variant, registry, §${path}.value§, resolving);
    }
    if (!encodedPayload.startsWith("{") || !encodedPayload.endsWith("}")) invalid(path, "union payload must encode as a record");
    const payloadMembers = encodedPayload.slice(1, -1);
    const discriminator = §${JSON.stringify(descriptor.discriminator)}:${JSON.stringify(value.kind)}§;
    return §{${discriminator}${payloadMembers === "" ? "" : "," + payloadMembers}}§;
  }
  if (!isObject(value) || Array.isArray(value)) invalid(path, "expected a record");
  const known = new Set(descriptor.fields.map((field) => field.property));
  const members = new Map<string, string>();
  for (const field of descriptor.fields) {
    const present = Object.prototype.hasOwnProperty.call(value, field.property) && value[field.property] !== undefined;
    if (!present) {
      if (!field.optional) invalid(§${path}.${field.property}§, "required field is absent");
      continue;
    }
    validateConstraints(value[field.property], field.constraints, field.value, registry, §${path}.${field.property}§);
    members.set(field.wire, encodeTypedValue(value[field.property], field.value, registry, §${path}.${field.property}§, resolving));
  }
  for (const property of Object.keys(value)) {
    if (!known.has(property) && property !== "unknownFields") invalid(§${path}.${property}§, "unknown record property");
  }
  validateRecordRules(value, descriptor, registry, path);
  if (descriptor.preserveUnknown) {
    const unknown = value.unknownFields;
    if (unknown !== undefined) {
      if (!isObject(unknown) || Array.isArray(unknown)) invalid(§${path}.unknownFields§, "invalid unknown-field map");
      for (const key of Object.keys(unknown).sort()) {
        assertSafeKey(key);
        if (members.has(key)) invalid(§${path}.unknownFields.${key}§, "unknown field collides with a declared wire name");
        members.set(key, encodeExactJSON(unknown[key] as JsonValue, §${path}.unknownFields.${key}§));
      }
    }
  }
  return §{${[...members].sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0).map(([key, encoded]) => §${JSON.stringify(key)}:${encoded}§).join(",")}}§;
}

`
}
