package vnext

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
)

func renderTSMetadata(target Resource, manifest *Manifest, bindings, reachable []Resource, revision, recommendation string) string {
	methods := map[string][]string{}
	guarantees := map[string]string{}
	counts := map[string]int{}
	for _, binding := range bindings {
		counts[lastRef(refString(binding.Spec["operation"]))]++
	}
	for _, binding := range bindings {
		operation := lastRef(refString(binding.Spec["operation"]))
		method := tsName(operation)
		if counts[operation] > 1 {
			method += "Via" + goName(binding.Name)
		}
		operationAddress := resolveResourceRef(binding, refString(binding.Spec["operation"]), "operation")
		methods[operationAddress] = append(methods[operationAddress], method)
		httpSpec, _ := binding.Spec["http"].(map[string]any)
		guarantees[binding.Address] = stringValue(httpSpec["guarantee"])
	}
	for operation := range methods {
		sort.Strings(methods[operation])
	}
	gateways := make([]string, 0)
	for _, value := range anyList(target.Spec["gateways"]) {
		gateways = append(gateways, refOrString(value))
	}
	sort.Strings(gateways)
	codecProfiles := typeScriptCodecProfileDigests(bindings)
	profiles := []string{"scenery.http-codec/v1", "scenery.typescript-client/v1"}
	profileDigests := map[string]string{"scenery.http-codec/v1": profileIdentityDigest("scenery.http-codec/v1"), "scenery.typescript-client/v1": profileIdentityDigest("scenery.typescript-client/v1")}
	if bindingsUseHTTPPathTail(bindings) {
		profiles = append(profiles, HTTPPathTailProfile)
		profileDigests[HTTPPathTailProfile] = profileIdentityDigest(HTTPPathTailProfile)
	}
	b, _ := json.MarshalIndent(map[string]any{
		"target": target.Address, "gateways": gateways, "bindings": resourceAddresses(bindings), "resources": resourceAddresses(reachable),
		"contractRevision": manifest.ContractRevision, "typescriptClientRevision": revision,
		"profiles": profiles, "codecProfiles": sortedMapKeys(codecProfiles),
		"profileDigests":       profileDigests,
		"codecProfileDigests":  codecProfiles,
		"compatibilityCatalog": "scenery.compatibility-core/v1", "packageVersionRecommendation": recommendation, "generator": "scenery.vnext.typescript/v1", "sourceEdition": Edition,
		"operationMethods": methods, "guaranteeClassifications": guarantees,
	}, "", "  ")
	return "// Code generated by Scenery vNext. DO NOT EDIT.\nimport { freezeMetadata } from \"./runtime.js\";\nexport const sceneryClientMetadata = freezeMetadata(" + string(b) + " as const);\n"
}

func tsType(value any) string {
	ref := refString(value)
	if ref != "" {
		for _, segment := range []string{"/record/", "/enum/", "/union/"} {
			if index := strings.LastIndex(ref, segment); index >= 0 {
				return goName(ref[index+len(segment):])
			}
		}
		parts := strings.Split(ref, ".")
		if len(parts) >= 2 && (parts[0] == "record" || parts[0] == "enum" || parts[0] == "union") {
			return goName(parts[1])
		}
		if ref == "std.type.problem" {
			return "Problem"
		}
		if ref == "std.type.unit" {
			return "Unit"
		}
		if ref == "std.type.execution_receipt" {
			return "EnqueueReceipt"
		}
		switch ref {
		case "bool":
			return "boolean"
		case "int", "int64", "uint64", "size":
			return "bigint"
		case "int32", "uint32", "float32", "float64":
			return "number"
		case "decimal":
			return "DecimalString"
		case "string":
			return "string"
		case "bytes":
			return "Uint8Array"
		case "uuid":
			return "UUIDString"
		case "date":
			return "DateString"
		case "datetime":
			return "DateTimeString"
		case "duration":
			return "DurationString"
		case "url":
			return "URLString"
		case "relative_path":
			return "RelativePathString"
		case "json":
			return "JsonValue"
		}
	}
	if m, ok := value.(map[string]any); ok {
		if raw, ok := m["$expression"].(string); ok {
			return tsTypeExpression(raw)
		}
	}
	return "unknown"
}
func tsTypeExpression(raw string) string {
	raw = strings.TrimSpace(raw)
	for _, wrapper := range []struct{ prefix, before, after string }{{"optional(", "", ""}, {"nullable(", "", " | null"}, {"list(", "readonly ", "[]"}, {"set(", "readonly ", "[]"}, {"map(", "Readonly<Record<string, ", ">>"}} {
		if strings.HasPrefix(raw, wrapper.prefix) && strings.HasSuffix(raw, ")") {
			inner := tsTypeExpression(strings.TrimSuffix(strings.TrimPrefix(raw, wrapper.prefix), ")"))
			return wrapper.before + inner + wrapper.after
		}
	}
	return tsType(map[string]any{"$ref": raw})
}
func tsOptional(value any) string {
	if m, ok := value.(map[string]any); ok {
		if raw, ok := m["$expression"].(string); ok && strings.HasPrefix(strings.TrimSpace(raw), "optional(") {
			return "?"
		}
	}
	return ""
}
func tsName(value string) string {
	name := goName(value)
	if name == "" {
		return ""
	}
	return strings.ToLower(name[:1]) + name[1:]
}
func lastRef(value string) string {
	value = strings.TrimSpace(value)
	if slash := strings.LastIndex(value, "/"); slash >= 0 {
		value = value[slash+1:]
	}
	parts := strings.Split(value, ".")
	return parts[len(parts)-1]
}
func tsClientType(value any) string {
	typeName := tsType(value)
	if strings.HasPrefix(typeName, "{") || typeName == "unknown" || typeName == "never" {
		return typeName
	}
	return "Types." + typeName
}
func tsRequestBody(httpSpec map[string]any, operation Resource, resources []Resource) (string, string, string) {
	body, _ := httpSpec["body"].(map[string]any)
	if body == nil {
		return "undefined", "", "{} as const"
	}
	codec := stringValue(body["codec"])
	value, descriptor := tsBodyDescriptor(body, operation, resources)
	return value, codec, descriptor
}

func tsInputTargetProperty(value any) string {
	return tsName(lastRef(refOrString(value)))
}

func defaultTSQueryEncoding(value string) string {
	if value == "" {
		return "repeated"
	}
	return value
}

func integerText(value any) string {
	if integer, ok := integerValue(value); ok {
		return strconv.Itoa(integer)
	}
	switch typed := value.(type) {
	case string:
		return typed
	case float64:
		return fmt.Sprintf("%.0f", typed)
	default:
		return "0"
	}
}

func operationVariantType(operation Resource, kind, name string) any {
	for _, variant := range namedChildren(operation.Spec, kind) {
		if variant["name"] == name {
			return variant["type"]
		}
	}
	return nil
}
