package vnext

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func GenerateTypeScriptClients(root, selector string, check bool) (GenerateResult, error) {
	result, err := Compile(root)
	if err != nil {
		return GenerateResult{}, err
	}
	if !result.Valid() {
		return GenerateResult{}, fmt.Errorf("cannot generate from invalid vNext contract")
	}
	targets := typescriptTargets(result.Manifest.Resources, selector)
	if selector != "" && len(targets) == 0 {
		return GenerateResult{}, fmt.Errorf("TypeScript client target %q not found", selector)
	}
	generated := GenerateResult{Changed: []string{}, Checked: []string{}}
	for _, target := range targets {
		files, err := renderTypeScriptTarget(result, target)
		if err != nil {
			return generated, err
		}
		for _, file := range files {
			rel, _ := filepath.Rel(result.Root, file.Path)
			rel = filepath.ToSlash(rel)
			generated.Checked = append(generated.Checked, rel)
			current, readErr := os.ReadFile(file.Path)
			if readErr == nil && string(current) == string(file.Bytes) {
				continue
			}
			generated.Changed = append(generated.Changed, rel)
			if !check {
				if err := atomicWrite(file.Path, file.Bytes); err != nil {
					return generated, err
				}
			}
		}
	}
	sort.Strings(generated.Changed)
	sort.Strings(generated.Checked)
	if check && len(generated.Changed) > 0 {
		return generated, fmt.Errorf("generated vNext TypeScript clients are stale: %s", strings.Join(generated.Changed, ", "))
	}
	return generated, nil
}

func typescriptTargets(resources []Resource, selector string) []Resource {
	var out []Resource
	selector = strings.TrimPrefix(selector, "typescript_client.")
	for _, r := range resources {
		if r.Kind == "scenery.typescript-client/v1" && (selector == "" || r.Name == selector) {
			out = append(out, r)
		}
	}
	return out
}

func renderTypeScriptTarget(result *Result, target Resource) ([]generatedFile, error) {
	outputRoot, ok := target.Spec["output_root"].(string)
	if !ok || outputRoot == "" {
		return nil, fmt.Errorf("TypeScript client %s requires output_root", target.Name)
	}
	root := filepath.Join(result.Root, filepath.FromSlash(outputRoot))
	bindings := publicHTTPBindings(result.Manifest.Resources)
	reachable := reachableResources(result.Manifest.Resources, bindings)
	revision := typescriptRevision(target, reachable)
	selectionBytes, _ := json.MarshalIndent(clientSelectionManifest(result.Manifest.Resources, bindings, revision), "", "  ")
	selectionBytes = append(selectionBytes, '\n')
	files := []generatedFile{{filepath.Join(root, "types.ts"), []byte(renderTSTypes(reachable))}, {filepath.Join(root, "runtime.ts"), []byte(renderTSRuntime())}, {filepath.Join(root, "client.ts"), []byte(renderTSClient(target, bindings, reachable))}, {filepath.Join(root, "metadata.ts"), []byte(renderTSMetadata(target, result.Manifest, bindings, revision))}, {filepath.Join(root, "index.ts"), []byte("// Code generated by Scenery vNext. DO NOT EDIT.\nexport * from \"./client.js\";\nexport * from \"./types.js\";\nexport * from \"./runtime.js\";\nexport * from \"./metadata.js\";\n")}, {filepath.Join(root, "scenery.client-selection.v1.json"), selectionBytes}}
	descriptor := map[string]any{"api_version": "scenery.typescript-client-generated/v1", "target": target.Address, "package": target.Spec["package"], "contract_revision": result.Manifest.ContractRevision, "typescript_client_revision": revision, "content_digest": artifactDigest(root, files), "profile": "scenery.typescript-client/v1", "codec_profiles": []string{"scenery.http-codec/v1"}, "covered_bindings": resourceAddresses(bindings), "generator": "scenery.vnext.typescript/v1"}
	b, _ := json.MarshalIndent(descriptor, "", "  ")
	files = append(files, generatedFile{filepath.Join(root, "scenery.typescript-client-generated.v1.json"), append(b, '\n')})
	return files, nil
}

func publicHTTPBindings(resources []Resource) []Resource {
	var out []Resource
	operations := map[string]Resource{}
	for _, resource := range resources {
		if resource.Kind == "scenery.operation/v1" {
			operations[resource.Address] = resource
			operations[resource.Module+"/operation/"+resource.Name] = resource
		}
	}
	for _, r := range resources {
		if r.Kind != "scenery.binding/v1" {
			continue
		}
		if r.Origin.Kind != "authored" {
			continue
		}
		opRef := refString(r.Spec["operation"])
		op := operations[opRef]
		if op.Address == "" {
			op = operations[r.Module+"/operation/"+lastRef(opRef)]
		}
		handler, _ := op.Spec["handler"].(map[string]any)
		if adapter, _ := handler["adapter"].(string); adapter == "legacy_go_v0" {
			continue
		}
		if protocol, _ := r.Spec["protocol"].(string); protocol != "http" {
			continue
		}
		httpSpec, _ := r.Spec["http"].(map[string]any)
		if httpSpec == nil {
			continue
		}
		out = append(out, r)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Address < out[j].Address })
	return out
}

func clientSelectionManifest(resources, nativeBindings []Resource, revision string) map[string]any {
	native := map[string]bool{}
	for _, binding := range nativeBindings {
		native[binding.Address] = true
	}
	selection := map[string]any{}
	for _, binding := range resources {
		if binding.Kind != "scenery.binding/v1" {
			continue
		}
		if httpSpec, _ := binding.Spec["http"].(map[string]any); httpSpec == nil {
			continue
		}
		family, bindingRevision := "legacy_v0", "scenery.legacy.v0"
		if native[binding.Address] {
			family, bindingRevision = "native", revision
		}
		selection[binding.Address] = map[string]any{"family": family, "revision": bindingRevision}
	}
	return map[string]any{"api_version": "scenery.client-selection.v1", "operations": selection}
}
func reachableResources(resources, bindings []Resource) []Resource {
	modules := map[string]bool{}
	operations := map[string]bool{}
	for _, b := range bindings {
		modules[b.Module] = true
		operations[b.Module+"/operation/"+lastRef(refString(b.Spec["operation"]))] = true
	}
	var out []Resource
	for _, r := range resources {
		if modules[r.Module] && (r.Kind == "scenery.record/v1" || r.Kind == "scenery.enum/v1" || r.Kind == "scenery.union/v1" || (r.Kind == "scenery.operation/v1" && operations[r.Address])) {
			out = append(out, r)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Address < out[j].Address })
	return out
}
func typescriptRevision(target Resource, resources []Resource) string {
	b, _ := json.Marshal(map[string]any{"target": target, "resources": resources, "profile": "scenery.typescript-client/v1"})
	sum := sha256.Sum256(append([]byte("scenery.typescript-client-revision.v1\x00"), b...))
	return "sha256:" + hex.EncodeToString(sum[:])
}

func renderTSTypes(resources []Resource) string {
	var b strings.Builder
	b.WriteString("// Code generated by Scenery vNext. DO NOT EDIT.\n\nexport type JsonValue = null | boolean | string | JsonNumber | readonly JsonValue[] | { readonly [key: string]: JsonValue };\nexport interface JsonNumber { readonly coefficient: string; readonly scale: number }\nexport type UUIDString = string & { readonly __uuid: unique symbol };\nexport type DateString = string & { readonly __date: unique symbol };\nexport type DateTimeString = string & { readonly __datetime: unique symbol };\nexport type DurationString = string & { readonly __duration: unique symbol };\nexport type DecimalString = string & { readonly __decimal: unique symbol };\nexport type URLString = string & { readonly __url: unique symbol };\nexport type RelativePathString = string & { readonly __relativePath: unique symbol };\n\n")
	for _, r := range resources {
		switch r.Kind {
		case "scenery.record/v1":
			fmt.Fprintf(&b, "export interface %s {\n", goName(r.Name))
			for _, field := range namedChildren(r.Spec, "field") {
				name, _ := field["name"].(string)
				optional := tsOptional(field["type"])
				fmt.Fprintf(&b, "  readonly %s%s: %s;\n", tsName(name), optional, tsType(field["type"]))
			}
			b.WriteString("}\n\n")
		case "scenery.enum/v1":
			fmt.Fprintf(&b, "export type %s = ", goName(r.Name))
			values := namedChildren(r.Spec, "value")
			for i, v := range values {
				if i > 0 {
					b.WriteString(" | ")
				}
				name, _ := v["name"].(string)
				fmt.Fprintf(&b, "%q", name)
			}
			b.WriteString(";\n\n")
		}
	}
	for _, r := range resources {
		if r.Kind != "scenery.operation/v1" {
			continue
		}
		name := goName(r.Name)
		inputType := tsType(r.Spec["input"])
		if inputType != name+"Input" {
			fmt.Fprintf(&b, "export type %sInput = %s;\n\n", name, inputType)
		}
		fmt.Fprintf(&b, "export type %sOutcome =\n", name)
		variants := append(namedChildren(r.Spec, "result"), namedChildren(r.Spec, "error")...)
		if len(variants) == 0 {
			b.WriteString("  never\n")
		}
		for i, v := range variants {
			variant, _ := v["name"].(string)
			kind := "result"
			field := "value"
			if i >= len(namedChildren(r.Spec, "result")) {
				kind = "error"
				field = "problem"
			}
			fmt.Fprintf(&b, "  | { readonly kind: %q; readonly name: %q; readonly %s: %s }\n", kind, variant, field, tsType(v["type"]))
		}
		b.WriteString(";\n\n")
	}
	return b.String()
}

func renderTSRuntime() string {
	return `// Code generated by Scenery vNext. DO NOT EDIT.
export class SceneryClientError extends Error {
  constructor(readonly code: string, readonly bindingAddress: string, message: string, readonly cause?: unknown) { super(message); this.name = "SceneryClientError"; }
}
export interface CallOptions { readonly signal?: AbortSignal; readonly headers?: Readonly<Record<string, string>> }
`
}

func renderTSClient(target Resource, bindings, resources []Resource) string {
	className := goName(target.Name) + "Client"
	var b strings.Builder
	b.WriteString("// Code generated by Scenery vNext. DO NOT EDIT.\nimport { SceneryClientError, type CallOptions } from \"./runtime.js\";\nimport type * as Types from \"./types.js\";\n\nexport interface " + className + "Options { readonly baseUrl: string; readonly fetch?: typeof globalThis.fetch; readonly defaultHeaders?: Readonly<Record<string,string>> }\n\nexport class " + className + " {\n  readonly #baseUrl: string; readonly #fetch: typeof globalThis.fetch; readonly #headers: Readonly<Record<string,string>>;\n  constructor(options: " + className + "Options) { this.#baseUrl=options.baseUrl.replace(/\\/$/, \"\"); this.#fetch=options.fetch ?? globalThis.fetch; this.#headers=Object.freeze({...(options.defaultHeaders ?? {})}); }\n")
	ops := map[string]Resource{}
	for _, r := range resources {
		if r.Kind == "scenery.operation/v1" {
			ops[r.Name] = r
		}
	}
	for _, binding := range bindings {
		opRef := refString(binding.Spec["operation"])
		opName := lastRef(opRef)
		op := ops[opName]
		methodName := tsName(opName)
		httpSpec, _ := binding.Spec["http"].(map[string]any)
		method, _ := httpSpec["method"].(string)
		path, _ := httpSpec["path"].(string)
		fmt.Fprintf(&b, "  async %s(input: Types.%sInput, options: CallOptions = {}): Promise<Types.%sOutcome> {\n", methodName, goName(opName), goName(opName))
		fmt.Fprintf(&b, "    const binding = %q; if (options.signal?.aborted) throw new SceneryClientError(\"cancelled\", binding, \"request cancelled\");\n", binding.Address)
		fmt.Fprintf(&b, "    let path = %q; path = path.replace(/\\{([a-z0-9_]+)\\}/g, (_, key: string) => encodeURIComponent(String((input as unknown as Record<string, unknown>)[key])));\n", path)
		fmt.Fprintf(&b, "    let response: Response; try { response = await this.#fetch(this.#baseUrl + path, { method: %q, signal: options.signal, headers: { ...this.#headers, ...options.headers, \"content-type\": \"application/json\" }, body: %s }); } catch (cause) { throw new SceneryClientError(options.signal?.aborted ? \"cancelled\" : \"network\", binding, \"request failed\", cause); }\n", method, tsRequestBody(method))
		b.WriteString("    const payload = await response.json().catch(() => undefined) as unknown;\n")
		results := namedChildren(op.Spec, "result")
		errors := namedChildren(op.Spec, "error")
		for _, v := range results {
			name, _ := v["name"].(string)
			fmt.Fprintf(&b, "    if (response.ok) return { kind: \"result\", name: %q, value: payload as %s } as Types.%sOutcome;\n", name, tsClientType(v["type"]), goName(opName))
		}
		for _, v := range errors {
			name, _ := v["name"].(string)
			fmt.Fprintf(&b, "    if (response.status >= 400 && response.status < 500) return { kind: \"error\", name: %q, problem: payload as %s } as Types.%sOutcome;\n", name, tsClientType(v["type"]), goName(opName))
		}
		b.WriteString("    throw new SceneryClientError(\"contract_violation\", binding, `unexpected response ${response.status}`);\n  }\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func renderTSMetadata(target Resource, manifest *Manifest, bindings []Resource, revision string) string {
	methods := map[string]string{}
	for _, binding := range bindings {
		methods[binding.Address] = tsName(lastRef(refString(binding.Spec["operation"])))
	}
	b, _ := json.MarshalIndent(map[string]any{"target": target.Address, "contractRevision": manifest.ContractRevision, "typescriptClientRevision": revision, "profiles": []string{"scenery.typescript-client/v1", "scenery.http-codec/v1"}, "operationMethods": methods}, "", "  ")
	return "// Code generated by Scenery vNext. DO NOT EDIT.\nexport const sceneryClientMetadata = Object.freeze(" + string(b) + " as const);\n"
}

func tsType(value any) string {
	ref := refString(value)
	if ref != "" {
		parts := strings.Split(ref, ".")
		if len(parts) >= 2 && (parts[0] == "record" || parts[0] == "enum" || parts[0] == "union") {
			return goName(parts[1])
		}
		if strings.HasSuffix(ref, ".problem") {
			return "{ readonly code: string; readonly message: string; readonly path?: string }"
		}
		switch ref {
		case "bool":
			return "boolean"
		case "int", "int64", "uint64", "size":
			return "bigint"
		case "int32", "uint32", "float32", "float64":
			return "number"
		case "decimal":
			return "DecimalString"
		case "string":
			return "string"
		case "bytes":
			return "Uint8Array"
		case "uuid":
			return "UUIDString"
		case "date":
			return "DateString"
		case "datetime":
			return "DateTimeString"
		case "duration":
			return "DurationString"
		case "url":
			return "URLString"
		case "relative_path":
			return "RelativePathString"
		case "json":
			return "JsonValue"
		}
	}
	if m, ok := value.(map[string]any); ok {
		if raw, ok := m["$expression"].(string); ok {
			return tsTypeExpression(raw)
		}
	}
	return "unknown"
}
func tsTypeExpression(raw string) string {
	raw = strings.TrimSpace(raw)
	for _, wrapper := range []struct{ prefix, before, after string }{{"optional(", "", ""}, {"nullable(", "", " | null"}, {"list(", "readonly ", "[]"}, {"set(", "readonly ", "[]"}, {"map(", "Readonly<Record<string, ", ">>"}} {
		if strings.HasPrefix(raw, wrapper.prefix) && strings.HasSuffix(raw, ")") {
			inner := tsTypeExpression(strings.TrimSuffix(strings.TrimPrefix(raw, wrapper.prefix), ")"))
			return wrapper.before + inner + wrapper.after
		}
	}
	return tsType(map[string]any{"$ref": raw})
}
func tsOptional(value any) string {
	if m, ok := value.(map[string]any); ok {
		if raw, ok := m["$expression"].(string); ok && strings.HasPrefix(strings.TrimSpace(raw), "optional(") {
			return "?"
		}
	}
	return ""
}
func tsName(value string) string {
	name := goName(value)
	if name == "" {
		return ""
	}
	return strings.ToLower(name[:1]) + name[1:]
}
func lastRef(value string) string {
	value = strings.TrimSpace(value)
	if slash := strings.LastIndex(value, "/"); slash >= 0 {
		value = value[slash+1:]
	}
	parts := strings.Split(value, ".")
	return parts[len(parts)-1]
}
func tsClientType(value any) string {
	typeName := tsType(value)
	if strings.HasPrefix(typeName, "{") || typeName == "unknown" || typeName == "never" {
		return typeName
	}
	return "Types." + typeName
}
func tsRequestBody(method string) string {
	switch strings.ToUpper(method) {
	case "GET", "HEAD":
		return "undefined"
	default:
		return "JSON.stringify(input)"
	}
}
