// Code generated by Scenery. DO NOT EDIT.
package composition

import (
	adapter0 "example.test/nativeapp/internal/scenerygen/house_house_adapter"
	scenery "scenery.sh"
)

const ContractRevision = "sha256:1fd62db00ac84b74cc80b7a04e0bae8975bd97e79d44662b85a110169b0347de"

var RequiredAddresses = []string{"house/binding/process_scene_http", "house/binding/process_scene_internal", "house/execution/process_scene_direct", "house/operation/process_scene", "house/service/house"}

var RequiredProviderABIs = map[string]string{}

func Register(registry scenery.Registry) error {
	if err := adapter0.Register(registry); err != nil {
		return err
	}
	return nil
}
