package schemagen

import (
	"bytes"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"scenery.sh/internal/model"
)

type ServiceSeed struct {
	Service       string
	GeneratedPath string
	SQL           string
	Entities      []string
}

func BuildSeeds(appRoot string, app *model.App) ([]ServiceSeed, error) {
	_ = appRoot
	if app == nil || len(app.Entities) == 0 {
		return nil, nil
	}
	byService := make(map[string][]*model.Entity)
	for _, entity := range app.Entities {
		if entity == nil || len(entity.Seeds) == 0 {
			continue
		}
		byService[entityService(entity)] = append(byService[entityService(entity)], entity)
	}
	services := make([]string, 0, len(byService))
	for service := range byService {
		services = append(services, service)
	}
	sort.Strings(services)
	out := make([]ServiceSeed, 0, len(services))
	for _, service := range services {
		entities := byService[service]
		sort.Slice(entities, func(i, j int) bool {
			if entities[i].Table != entities[j].Table {
				return entities[i].Table < entities[j].Table
			}
			return entities[i].Name < entities[j].Name
		})
		names := make([]string, 0, len(entities))
		for _, entity := range entities {
			names = append(names, entity.Name)
		}
		sql, err := renderServiceSeedSQL(entities)
		if err != nil {
			return nil, err
		}
		out = append(out, ServiceSeed{
			Service:       service,
			GeneratedPath: filepath.ToSlash(filepath.Join(".scenery", "gen", "db", service, "seed.sql")),
			SQL:           sql,
			Entities:      names,
		})
	}
	return out, nil
}

func renderServiceSeedSQL(entities []*model.Entity) (string, error) {
	var b bytes.Buffer
	b.WriteString("-- Code generated by scenery generate data; DO NOT EDIT.\n\n")
	for _, entity := range entities {
		pk := primaryKeyField(entity)
		if pk == nil {
			return "", fmt.Errorf("model %s needs an ID field before seed SQL can be generated", entity.Name)
		}
		fields := generatedSeedFields(entity)
		for _, row := range entity.Seeds {
			values := make(map[string]model.EntitySeedValue, len(row.Values))
			for _, value := range row.Values {
				values[value.Field] = value
			}
			columns := make([]model.EntityField, 0, len(row.Values))
			for _, field := range fields {
				if _, ok := values[field.Name]; ok {
					columns = append(columns, field)
				}
			}
			if len(columns) == 0 {
				continue
			}
			fmt.Fprintf(&b, "insert into %s (", quoteSQLIdent(entity.Table))
			for i, field := range columns {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(quoteSQLIdent(field.Column))
			}
			b.WriteString(")\nvalues (")
			for i, field := range columns {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(seedSQLLiteral(values[field.Name]))
			}
			fmt.Fprintf(&b, ")\non conflict (%s) ", quoteSQLIdent(pk.Column))
			var updates []string
			for _, field := range columns {
				if strings.EqualFold(field.Name, pk.Name) {
					continue
				}
				updates = append(updates, fmt.Sprintf("%s = excluded.%s", quoteSQLIdent(field.Column), quoteSQLIdent(field.Column)))
			}
			if len(updates) == 0 {
				b.WriteString("do nothing")
			} else {
				b.WriteString("do update set\n  ")
				b.WriteString(strings.Join(updates, ",\n  "))
			}
			b.WriteString(";\n\n")
		}
	}
	return b.String(), nil
}

func generatedSeedFields(entity *model.Entity) []model.EntityField {
	var fields []model.EntityField
	for _, field := range entity.Fields {
		if field.Kind != model.EntityFieldComputed {
			fields = append(fields, field)
		}
	}
	return fields
}

func seedSQLLiteral(value model.EntitySeedValue) string {
	switch value.Kind {
	case model.EntitySeedString:
		return "'" + strings.ReplaceAll(value.Value, "'", "''") + "'"
	case model.EntitySeedInteger, model.EntitySeedFloat:
		return value.Value
	case model.EntitySeedBool:
		if strings.EqualFold(value.Value, "true") {
			return "true"
		}
		return "false"
	case model.EntitySeedTimestamp:
		return "'" + strings.ReplaceAll(value.Value, "'", "''") + "'::timestamptz"
	default:
		return "null"
	}
}

func quoteSQLIdent(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `""`) + `"`
}
