package codegen

import (
	"fmt"
	"go/format"
	"go/types"
	"path/filepath"
	"reflect"
	"slices"
	"strings"

	"scenery.sh/internal/model"
)

// GenerateVNextBridgeFiles renders committed compatibility helpers for the
// explicitly selected native-contract/legacy-handler services.
func GenerateVNextBridgeFiles(app *model.App, services map[string]bool) (map[string][]byte, error) {
	result := map[string][]byte{}
	if app == nil {
		return result, nil
	}
	for _, pkg := range app.Packages {
		if pkg.Service == nil || !services[pkg.Service.Name] {
			continue
		}
		data, err := generateVNextBridgePackageFile(pkg)
		if err != nil {
			return nil, err
		}
		if len(data) == 0 {
			continue
		}
		relative := filepath.ToSlash(filepath.Join(pkg.RelDir, "scenery.bridge.gen.go"))
		if pkg.RelDir == "." {
			relative = "scenery.bridge.gen.go"
		}
		result[relative] = data
	}
	return result, nil
}

// generateVNextBridgePackageFile keeps the frozen legacy Go signatures behind
// an explicit byte boundary while the edition-2027 adapter owns routing,
// policy, outcomes, and registration. It deliberately emits no init function
// and no legacy endpoint registration.
func generateVNextBridgePackageFile(pkg *model.Package) ([]byte, error) {
	if pkg == nil || pkg.Service == nil {
		return nil, nil
	}
	var endpoints []*model.Endpoint
	for _, endpoint := range pkg.Service.Endpoints {
		if endpoint.Package == pkg {
			endpoints = append(endpoints, endpoint)
		}
	}
	slices.SortFunc(endpoints, func(left, right *model.Endpoint) int { return strings.Compare(left.Name, right.Name) })
	isRoot := pkg.Service.RootPackage == pkg
	if len(endpoints) == 0 && !isRoot {
		return nil, nil
	}

	imports := newImports(pkg.ImportPath)
	imports.use("context", "context")
	if len(endpoints) > 0 {
		imports.use("json", "encoding/json")
		imports.use("fmt", "fmt")
	}
	var source strings.Builder
	fmt.Fprintf(&source, "package %s\n\n", pkg.Name)
	if isRoot {
		writeVNextBridgeLifecycle(&source, imports, pkg.Service.Struct)
	}
	for _, endpoint := range endpoints {
		if endpoint.Raw {
			return nil, fmt.Errorf("vNext legacy Go bridge does not support raw endpoint %s.%s", endpoint.Service.Name, endpoint.Name)
		}
		writeVNextBridgeEndpoint(&source, imports, endpoint, pkg.Service.Struct)
		writeVNextLegacyCallEndpoint(&source, imports, endpoint)
	}
	writeImports(&source, imports)
	formatted, err := format.Source([]byte("// Code generated by Scenery vNext. DO NOT EDIT.\n\n" + source.String()))
	if err != nil {
		return nil, fmt.Errorf("format vNext legacy bridge for %s: %w\n%s", pkg.ImportPath, err, source.String())
	}
	return formatted, nil
}

// writeVNextLegacyCallEndpoint keeps already-generated v0 Go callers working
// after ownership moves to a native contract adapter. The runtime facade owns
// invocation; these helpers only translate the frozen Go signature at an
// explicit JSON boundary and never register an endpoint themselves.
func writeVNextLegacyCallEndpoint(source *strings.Builder, imports *imports, endpoint *model.Endpoint) {
	imports.use("json", "encoding/json")
	imports.use("fmt", "fmt")
	imports.use("scenery", "scenery.sh")
	name := endpoint.Name
	fmt.Fprintf(source, "func SceneryVNextLegacyCall%sInput(pathArgs []any, payload any) ([]byte, error) {\n", name)
	fmt.Fprintf(source, "\tif len(pathArgs) != %d { return nil, fmt.Errorf(\"legacy call %s requires %d path arguments, got %%d\", len(pathArgs)) }\n", len(endpoint.PathParams), name, len(endpoint.PathParams))
	source.WriteString("\tobject := map[string]any{}\n")
	for index, parameter := range endpoint.PathParams {
		fmt.Fprintf(source, "\tobject[%q] = pathArgs[%d]\n", parameter.Name, index)
	}
	if endpoint.Payload != nil {
		source.WriteString("\tpayloadRaw, err := json.Marshal(payload)\n\tif err != nil { return nil, fmt.Errorf(\"encode legacy call payload: %w\", err) }\n")
		if mappings, ok := vnextBridgePayloadMappings(endpoint.Payload.Type); ok {
			source.WriteString("\tvar payloadObject map[string]json.RawMessage\n\tif err := json.Unmarshal(payloadRaw, &payloadObject); err != nil { return nil, fmt.Errorf(\"decode legacy call payload: %w\", err) }\n")
			for _, mapping := range mappings {
				fmt.Fprintf(source, "\tif raw, ok := payloadObject[%q]; ok { object[%q] = raw }\n", mapping.PayloadWire, mapping.ContractWire)
			}
		} else {
			source.WriteString("\tobject[\"payload\"] = json.RawMessage(payloadRaw)\n")
		}
	}
	source.WriteString("\treturn json.Marshal(object)\n}\n\n")

	fmt.Fprintf(source, "func SceneryVNextLegacyCall%sOutput(data []byte) (any, error) {\n", name)
	source.WriteString("\tkind, outcome, payload, err := scenery.DecodeContractOutcomeEnvelope(data)\n\tif err != nil { return nil, fmt.Errorf(\"decode native outcome: %w\", err) }\n")
	source.WriteString("\tif kind != \"result\" {\n\t\tvar problem scenery.Problem\n\t\tif err := json.Unmarshal(payload, &problem); err != nil { return nil, fmt.Errorf(\"native %s outcome: %s\", kind, outcome) }\n\t\treturn nil, fmt.Errorf(\"%s: %s\", problem.Code, problem.Message)\n\t}\n")
	if endpoint.Response == nil {
		source.WriteString("\treturn nil, nil\n}\n\n")
		return
	}
	responseType := imports.typeExpr(endpoint.Response.Type)
	fmt.Fprintf(source, "\tvar response %s\n", responseType)
	source.WriteString("\tif err := json.Unmarshal(payload, &response); err != nil { return nil, fmt.Errorf(\"decode native result %s: %w\", outcome, err) }\n\treturn response, nil\n}\n\n")
}

func writeVNextBridgeLifecycle(source *strings.Builder, imports *imports, service *model.ServiceStruct) {
	if service == nil {
		source.WriteString("func SceneryVNextBridgeInitialize() error { return nil }\n")
		source.WriteString("func SceneryVNextBridgeService() (any, error) { return struct{}{}, nil }\n")
		source.WriteString("func SceneryVNextBridgeShutdown(context.Context) {}\n\n")
		return
	}
	imports.use("sync", "sync")
	fmt.Fprintf(source, "var sceneryVNextBridgeState struct {\n\tonce sync.Once\n\tservice *%s\n\terr error\n}\n\n", service.TypeName)
	fmt.Fprintf(source, "func SceneryVNextBridgeInitialize() error {\n\tsceneryVNextBridgeState.once.Do(func() {\n")
	if service.InitFunc != "" {
		fmt.Fprintf(source, "\t\tsceneryVNextBridgeState.service, sceneryVNextBridgeState.err = %s()\n", service.InitFunc)
	} else {
		fmt.Fprintf(source, "\t\tsceneryVNextBridgeState.service = &%s{}\n", service.TypeName)
	}
	source.WriteString("\t})\n\treturn sceneryVNextBridgeState.err\n}\n\n")
	fmt.Fprintf(source, "func sceneryVNextBridgeService() (*%s, error) {\n\tif err := SceneryVNextBridgeInitialize(); err != nil { return nil, err }\n\treturn sceneryVNextBridgeState.service, nil\n}\n\n", service.TypeName)
	source.WriteString("func SceneryVNextBridgeService() (any, error) { return sceneryVNextBridgeService() }\n\n")
	source.WriteString("func SceneryVNextBridgeShutdown(ctx context.Context) {\n")
	if service.Shutdown != "" {
		fmt.Fprintf(source, "\tif sceneryVNextBridgeState.service != nil { sceneryVNextBridgeState.service.%s(ctx) }\n", service.Shutdown)
	} else {
		source.WriteString("\t_ = ctx\n")
	}
	source.WriteString("}\n\n")
}

func writeVNextBridgeEndpoint(source *strings.Builder, imports *imports, endpoint *model.Endpoint, service *model.ServiceStruct) {
	if endpoint.Receiver != nil {
		fmt.Fprintf(source, "func SceneryVNextBridge%s(ctx context.Context, input []byte) ([]byte, error) {\n\tservice, err := sceneryVNextBridgeService()\n\tif err != nil { return nil, err }\n\treturn SceneryVNextBridge%sWithService(ctx, service, input)\n}\n\n", endpoint.Name, endpoint.Name)
		fmt.Fprintf(source, "func SceneryVNextBridge%sWithService(ctx context.Context, receiver any, input []byte) ([]byte, error) {\n\tservice, ok := receiver.(*%s)\n\tif !ok { return nil, fmt.Errorf(\"legacy bridge receiver has type %%T, want *%s\", receiver) }\n", endpoint.Name, endpoint.Receiver.TypeName, endpoint.Receiver.TypeName)
	} else {
		fmt.Fprintf(source, "func SceneryVNextBridge%s(ctx context.Context, input []byte) ([]byte, error) {\n", endpoint.Name)
	}
	needsObject := len(endpoint.PathParams) > 0 || endpoint.Payload != nil
	if needsObject {
		source.WriteString("\tvar object map[string]json.RawMessage\n\tif err := json.Unmarshal(input, &object); err != nil { return nil, fmt.Errorf(\"decode bridge input: %w\", err) }\n")
	}
	arguments := []string{"ctx"}
	for index, parameter := range endpoint.PathParams {
		if index+1 >= len(endpoint.Params) {
			continue
		}
		variable := fmt.Sprintf("pathValue%d", index)
		typeName := imports.typeExpr(endpoint.Params[index+1].Type)
		fmt.Fprintf(source, "\tvar %s %s\n", variable, typeName)
		fmt.Fprintf(source, "\tif raw, ok := object[%q]; !ok { return nil, fmt.Errorf(\"missing bridge path field %s\") } else if err := json.Unmarshal(raw, &%s); err != nil { return nil, fmt.Errorf(\"decode bridge path field %s: %%w\", err) }\n", parameter.Name, parameter.Name, variable, parameter.Name)
		arguments = append(arguments, variable)
	}
	if endpoint.Payload != nil {
		payloadType := imports.typeExpr(endpoint.Payload.Type)
		source.WriteString("\tpayloadRaw := input\n")
		if mappings, ok := vnextBridgePayloadMappings(endpoint.Payload.Type); ok {
			source.WriteString("\tpayloadObject := map[string]json.RawMessage{}\n")
			for _, mapping := range mappings {
				fmt.Fprintf(source, "\tif raw, ok := object[%q]; ok { payloadObject[%q] = raw }\n", mapping.ContractWire, mapping.PayloadWire)
			}
			source.WriteString("\tvar err error\n\tpayloadRaw, err = json.Marshal(payloadObject)\n\tif err != nil { return nil, fmt.Errorf(\"encode bridge payload: %w\", err) }\n")
		} else {
			source.WriteString("\tvar ok bool\n\tpayloadRaw, ok = object[\"payload\"]\n\tif !ok { return nil, fmt.Errorf(\"missing bridge payload field\") }\n")
		}
		fmt.Fprintf(source, "\tvar payload %s\n\tif err := json.Unmarshal(payloadRaw, &payload); err != nil { return nil, fmt.Errorf(\"decode bridge payload: %%w\", err) }\n", payloadType)
		arguments = append(arguments, "payload")
	}

	callTarget := endpoint.Name
	if endpoint.Receiver != nil {
		callTarget = "service." + endpoint.Name
	} else if service != nil && endpoint.Package == service.Package {
		// The package-level handler intentionally remains a package function.
		_ = service
	}
	call := callTarget + "(" + strings.Join(arguments, ", ") + ")"
	if endpoint.Response == nil {
		fmt.Fprintf(source, "\tif err := %s; err != nil { return nil, err }\n\treturn []byte(\"{}\"), nil\n", call)
	} else {
		fmt.Fprintf(source, "\tresponse, err := %s\n\tif err != nil { return nil, err }\n", call)
		if vnextBridgeStruct(endpoint.Response.Type) != nil {
			source.WriteString("\treturn json.Marshal(response)\n")
		} else {
			source.WriteString("\traw, err := json.Marshal(response)\n\tif err != nil { return nil, err }\n\treturn json.Marshal(map[string]json.RawMessage{\"value\": raw})\n")
		}
	}
	source.WriteString("}\n\n")
	if endpoint.Receiver == nil {
		fmt.Fprintf(source, "func SceneryVNextBridge%sWithService(ctx context.Context, _ any, input []byte) ([]byte, error) { return SceneryVNextBridge%s(ctx, input) }\n\n", endpoint.Name, endpoint.Name)
	}
}

type vnextBridgeFieldMapping struct {
	ContractWire string
	PayloadWire  string
}

func vnextBridgePayloadMappings(value types.Type) ([]vnextBridgeFieldMapping, bool) {
	structure := vnextBridgeStruct(value)
	if structure == nil {
		return nil, false
	}
	result := make([]vnextBridgeFieldMapping, 0, structure.NumFields())
	for index := 0; index < structure.NumFields(); index++ {
		field := structure.Field(index)
		if !field.Exported() {
			continue
		}
		tag := reflect.StructTag(structure.Tag(index))
		payloadWire := vnextBridgeTagName(tag.Get("json"))
		if payloadWire == "-" {
			continue
		}
		if payloadWire == "" {
			payloadWire = field.Name()
		}
		contractWire := payloadWire
		for _, key := range []string{"query", "qs", "header", "cookie"} {
			if candidate := vnextBridgeTagName(tag.Get(key)); candidate != "" {
				contractWire = candidate
				if key == "header" {
					contractWire = strings.ToLower(contractWire)
				}
				break
			}
		}
		result = append(result, vnextBridgeFieldMapping{ContractWire: contractWire, PayloadWire: payloadWire})
	}
	return result, true
}

func vnextBridgeStruct(value types.Type) *types.Struct {
	for {
		value = types.Unalias(value)
		pointer, ok := value.(*types.Pointer)
		if !ok {
			break
		}
		value = pointer.Elem()
	}
	if named, ok := value.(*types.Named); ok {
		value = named.Underlying()
	}
	structure, _ := value.(*types.Struct)
	return structure
}

func vnextBridgeTagName(value string) string {
	return strings.TrimSpace(strings.Split(value, ",")[0])
}
