// Code generated by Scenery vNext. DO NOT EDIT.
package scenerycontract

import (
	"encoding/json"
	"fmt"
	scenery "scenery.sh"
)

var _ = scenery.Problem{}

type EchoInput struct {
	Message string `json:"message"`
}

func (value EchoInput) MarshalJSON() ([]byte, error) {
	if err := value.Validate(); err != nil {
		return nil, err
	}
	object := map[string]json.RawMessage{}
	rawMessage, err := scenery.MarshalContractValue(value.Message, "string")
	if err != nil {
		return nil, fmt.Errorf("encode field message: %w", err)
	}
	object["message"] = rawMessage
	encoded, err := json.Marshal(object)
	if err != nil {
		return nil, err
	}
	return scenery.MarshalContractValue(scenery.JSON(encoded), "json")
}

func (value *EchoInput) UnmarshalJSON(data []byte) error {
	object, err := scenery.DecodeJSONObject(data)
	if err != nil {
		return err
	}
	*value = EchoInput{}
	rawMessage, exists := object["message"]
	if !exists {
		return fmt.Errorf("missing required field message")
	}
	if err := unmarshalGeneratedContractValue(rawMessage, &value.Message, "string"); err != nil {
		return fmt.Errorf("decode field message: %w", err)
	}
	delete(object, "message")
	for key := range object {
		return fmt.Errorf("unknown field %q", key)
	}
	return value.Validate()
}

func (value EchoInput) Validate() error {
	if err := scenery.ValidateContractValue(value.Message, "string", scenery.ContractConstraints{}); err != nil {
		return fmt.Errorf("validate field message: %w", err)
	}
	return nil
}

type EchoResult struct {
	Message string `json:"message"`
}

func (value EchoResult) MarshalJSON() ([]byte, error) {
	if err := value.Validate(); err != nil {
		return nil, err
	}
	object := map[string]json.RawMessage{}
	rawMessage, err := scenery.MarshalContractValue(value.Message, "string")
	if err != nil {
		return nil, fmt.Errorf("encode field message: %w", err)
	}
	object["message"] = rawMessage
	encoded, err := json.Marshal(object)
	if err != nil {
		return nil, err
	}
	return scenery.MarshalContractValue(scenery.JSON(encoded), "json")
}

func (value *EchoResult) UnmarshalJSON(data []byte) error {
	object, err := scenery.DecodeJSONObject(data)
	if err != nil {
		return err
	}
	*value = EchoResult{}
	rawMessage, exists := object["message"]
	if !exists {
		return fmt.Errorf("missing required field message")
	}
	if err := unmarshalGeneratedContractValue(rawMessage, &value.Message, "string"); err != nil {
		return fmt.Errorf("decode field message: %w", err)
	}
	delete(object, "message")
	for key := range object {
		return fmt.Errorf("unknown field %q", key)
	}
	return value.Validate()
}

func (value EchoResult) Validate() error {
	if err := scenery.ValidateContractValue(value.Message, "string", scenery.ContractConstraints{}); err != nil {
		return fmt.Errorf("validate field message: %w", err)
	}
	return nil
}

func unmarshalGeneratedContractValue(data []byte, target any, typeExpression string) error {
	return scenery.UnmarshalContractValue(data, target, typeExpression)
}
