// Package eve contains the developer-only adapter for the pinned Eve
// filesystem runtime.  The package deliberately exposes only provider-neutral
// values: callers exchange overlays, assertions, and assistantcontrol events;
// no Eve types escape this package.
package eve

import (
	"bytes"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"

	"scenery.sh/internal/assistantcontrol"
	"scenery.sh/internal/mcpcontract"
)

const (
	// EveVersion and NodeVersion are implementation identities.  They are
	// intentionally kept below this developer-only package and are not part of
	// the public assistant contract.
	EveVersion  = "0.29.5"
	NodeVersion = "24.18.0"

	controlHeader = "x-scenery-assistant-control-token"

	defaultAssertionTTL = 30 * time.Second
	maxAssertionTTL     = 2 * time.Minute
)

// ReservedPaths are generated by Scenery and can never be authored. Paths use
// slash separators regardless of the host platform.
var reservedPaths = [...]string{
	"agent/channels/scenery.ts",
	"agent/connections/scenery.ts",
	".scenery/bootstrap.mjs",
	".scenery/runtime-manifest.json",
}

// OverlayRequest describes one transient provider workspace. SourceRoot is
// read-only; OverlayRoot must be a new directory. The generated MCP URL must
// be a loopback URL. Secrets are read by generated code from the helper process
// environment and never written to the overlay.
type OverlayRequest struct {
	SourceRoot         string
	OverlayRoot        string
	AssistantAddress   string
	RuntimeRevision    string
	CapabilityRevision string
	ApprovalNeverTools []string
	ControlURL         string
	MCPURL             string
}

// Overlay identifies the generated files and their deterministic digests.
type Overlay struct {
	Root              string
	ChannelPath       string
	ConnectionPath    string
	BootstrapPath     string
	ManifestPath      string
	PackageLockDigest string
	ManifestDigest    string
}

// MaterializeOverlay copies authored files to a transient workspace and then
// writes the four reserved generated files. It never changes SourceRoot.
func MaterializeOverlay(request OverlayRequest) (Overlay, error) {
	request.SourceRoot = filepath.Clean(request.SourceRoot)
	request.OverlayRoot = filepath.Clean(request.OverlayRoot)
	if request.SourceRoot == "." || request.OverlayRoot == "." || isFilesystemRoot(request.OverlayRoot) {
		return Overlay{}, errors.New("eve overlay paths must be explicit")
	}
	if request.SourceRoot == request.OverlayRoot {
		return Overlay{}, errors.New("eve overlay source and destination must differ")
	}
	if strings.TrimSpace(request.SourceRoot) == "" || strings.TrimSpace(request.OverlayRoot) == "" {
		return Overlay{}, errors.New("eve overlay source and destination are required")
	}
	if err := validateIdentity(request); err != nil {
		return Overlay{}, err
	}
	request.ApprovalNeverTools = normalizeApprovalNeverTools(request.ApprovalNeverTools)
	if err := validateLoopbackURL(request.MCPURL, "MCP URL"); err != nil {
		return Overlay{}, err
	}
	if request.ControlURL != "" {
		if err := validateLoopbackURL(request.ControlURL, "control URL"); err != nil {
			return Overlay{}, err
		}
	}
	if err := rejectReservedSourcePaths(request.SourceRoot); err != nil {
		return Overlay{}, err
	}

	info, err := os.Stat(request.SourceRoot)
	if err != nil {
		return Overlay{}, fmt.Errorf("stat Eve source root: %w", err)
	}
	if !info.IsDir() {
		return Overlay{}, errors.New("Eve source root must be a directory")
	}
	if info, err := os.Lstat(request.OverlayRoot); err == nil {
		if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
			return Overlay{}, errors.New("Eve overlay destination must be a new directory")
		}
		return Overlay{}, errors.New("Eve overlay destination already exists")
	} else if !errors.Is(err, os.ErrNotExist) {
		return Overlay{}, fmt.Errorf("check Eve overlay destination: %w", err)
	}
	if err := copyAuthoredTree(request.SourceRoot, request.OverlayRoot); err != nil {
		return Overlay{}, err
	}

	data := templateData{
		AssistantAddress:   request.AssistantAddress,
		RuntimeRevision:    request.RuntimeRevision,
		CapabilityRevision: request.CapabilityRevision,
		ApprovalNeverTools: request.ApprovalNeverTools,
		ControlURL:         request.ControlURL,
		MCPURL:             request.MCPURL,
		EveVersion:         EveVersion,
		NodeVersion:        NodeVersion,
	}
	files := map[string]string{
		"agent/channels/scenery.ts":      "templates/scenery-channel.ts.tmpl",
		"agent/connections/scenery.ts":   "templates/scenery-connection.ts.tmpl",
		".scenery/bootstrap.mjs":         "templates/bootstrap.mjs.tmpl",
		".scenery/runtime-manifest.json": "templates/runtime-manifest.json.tmpl",
	}
	for path, templatePath := range files {
		if err := renderTemplate(templatePath, filepath.Join(request.OverlayRoot, filepath.FromSlash(path)), data); err != nil {
			return Overlay{}, err
		}
	}

	lockDigest, err := digestFile(filepath.Join(request.OverlayRoot, "package-lock.json"))
	if err != nil {
		return Overlay{}, fmt.Errorf("digest Eve package lock: %w", err)
	}
	manifestDigest, err := digestFile(filepath.Join(request.OverlayRoot, ".scenery/runtime-manifest.json"))
	if err != nil {
		return Overlay{}, fmt.Errorf("digest Eve runtime manifest: %w", err)
	}
	return Overlay{
		Root:              request.OverlayRoot,
		ChannelPath:       filepath.Join(request.OverlayRoot, filepath.FromSlash("agent/channels/scenery.ts")),
		ConnectionPath:    filepath.Join(request.OverlayRoot, filepath.FromSlash("agent/connections/scenery.ts")),
		BootstrapPath:     filepath.Join(request.OverlayRoot, filepath.FromSlash(".scenery/bootstrap.mjs")),
		ManifestPath:      filepath.Join(request.OverlayRoot, filepath.FromSlash(".scenery/runtime-manifest.json")),
		PackageLockDigest: lockDigest,
		ManifestDigest:    manifestDigest,
	}, nil
}

// Materialize is a short alias used by build orchestration code.
func Materialize(request OverlayRequest) (Overlay, error) {
	return MaterializeOverlay(request)
}

type templateData struct {
	AssistantAddress   string
	RuntimeRevision    string
	CapabilityRevision string
	ApprovalNeverTools []string
	ControlURL         string
	MCPURL             string
	EveVersion         string
	NodeVersion        string
}

//go:embed templates/*
var templateFiles embed.FS

var templateFuncs = template.FuncMap{
	"json": func(value any) string {
		encoded, _ := json.Marshal(value)
		return string(encoded)
	},
}

// ApprovalNeverTools qualifies the local capability names that Eve may run
// without pausing. Unknown and federated tools are deliberately omitted so
// the generated policy continues to fail closed.
func ApprovalNeverTools(manifest mcpcontract.Manifest) []string {
	tools := make([]string, 0, len(manifest.Capabilities))
	for _, capability := range manifest.Capabilities {
		if capability.Approval != mcpcontract.ApprovalNever || strings.TrimSpace(capability.Name) == "" {
			continue
		}
		tools = append(tools, "scenery__"+strings.TrimSpace(capability.Name))
	}
	return normalizeApprovalNeverTools(tools)
}

func normalizeApprovalNeverTools(tools []string) []string {
	seen := make(map[string]struct{}, len(tools))
	result := make([]string, 0, len(tools))
	for _, tool := range tools {
		tool = strings.TrimSpace(tool)
		if tool == "" {
			continue
		}
		if _, ok := seen[tool]; ok {
			continue
		}
		seen[tool] = struct{}{}
		result = append(result, tool)
	}
	sort.Strings(result)
	return result
}

func renderTemplate(templatePath, destination string, data templateData) error {
	contents, err := fs.ReadFile(templateFiles, templatePath)
	if err != nil {
		return fmt.Errorf("read Eve adapter template %s: %w", templatePath, err)
	}
	tpl, err := template.New(filepath.Base(templatePath)).Funcs(templateFuncs).Parse(string(contents))
	if err != nil {
		return fmt.Errorf("parse Eve adapter template %s: %w", templatePath, err)
	}
	if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
		return fmt.Errorf("create Eve generated directory: %w", err)
	}
	var output bytes.Buffer
	if err := tpl.Execute(&output, data); err != nil {
		return fmt.Errorf("render Eve adapter template %s: %w", templatePath, err)
	}
	mode := fs.FileMode(0o644)
	if strings.HasSuffix(destination, "bootstrap.mjs") {
		mode = 0o755
	}
	if err := os.WriteFile(destination, output.Bytes(), mode); err != nil {
		return fmt.Errorf("write Eve generated file %s: %w", destination, err)
	}
	return nil
}

func validateIdentity(request OverlayRequest) error {
	if strings.TrimSpace(request.AssistantAddress) == "" {
		return errors.New("Eve assistant address is required")
	}
	if strings.TrimSpace(request.RuntimeRevision) == "" {
		return errors.New("Eve runtime revision is required")
	}
	if strings.TrimSpace(request.CapabilityRevision) == "" {
		return errors.New("Eve capability revision is required")
	}
	return nil
}

func validateLoopbackURL(raw, label string) error {
	parsed, err := url.Parse(strings.TrimSpace(raw))
	if err != nil || parsed.Scheme != "http" || parsed.Hostname() == "" {
		return fmt.Errorf("Eve %s must be an http loopback URL", label)
	}
	if parsed.User != nil || parsed.Host == "" {
		return fmt.Errorf("Eve %s must not include credentials", label)
	}
	if !isLoopbackHost(parsed.Hostname()) {
		return fmt.Errorf("Eve %s must target loopback", label)
	}
	return nil
}

func isLoopbackHost(host string) bool {
	host = strings.Trim(strings.ToLower(host), "[]")
	if host == "localhost" || strings.HasSuffix(host, ".localhost") || host == "::1" {
		return true
	}
	ip := net.ParseIP(host)
	return ip != nil && ip.IsLoopback()
}

func isFilesystemRoot(path string) bool {
	clean := filepath.Clean(path)
	volume := filepath.VolumeName(clean)
	if volume == "" {
		return clean == string(filepath.Separator)
	}
	return clean == volume+string(filepath.Separator)
}

func rejectReservedSourcePaths(sourceRoot string) error {
	for _, relative := range reservedPaths {
		path := filepath.Join(sourceRoot, filepath.FromSlash(relative))
		_, err := os.Lstat(path)
		if err == nil {
			return fmt.Errorf("Eve authored source claims reserved generated path %q", relative)
		}
		if !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("check Eve reserved path %q: %w", relative, err)
		}
	}
	return nil
}

func copyAuthoredTree(sourceRoot, destinationRoot string) error {
	return filepath.WalkDir(sourceRoot, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return fmt.Errorf("walk Eve source %s: %w", path, err)
		}
		relative, err := filepath.Rel(sourceRoot, path)
		if err != nil {
			return err
		}
		if relative == "." {
			return os.MkdirAll(destinationRoot, 0o755)
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("Eve source contains unsupported symlink %q", filepath.ToSlash(relative))
		}
		// Dependencies are installed by the managed npm lane. Copying a local
		// node_modules tree would make the overlay non-deterministic and can
		// accidentally carry machine-local binaries into a build capsule.
		if entry.IsDir() && entry.Name() == "node_modules" {
			return filepath.SkipDir
		}
		destination := filepath.Join(destinationRoot, relative)
		if entry.IsDir() {
			info, err := entry.Info()
			if err != nil {
				return err
			}
			return os.MkdirAll(destination, info.Mode().Perm())
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		contents, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read Eve authored file %s: %w", path, err)
		}
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(destination, contents, info.Mode().Perm()); err != nil {
			return fmt.Errorf("write Eve authored file %s: %w", destination, err)
		}
		return nil
	})
}

func digestFile(path string) (string, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	digest := sha256.Sum256(contents)
	return "sha256:" + hex.EncodeToString(digest[:]), nil
}

// PackageLockDigest returns the exact digest of a lock file. It is useful to
// bind helper implementation identity without exposing package contents.
func PackageLockDigest(path string) (string, error) {
	return digestFile(path)
}

// ReservedPathConflict reports whether a source tree claims any generated
// path, without materializing an overlay.
func ReservedPathConflict(sourceRoot string) (string, bool, error) {
	sourceRoot = filepath.Clean(sourceRoot)
	for _, relative := range reservedPaths {
		if _, err := os.Lstat(filepath.Join(sourceRoot, filepath.FromSlash(relative))); err == nil {
			return relative, true, nil
		} else if !errors.Is(err, os.ErrNotExist) {
			return "", false, err
		}
	}
	return "", false, nil
}

// ReservedPathList returns a stable copy for diagnostics and inspection.
func ReservedPathList() []string {
	result := append([]string(nil), reservedPaths[:]...)
	sort.Strings(result)
	return result
}

// Ensure this package's generated protocol values stay tied to the current
// private contract. This compile-time reference also documents the boundary.
var _ = assistantcontrol.ControlProtocol
