// Code generated by Scenery. DO NOT EDIT.
package scenerycontract

import (
	"encoding/json"
	"fmt"
	scenery "scenery.sh"
)

var _ = scenery.Problem{}

type ObjectSummary struct {
	Body      string `json:"body"`
	Key       string `json:"key"`
	SizeBytes int64  `json:"size_bytes"`
}

func (value ObjectSummary) MarshalJSON() ([]byte, error) {
	if err := value.Validate(); err != nil {
		return nil, err
	}
	object := map[string]json.RawMessage{}
	rawBody, err := scenery.MarshalContractValue(value.Body, "string")
	if err != nil {
		return nil, fmt.Errorf("encode field body: %w", err)
	}
	object["body"] = rawBody
	rawKey, err := scenery.MarshalContractValue(value.Key, "string")
	if err != nil {
		return nil, fmt.Errorf("encode field key: %w", err)
	}
	object["key"] = rawKey
	rawSizeBytes, err := scenery.MarshalContractValue(value.SizeBytes, "int64")
	if err != nil {
		return nil, fmt.Errorf("encode field size_bytes: %w", err)
	}
	object["size_bytes"] = rawSizeBytes
	encoded, err := json.Marshal(object)
	if err != nil {
		return nil, err
	}
	return scenery.MarshalContractValue(scenery.JSON(encoded), "json")
}

func (value *ObjectSummary) UnmarshalJSON(data []byte) error {
	object, err := scenery.DecodeJSONObject(data)
	if err != nil {
		return err
	}
	*value = ObjectSummary{}
	rawBody, exists := object["body"]
	if !exists {
		return fmt.Errorf("missing required field body")
	}
	if err := unmarshalGeneratedContractValue(rawBody, &value.Body, "string"); err != nil {
		return fmt.Errorf("decode field body: %w", err)
	}
	delete(object, "body")
	rawKey, exists := object["key"]
	if !exists {
		return fmt.Errorf("missing required field key")
	}
	if err := unmarshalGeneratedContractValue(rawKey, &value.Key, "string"); err != nil {
		return fmt.Errorf("decode field key: %w", err)
	}
	delete(object, "key")
	rawSizeBytes, exists := object["size_bytes"]
	if !exists {
		return fmt.Errorf("missing required field size_bytes")
	}
	if err := unmarshalGeneratedContractValue(rawSizeBytes, &value.SizeBytes, "int64"); err != nil {
		return fmt.Errorf("decode field size_bytes: %w", err)
	}
	delete(object, "size_bytes")
	for key := range object {
		return fmt.Errorf("unknown field %q", key)
	}
	return value.Validate()
}

func (value ObjectSummary) Validate() error {
	if err := scenery.ValidateContractValue(value.Body, "string", scenery.ContractConstraints{}); err != nil {
		return fmt.Errorf("validate field body: %w", err)
	}
	if err := scenery.ValidateContractValue(value.Key, "string", scenery.ContractConstraints{}); err != nil {
		return fmt.Errorf("validate field key: %w", err)
	}
	if err := scenery.ValidateContractValue(value.SizeBytes, "int64", scenery.ContractConstraints{}); err != nil {
		return fmt.Errorf("validate field size_bytes: %w", err)
	}
	return nil
}

func unmarshalGeneratedContractValue(data []byte, target any, typeExpression string) error {
	return scenery.UnmarshalContractValue(data, target, typeExpression)
}
