// Code generated by Scenery. DO NOT EDIT.
package composition

import (
	adapter0 "example.com/basicapp/internal/scenerygen/service_service_adapter"
	scenery "scenery.sh"
)

const ContractRevision = "sha256:a50c5a9164158b02c02c8d9fbb1881415ae12cef9c5e8abfad47ef7e72e6b26f"

var RequiredAddresses = []string{"service/binding/echo_http", "service/execution/echo_direct", "service/operation/echo", "service/service/service"}

var RequiredProviderABIs = map[string]string{}

func Register(registry scenery.Registry) error {
	if err := adapter0.Register(registry); err != nil {
		return err
	}
	return nil
}
