// Code generated by scenery generate data; DO NOT EDIT.

schema "public" {}

enum "tasks_status" {
  schema = schema.public
  values = ["todo", "doing", "done"]
}

table "tasks" {
  schema = schema.public

  column "id" {
    null = false
    type = text
  }

  column "tenant_id" {
    null = false
    type = text
  }

  column "title" {
    null = false
    type = text
  }

  column "status" {
    null = false
    type = enum.tasks_status
  }

  column "project_id" {
    null = false
    type = text
  }

  column "created_at" {
    null = false
    type = timestamptz
  }

  primary_key {
    columns = [column.id]
  }
}
