// Code generated by scenery generate data; DO NOT EDIT.

schema "tasks" {}

enum "tasks" "tasks_status" {
  schema = schema.tasks
  values = ["todo", "doing", "done"]
}

enum "tasks" "tasks_priority" {
  schema = schema.tasks
  values = ["low", "normal", "high"]
}

table "tasks" "tasks" {
  schema = schema.tasks

  column "id" {
    null = false
    type = text
  }

  column "tenant_id" {
    null = false
    type = text
  }

  column "title" {
    null = false
    type = text
  }

  column "status" {
    null = false
    type = enum.tasks.tasks_status
  }

  column "priority" {
    null = false
    type = enum.tasks.tasks_priority
  }

  column "assignee_name" {
    null = false
    type = text
  }

  column "due_at" {
    null = false
    type = timestamptz
  }

  column "project_id" {
    null = false
    type = text
  }

  column "created_at" {
    null = false
    type = timestamptz
  }

  column "updated_at" {
    null = false
    type = timestamptz
  }

  primary_key {
    columns = [column.id]
  }
}
