// Code generated by Scenery vNext. DO NOT EDIT.
package composition

import (
	adapter0 "example.test/bridgeapp/internal/scenerygen/bridge_bridge_adapter"
	scenery "scenery.sh"
)

const ContractRevision = "sha256:13091d6d1929f10339f55ad03714840fa56e206a063ce1c4e731615ccb19ca41"

var RequiredAddresses = []string{"bridge/binding/echo_http", "bridge/execution/echo_direct", "bridge/operation/echo", "bridge/service/bridge"}

var RequiredProviderABIs = map[string]string{}

func Register(registry scenery.Registry) error {
	if err := adapter0.Register(registry); err != nil {
		return err
	}
	return nil
}
