// Code generated by Scenery vNext. DO NOT EDIT.
package scenerycontract

import (
	"fmt"
	scenery "scenery.sh"
)

const PackageIdentity = "house"
const PackageVersion = "1.0.0"
const PackageContractABIRevision = "sha256:6cb7f6946c19487215fa6adab199e86895733ed3e15b7a66546993cd9a0459bf"
const PackageImportPath = "example.test/clean-tech/house"
const GoImplementationABIRange = ">=1.0.0, <2.0.0"
const RuntimeABIRange = "scenery.go-runtime/v1"

type HouseDependencies struct {
}

type HouseConfig struct {
}
type HouseClients struct {
}
type HouseConstructorInput struct {
	Dependencies HouseDependencies
	Config       HouseConfig
	Clients      HouseClients
}

func UnmarshalProcessSceneInput(data []byte) (ProcessSceneInput, error) {
	var value ProcessSceneInput
	if err := unmarshalGeneratedContractValue(data, &value, "record.process_scene_input"); err != nil {
		return value, err
	}
	return value, nil
}

func CloneProcessSceneInput(value ProcessSceneInput) (ProcessSceneInput, error) {
	raw, err := scenery.MarshalContractValue(value, "record.process_scene_input")
	if err != nil {
		return value, err
	}
	return UnmarshalProcessSceneInput(raw)
}

type ProcessSceneOutcome interface{ isProcessSceneOutcome() }

type ProcessSceneProcessed struct{ Value ProcessSceneResult }

func (ProcessSceneProcessed) isProcessSceneOutcome() {}

func MarshalProcessSceneOutcome(value ProcessSceneOutcome) ([]byte, error) {
	switch typed := value.(type) {
	case ProcessSceneProcessed:
		return scenery.MarshalContractOutcomeVariant("result", "processed", typed.Value, "record.process_scene_result")
	case *ProcessSceneProcessed:
		if typed == nil {
			return nil, fmt.Errorf("nil ProcessSceneProcessed outcome")
		}
		return scenery.MarshalContractOutcomeVariant("result", "processed", typed.Value, "record.process_scene_result")
	default:
		return nil, fmt.Errorf("unknown operation outcome %T", value)
	}
}

func UnmarshalProcessSceneOutcome(data []byte) (ProcessSceneOutcome, error) {
	kind, name, payload, err := scenery.DecodeContractOutcomeEnvelope(data)
	if err != nil {
		return nil, err
	}
	switch {
	case kind == "result" && name == "processed":
		var value ProcessSceneResult
		if err := unmarshalGeneratedContractValue(payload, &value, "record.process_scene_result"); err != nil {
			return nil, err
		}
		return ProcessSceneProcessed{Value: value}, nil
	default:
		return nil, fmt.Errorf("unknown operation outcome %s.%s", kind, name)
	}
}

func CloneProcessSceneOutcome(value ProcessSceneOutcome) (ProcessSceneOutcome, error) {
	raw, err := MarshalProcessSceneOutcome(value)
	if err != nil {
		return nil, err
	}
	return UnmarshalProcessSceneOutcome(raw)
}
