package generate

import (
	"bytes"
	"io/fs"
	"path/filepath"

	uicatalog "scenery.sh/ui"
)

func renderUICatalog(root string) ([]generatedFile, error) {
	var files []generatedFile
	err := fs.WalkDir(uicatalog.Files, ".", func(path string, entry fs.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		data, err := uicatalog.Files.ReadFile(path)
		if err != nil {
			return err
		}
		files = append(files, generatedFile{Path: filepath.Join(root, filepath.FromSlash(path)), Bytes: markGeneratedUICatalogFile(path, data)})
		return nil
	})
	return files, err
}

func markGeneratedUICatalogFile(path string, data []byte) []byte {
	const lineMarker = "// Code generated by Scenery. DO NOT EDIT.\n"
	switch filepath.Ext(path) {
	case ".json":
		return bytes.Replace(data, []byte("{"), []byte("{\n  \"_generated\": \"Code generated by Scenery. DO NOT EDIT.\","), 1)
	case ".css":
		return append([]byte("/* Code generated by Scenery. DO NOT EDIT. */\n"), data...)
	default:
		return append([]byte(lineMarker), data...)
	}
}
