package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestBinaryOwnedUICatalogContainsComposableQueryTable(t *testing.T) {
	root := t.TempDir()
	files, err := renderUICatalog("", root)
	if err != nil {
		t.Fatal(err)
	}
	content := map[string]string{}
	for _, file := range files {
		path := filepath.ToSlash(strings.TrimPrefix(file.Path, root+string(filepath.Separator)))
		content[path] = string(file.Bytes)
		if !trustedGeneratedArtifact("", path, file.Bytes) {
			t.Errorf("catalog %s has no trusted generated marker", path)
		}
		if filepath.Ext(path) == ".css" {
			t.Errorf("catalog materialized obsolete CSS file %s", path)
		}
	}
	for path, fragment := range map[string]string{
		"components/DataTable.tsx":      "export function DataTable",
		"components/PageLayout.tsx":     "defineContentPageSlots",
		"components/QueryTable.tsx":     "export function QueryTable",
		"components/request-state.ts":   "export type RequestState",
		"components/SplitPage.tsx":      "defineSplitPageSlots",
		"components/SideNavigation.tsx": "export function SideNavigation",
		"components/TopBar.tsx":         "export function TopBar",
		"global.d.ts":                   "Code generated by Scenery",
		"index.ts":                      `from "./components/QueryTable.js"`,
		"package.json":                  `"name": "@scenery/ui"`,
		"tokens.stylex.ts":              `export const t = stylex.defineVars`,
	} {
		if !strings.Contains(content[path], fragment) {
			t.Errorf("catalog %s missing %q", path, fragment)
		}
	}
	queryTable := content["components/QueryTable.tsx"]
	for _, fragment := range []string{
		`@astryxdesign/core/DateTimeInput`,
		`@astryxdesign/core/Pagination`,
		`@astryxdesign/core/Selector`,
		`@tanstack/react-query`,
		`requestStateFromQuery<{`,
		`<DataTable`,
		`<QueryState`,
	} {
		if !strings.Contains(queryTable, fragment) {
			t.Errorf("QueryTable missing %q", fragment)
		}
	}
	for _, rawControl := range []string{"<button", "<input", "<select"} {
		if strings.Contains(queryTable, rawControl) {
			t.Errorf("QueryTable contains raw control %q", rawControl)
		}
	}
	for path := range content {
		if strings.HasPrefix(path, "pages/") {
			t.Errorf("catalog still materializes obsolete page surface %s", path)
		}
	}
}

func TestRenderUICatalogFromConfiguredDirectory(t *testing.T) {
	appRoot := t.TempDir()
	catalog := filepath.Join(appRoot, "ui-src")
	for path, contents := range map[string]string{
		"package.json":          `{"name":"@scenery/ui"}`,
		"index.ts":              `export * from "./components/Button.js";`,
		"tokens.stylex.ts":      `export const t = {};`,
		"components/Button.tsx": "export function Button() { return null; }",
		"pages/Obsolete.css":    ":root { color: red; }",
		"AGENTS.md":             "not a catalog file",
		"embed.go":              "package ui",
	} {
		full := filepath.Join(catalog, filepath.FromSlash(path))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(contents), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	config := `{"name":"catalogapp","envs":{"local":{"default":true,"ui_catalog":"ui-src"}}}`
	if err := os.WriteFile(filepath.Join(appRoot, ".scenery.json"), []byte(config), 0o644); err != nil {
		t.Fatal(err)
	}

	out := t.TempDir()
	files, err := renderUICatalog(appRoot, out)
	if err != nil {
		t.Fatal(err)
	}
	content := map[string]string{}
	for _, file := range files {
		path := filepath.ToSlash(strings.TrimPrefix(file.Path, out+string(filepath.Separator)))
		content[path] = string(file.Bytes)
	}
	if got := content["components/Button.tsx"]; !strings.Contains(got, "export function Button") || !strings.HasPrefix(got, "// Code generated by Scenery.") {
		t.Errorf("Button.tsx = %q, want live content with generated marker", got)
	}
	if got := content["package.json"]; !strings.Contains(got, `"_generated"`) {
		t.Errorf("package.json = %q, want _generated marker", got)
	}
	if got := content["tokens.stylex.ts"]; !strings.Contains(got, "export const t") || !strings.HasPrefix(got, "// Code generated by Scenery.") {
		t.Errorf("tokens.stylex.ts = %q, want live content with generated marker", got)
	}
	for _, excluded := range []string{"AGENTS.md", "embed.go", "pages/Obsolete.css"} {
		if _, ok := content[excluded]; ok {
			t.Errorf("catalog materialized repo file %s", excluded)
		}
	}
}

func TestIncludeStaleUICatalogFilesRetiresOnlyGeneratedFiles(t *testing.T) {
	root := t.TempDir()
	catalogRoot := filepath.Join(root, ".scenery", "gen", "typescript", "public_api", "react", "scenery-ui")
	for path, contents := range map[string]string{
		"components/Current.tsx": "// Code generated by Scenery. DO NOT EDIT.\nexport {};\n",
		"components/Stale.tsx":   "// Code generated by Scenery. DO NOT EDIT.\nexport {};\n",
		"components/Owned.tsx":   "export {};\n",
	} {
		full := filepath.Join(catalogRoot, filepath.FromSlash(path))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(contents), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	result := &Result{Root: root}
	target := Resource{
		Name: "public_api",
		Spec: map[string]any{
			"materialization": "cache",
			"react":           map[string]any{},
		},
	}
	files := []generatedFile{{
		Path:  filepath.Join(catalogRoot, "components", "Current.tsx"),
		Bytes: []byte("// Code generated by Scenery. DO NOT EDIT.\nexport {};\n"),
	}}
	files, err := includeStaleUICatalogFiles(result, []Resource{target}, files)
	if err != nil {
		t.Fatal(err)
	}
	var removed []string
	for _, file := range files {
		if file.Remove {
			removed = append(removed, filepath.Base(file.Path))
		}
	}
	if len(removed) != 1 || removed[0] != "Stale.tsx" {
		t.Fatalf("removed = %v, want [Stale.tsx]", removed)
	}
}

func TestRenderUICatalogMissingConfiguredDirectoryFallsBackToEmbed(t *testing.T) {
	appRoot := t.TempDir()
	config := `{"name":"catalogapp","envs":{"local":{"default":true,"ui_catalog":"no-such-dir"}}}`
	if err := os.WriteFile(filepath.Join(appRoot, ".scenery.json"), []byte(config), 0o644); err != nil {
		t.Fatal(err)
	}
	files, err := renderUICatalog(appRoot, t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, file := range files {
		if strings.HasSuffix(filepath.ToSlash(file.Path), "components/DataTable.tsx") {
			found = true
		}
	}
	if !found {
		t.Fatal("embedded catalog fallback missing components/DataTable.tsx")
	}
}

func TestRenderUICatalogImplausibleConfiguredDirectoryFails(t *testing.T) {
	appRoot := t.TempDir()
	if err := os.MkdirAll(filepath.Join(appRoot, "empty"), 0o755); err != nil {
		t.Fatal(err)
	}
	config := `{"name":"catalogapp","envs":{"local":{"default":true,"ui_catalog":"empty"}}}`
	if err := os.WriteFile(filepath.Join(appRoot, ".scenery.json"), []byte(config), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := renderUICatalog(appRoot, t.TempDir()); err == nil || !strings.Contains(err.Error(), "not a UI catalog root") {
		t.Fatalf("error = %v, want catalog-root rejection", err)
	}
}
