package generate

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

type reactRoutePage struct {
	resource  Resource
	component string
}

func reactRoutePages(pages []reactTablePage, splitPages []reactSplitPage, contentPages []reactContentPage) []reactRoutePage {
	result := make([]reactRoutePage, 0, len(pages)+len(splitPages)+len(contentPages))
	for _, page := range pages {
		result = append(result, reactRoutePage{resource: page.table, component: goName(page.table.Name) + "Page"})
	}
	for _, page := range splitPages {
		result = append(result, reactRoutePage{resource: page.split, component: goName(page.split.Name) + "Page"})
	}
	for _, page := range contentPages {
		result = append(result, reactRoutePage{resource: page.content, component: goName(page.content.Name) + "Page"})
	}
	sort.Slice(result, func(i, j int) bool { return result[i].resource.Address < result[j].resource.Address })
	return result
}

func renderReactRoutes(result *Result, pages []reactRoutePage) string {
	var b strings.Builder
	b.WriteString("// Code generated by Scenery. DO NOT EDIT.\n")
	b.WriteString("import { createElement } from \"react\";\n")
	b.WriteString("import type { ComponentType, ReactNode } from \"react\";\n")
	b.WriteString("import type { PublicApiClient } from \"../index.js\";\n")
	for _, page := range pages {
		fmt.Fprintf(&b, "import { %s } from %q;\n", page.component, "./"+page.resource.Name+".generated.js")
	}
	b.WriteString(`
export type ScenerySearch = Record<string, unknown>;
export type ScenerySearchValidator = (search: ScenerySearch) => ScenerySearch;
export type SceneryRouteParent = "root" | "shell";
export type SceneryRouteComponent = () => ReactNode;

export type SceneryNavigationDescriptor = {
  readonly group: string;
  readonly order: number;
  readonly label: string;
  readonly icon?: string;
  readonly activePaths: readonly string[];
};

export type SceneryRouteDescriptor = {
  readonly path: string;
  readonly component: SceneryRouteComponent;
  readonly validateSearch?: ScenerySearchValidator;
  readonly navigation?: SceneryNavigationDescriptor;
  readonly parent?: SceneryRouteParent;
};

`)
	for _, page := range pages {
		writeReactSearchValidator(&b, result, page.resource)
	}
	b.WriteString("export function createGeneratedRoutes(client?: PublicApiClient): readonly SceneryRouteDescriptor[] {\n  return [\n")
	for _, page := range pages {
		resource := page.resource
		fmt.Fprintf(&b, "    {\n      path: %s,\n      component: () => createElement(%s as ComponentType<{ readonly client?: PublicApiClient }>, { client }),\n", strconv.Quote(stringValue(resource.Spec["path"])), page.component)
		if len(namedChildren(resource.Spec, "search")) > 0 {
			fmt.Fprintf(&b, "      validateSearch: validate%sSearch,\n", goName(resource.Name))
		}
		if group := stringValue(resource.Spec["nav_group"]); group != "" {
			order, _ := integerValue(resource.Spec["nav_order"])
			label := defaultString(stringValue(resource.Spec["nav_label"]), stringValue(resource.Spec["title"]))
			activePaths := stringValues(resource.Spec["nav_active_paths"])
			if len(activePaths) == 0 {
				activePaths = []string{stringValue(resource.Spec["path"])}
			}
			fmt.Fprintf(&b, "      navigation: { group: %s, order: %d, label: %s", strconv.Quote(group), order, strconv.Quote(label))
			if icon := stringValue(resource.Spec["nav_icon"]); icon != "" {
				fmt.Fprintf(&b, ", icon: %s", strconv.Quote(icon))
			}
			fmt.Fprintf(&b, ", activePaths: %s },\n", renderTypeScriptStringArray(activePaths))
		}
		b.WriteString("    },\n")
	}
	b.WriteString("  ] as const satisfies readonly SceneryRouteDescriptor[];\n}\n")
	return b.String()
}

func writeReactSearchValidator(b *strings.Builder, result *Result, page Resource) {
	search := namedChildren(page.Spec, "search")
	if len(search) == 0 {
		return
	}
	typeName := goName(page.Name) + "Search"
	fmt.Fprintf(b, "export type %s = {\n", typeName)
	for _, parameter := range search {
		fmt.Fprintf(b, "  %s?: %s;\n", tsName(stringValue(parameter["name"])), reactSearchType(result, page, parameter["type"]))
	}
	b.WriteString("};\n\n")
	fmt.Fprintf(b, "export function validate%sSearch(search: ScenerySearch): %s {\n  return {\n", goName(page.Name), typeName)
	for _, parameter := range search {
		name := stringValue(parameter["name"])
		fmt.Fprintf(b, "    %s: %s,\n", tsName(name), reactSearchValue(result, page, parameter["type"], "search["+strconv.Quote(name)+"]"))
	}
	b.WriteString("  };\n}\n\n")
}

func reactSearchType(result *Result, page Resource, value any) string {
	expression := typeExpression(value)
	switch expression {
	case "string":
		return "string"
	case "bool":
		return "boolean"
	}
	values := enumWireValues(resourcesByAddress(result.Manifest), page.Module, value)
	if len(values) == 0 {
		return "never"
	}
	quoted := make([]string, len(values))
	for index, item := range values {
		quoted[index] = strconv.Quote(item)
	}
	return strings.Join(quoted, " | ")
}

func reactSearchValue(result *Result, page Resource, value any, expression string) string {
	switch typeExpression(value) {
	case "string":
		return "typeof " + expression + " === \"string\" && " + expression + " !== \"\" ? " + expression + " : undefined"
	case "bool":
		return expression + " === true || " + expression + " === \"true\" ? true : " + expression + " === false || " + expression + " === \"false\" ? false : undefined"
	}
	values := enumWireValues(resourcesByAddress(result.Manifest), page.Module, value)
	return reactLiteralPredicate(expression, values) + " ? " + expression + " : undefined"
}

func renderTypeScriptStringArray(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = strconv.Quote(value)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func renderReactAppAdapter() string {
	return `// Code generated by Scenery. DO NOT EDIT.
import {
  Outlet,
  RouterProvider,
  createRootRoute,
  createRoute,
  createRouter,
  useRouterState,
} from "@tanstack/react-router";
import type { ReactNode } from "react";
import type { PublicApiClient } from "../index.js";
import {
  ClientAppShell,
  type ClientAppShellProps,
  type SideNavigationSection,
} from "./scenery-ui/index.js";
import {
  createGeneratedRoutes,
  type SceneryNavigationDescriptor,
  type SceneryRouteComponent,
  type SceneryRouteDescriptor,
} from "./routes.generated.js";

export type SceneryNavigationGroupOptions = {
  readonly collapsible?: boolean;
  readonly icon?: string;
};

export type SceneryAppSlots = {
  readonly authGate?: (props: { readonly children: ReactNode }) => ReactNode;
  readonly topBar?: ReactNode;
  readonly beforeContent?: ReactNode;
  readonly afterContent?: ReactNode;
  readonly linkComponent?: ClientAppShellProps["linkComponent"];
  readonly navigationToggleIcon?: ReactNode;
  readonly resolveNavigationIcon?: (name: string) => ReactNode;
  readonly navigationGroups?: Readonly<
    Record<string, SceneryNavigationGroupOptions>
  >;
  readonly normalizePath?: (path: string) => string;
  readonly contentGroup?: (path: string) => string;
  readonly navigationFilter?: (routePath: string, currentPath: string) => boolean;
};

export type SceneryAppOptions = {
  readonly basepath?: string;
  readonly client?: PublicApiClient;
  readonly routes?: readonly SceneryRouteDescriptor[];
  readonly rootComponent?: SceneryRouteComponent;
  readonly slots?: SceneryAppSlots;
};

export function createSceneryApp(options: SceneryAppOptions = {}) {
  const routes: readonly SceneryRouteDescriptor[] = [
    ...createGeneratedRoutes(options.client),
    ...(options.routes ?? []),
  ];
  const RootComponent = options.rootComponent ?? RootOutlet;
  const rootRoute = createRootRoute({ component: RootComponent });

  function ShellRoute() {
    const currentPath = useRouterState({
      select: (state) => state.location.pathname,
    });
    const slots = options.slots ?? {};
    const normalizedPath = slots.normalizePath
      ? slots.normalizePath(currentPath)
      : currentPath;
    const content = (
      <ClientAppShell
        afterContent={slots.afterContent}
        beforeContent={slots.beforeContent}
        contentGroup={
          slots.contentGroup ? slots.contentGroup(normalizedPath) : undefined
        }
        linkComponent={slots.linkComponent}
        navigation={navigationSections(
          routes,
          normalizedPath,
          slots.resolveNavigationIcon,
          slots.navigationGroups,
          slots.navigationFilter,
        )}
        navigationToggleIcon={slots.navigationToggleIcon}
        topBar={slots.topBar}
      >
        <Outlet />
      </ClientAppShell>
    );
    const AuthGate = slots.authGate;
    return AuthGate ? <AuthGate>{content}</AuthGate> : content;
  }

  const shellRoute = createRoute({
    getParentRoute: () => rootRoute,
    id: "app",
    component: ShellRoute,
  });
  const shellChildren = routes
    .filter((route) => (route.parent ?? "shell") === "shell")
    .map((route) =>
      createRoute({
        getParentRoute: () => shellRoute,
        path: route.path,
        component: route.component,
        validateSearch: route.validateSearch,
      }),
    );
  const rootChildren = routes
    .filter((route) => route.parent === "root")
    .map((route) =>
      createRoute({
        getParentRoute: () => rootRoute,
        path: route.path,
        component: route.component,
        validateSearch: route.validateSearch,
      }),
    );
  const routeTree = rootRoute.addChildren([
    ...rootChildren,
    shellRoute.addChildren(shellChildren),
  ]);
  const router = createRouter({
    routeTree,
    basepath: options.basepath,
    defaultPreload: "intent",
    defaultPreloadDelay: 0,
    defaultPendingMs: 0,
    defaultPendingMinMs: 0,
    defaultStaleTime: Number.POSITIVE_INFINITY,
    defaultGcTime: Number.POSITIVE_INFINITY,
    defaultPreloadStaleTime: Number.POSITIVE_INFINITY,
    defaultPreloadGcTime: Number.POSITIVE_INFINITY,
  });
  function SceneryApp() {
    return <RouterProvider router={router} />;
  }
  return { router, App: SceneryApp };
}

function RootOutlet() {
  return <Outlet />;
}

function navigationSections(
  routes: readonly SceneryRouteDescriptor[],
  currentPath: string,
  resolveIcon: ((name: string) => ReactNode) | undefined,
  groupOptions: Readonly<Record<string, SceneryNavigationGroupOptions>> | undefined,
  navigationFilter: ((routePath: string, currentPath: string) => boolean) | undefined,
): readonly SideNavigationSection[] {
  const groups = new Map<string, Array<{
    descriptor: SceneryNavigationDescriptor;
    path: string;
  }>>();
  for (const route of routes) {
    if (!route.navigation) continue;
    if (navigationFilter && !navigationFilter(route.path, currentPath)) continue;
    const group = groups.get(route.navigation.group) ?? [];
    group.push({ descriptor: route.navigation, path: route.path });
    groups.set(route.navigation.group, group);
  }
  return [...groups.entries()]
    .sort(([leftTitle, left], [rightTitle, right]) =>
      Math.min(...left.map(({ descriptor }) => descriptor.order)) -
        Math.min(...right.map(({ descriptor }) => descriptor.order)) ||
      leftTitle.localeCompare(rightTitle),
    )
    .map(([title, entries]) => {
      const group = groupOptions?.[title];
      return {
        title,
        isHeaderHidden: title === "Main",
        collapsible: group?.collapsible,
        icon: group?.icon && resolveIcon ? resolveIcon(group.icon) : undefined,
        items: entries
          .sort((left, right) =>
            left.descriptor.order - right.descriptor.order ||
            left.descriptor.label.localeCompare(right.descriptor.label),
          )
          .map(({ descriptor, path }) => ({
            href: path,
            icon: descriptor.icon && resolveIcon ? resolveIcon(descriptor.icon) : undefined,
            isSelected: descriptor.activePaths.includes(currentPath),
            label: descriptor.label,
          })),
      };
    });
}
`
}
