package generate

import (
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"

	"scenery.sh/internal/compiler"
)

func goGeneratedDescriptorNames() map[string]bool {
	return map[string]bool{
		"scenery.package-generated.json": true,
		"scenery.generated.json":         true,
		"scenery.library-generated.json": true,
	}
}

// generatedGoVerificationOverlay stages expected artifacts and masks every
// descriptor-owned Go file scheduled for retirement. An empty overlay entry
// does not remove a file from go/packages, so removals use a package-only stub.
func generatedGoVerificationOverlay(files []generatedFile) (map[string][]byte, error) {
	overlay := map[string][]byte{}
	for _, file := range files {
		if filepath.Ext(file.Path) != ".go" {
			continue
		}
		absolute, err := filepath.Abs(file.Path)
		if err != nil {
			return nil, err
		}
		if !file.Remove {
			overlay[absolute] = file.Bytes
			continue
		}
		data, err := os.ReadFile(absolute)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return nil, err
		}
		parsed, err := parser.ParseFile(token.NewFileSet(), absolute, data, parser.PackageClauseOnly)
		if err != nil {
			return nil, fmt.Errorf("parse stale generated Go package %s: %w", file.Path, err)
		}
		overlay[absolute] = []byte("// Code generated by Scenery. DO NOT EDIT.\n\npackage " + parsed.Name.Name + "\n")
	}
	return overlay, nil
}

// GoVerificationOverlay returns current expected source, independent of local
// freshness, and masks authenticated stale generated files in the checkout.
func GoVerificationOverlay(result *compiler.Result) (map[string][]byte, error) {
	files, err := goVerificationFiles(result)
	if err != nil {
		return nil, err
	}
	return generatedGoVerificationOverlay(files)
}

func goVerificationFiles(result *compiler.Result) ([]generatedFile, error) {
	files, err := renderExpectedGoContractFiles(result)
	if err != nil {
		return nil, err
	}
	return goVerificationRetirements(result, files), nil
}

func goVerificationRetirements(result *compiler.Result, files []generatedFile) []generatedFile {
	// Ownership/freshness checking reports local conflicts separately. They
	// must not prevent ABI analysis from using the current expected contracts.
	if withRetirements, err := includeStaleGeneratedFiles(result.Root, files, goGeneratedDescriptorNames(), protectedGoGeneratedDescriptors(result)); err == nil {
		return withRetirements
	}
	return files
}
