package generate

import (
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type reactTablePage struct {
	table, crud, record, operation, binding Resource
}

type reactSplitPage struct {
	split, operation, binding Resource
}

func renderTypeScriptReact(result *Result, target Resource, root string, bindings []Resource) ([]generatedFile, []string, error) {
	if _, ok := target.Spec["react"].(map[string]any); !ok {
		return nil, []string{}, nil
	}
	reactRoot := filepath.Join(root, "react")
	catalogRoot := filepath.Join(reactRoot, "scenery-ui")
	files, err := renderUICatalog(result.Root, catalogRoot)
	if err != nil {
		return nil, nil, err
	}
	pages := selectedReactTablePages(result.Manifest.Resources, bindings)
	for _, page := range pages {
		source, renderErr := renderReactTablePage(result, target, reactRoot, page, bindings)
		if renderErr != nil {
			return nil, nil, renderErr
		}
		files = append(files, generatedFile{Path: filepath.Join(reactRoot, page.table.Name+".generated.tsx"), Bytes: []byte(source)})
	}
	splitPages := selectedReactSplitPages(result.Manifest.Resources, bindings)
	for _, page := range splitPages {
		source, renderErr := renderReactSplitPage(result, target, reactRoot, page, bindings)
		if renderErr != nil {
			return nil, nil, renderErr
		}
		files = append(files, generatedFile{Path: filepath.Join(reactRoot, page.split.Name+".generated.tsx"), Bytes: []byte(source)})
	}
	files = append(files,
		generatedFile{Path: filepath.Join(reactRoot, "pages.generated.ts"), Bytes: []byte(renderReactPages(pages, splitPages))},
		generatedFile{Path: filepath.Join(reactRoot, "index.ts"), Bytes: []byte("// Code generated by Scenery. DO NOT EDIT.\nexport * from \"./pages.generated.js\";\n")},
	)
	return files, []string{"react/scenery-ui"}, nil
}

func selectedReactTablePages(resources, bindings []Resource) []reactTablePage {
	byAddress := resourcesByAddress(&Manifest{Resources: resources})
	selectedBindings := map[string]Resource{}
	for _, binding := range bindings {
		selectedBindings[binding.Address] = binding
	}
	var pages []reactTablePage
	for _, table := range resources {
		if table.Kind != "scenery.table-page" || table.Origin.Kind == "expanded" {
			continue
		}
		crud := byAddress[resolveResourceRef(table, refString(table.Spec["source"]), "crud")]
		binding := selectedBindings[resourceAddress(crud.Module, "binding", crud.Name+"_list_http")]
		if binding.Address == "" {
			continue
		}
		operation := byAddress[resolveResourceRef(binding, refString(binding.Spec["operation"]), "operation")]
		entity := byAddress[resolveResourceRef(crud, refString(crud.Spec["entity"]), "entity")]
		record := byAddress[resolveResourceRef(entity, refString(entity.Spec["type"]), "record")]
		pages = append(pages, reactTablePage{table: table, crud: crud, record: record, operation: operation, binding: binding})
	}
	sort.Slice(pages, func(i, j int) bool { return pages[i].table.Address < pages[j].table.Address })
	return pages
}

func selectedReactSplitPages(resources, bindings []Resource) []reactSplitPage {
	byAddress := resourcesByAddress(&Manifest{Resources: resources})
	selectedBindings := map[string]Resource{}
	for _, binding := range bindings {
		selectedBindings[binding.Address] = binding
	}
	var pages []reactSplitPage
	for _, split := range resources {
		if split.Kind != "scenery.split-page" || split.Origin.Kind == "expanded" {
			continue
		}
		binding := selectedBindings[resolveResourceRef(split, refString(split.Spec["source"]), "binding")]
		if binding.Address == "" {
			continue
		}
		operation := byAddress[resolveResourceRef(binding, refString(binding.Spec["operation"]), "operation")]
		pages = append(pages, reactSplitPage{split: split, operation: operation, binding: binding})
	}
	sort.Slice(pages, func(i, j int) bool { return pages[i].split.Address < pages[j].split.Address })
	return pages
}

func renderReactPages(pages []reactTablePage, splitPages []reactSplitPage) string {
	var b strings.Builder
	b.WriteString("// Code generated by Scenery. DO NOT EDIT.\n")
	for _, page := range pages {
		fmt.Fprintf(&b, "import { %sPage } from %q;\n", goName(page.table.Name), "./"+page.table.Name+".generated.js")
	}
	for _, page := range splitPages {
		fmt.Fprintf(&b, "import { %sPage } from %q;\n", goName(page.split.Name), "./"+page.split.Name+".generated.js")
	}
	b.WriteString("\nexport const generatedPages = [\n")
	for _, page := range pages {
		fmt.Fprintf(&b, "  { path: %s, component: %sPage },\n", strconv.Quote(stringValue(page.table.Spec["path"])), goName(page.table.Name))
	}
	for _, page := range splitPages {
		fmt.Fprintf(&b, "  { path: %s, component: %sPage },\n", strconv.Quote(stringValue(page.split.Spec["path"])), goName(page.split.Name))
	}
	b.WriteString("] as const;\n")
	return b.String()
}

func renderReactSplitPage(result *Result, target Resource, reactRoot string, page reactSplitPage, bindings []Resource) (string, error) {
	resultType := tsType(namedChildren(page.operation.Spec, "result")[0]["type"])
	aliases := map[string]string{}
	var b strings.Builder
	b.WriteString("// Code generated by Scenery. DO NOT EDIT.\n")
	b.WriteString("import { useCallback, useEffect, useMemo, useState } from \"react\";\n")
	fmt.Fprintf(&b, "import { %sClient, SceneryClientError, url } from \"../index.js\";\n", goName(target.Name))
	fmt.Fprintf(&b, "import type { %s } from \"../index.js\";\n", resultType)
	b.WriteString("import { SplitPage, defineSplitPageSlots } from \"./scenery-ui/index.js\";\n")
	b.WriteString("import type { SplitPageSlotProps, SplitPageState } from \"./scenery-ui/index.js\";\n")
	for index, slot := range []string{"pane", "detail", "pane_actions", "detail_header"} {
		children := orderedChildren(page.split.Spec, slot)
		if len(children) == 0 {
			continue
		}
		componentAddress := resolveResourceRef(page.split, refString(children[0]["component"]), "react_component")
		component := resourcesByAddress(result.Manifest)[componentAddress]
		module, err := reactComponentImport(result, reactRoot, component)
		if err != nil {
			return "", err
		}
		alias := fmt.Sprintf("ScenerySplitSlot%d", index+1)
		aliases[slot] = alias
		fmt.Fprintf(&b, "import { %s as %s } from %s;\n", stringValue(component.Spec["export"]), alias, strconv.Quote(module))
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "const slots = defineSplitPageSlots<%s>()({\n", resultType)
	for _, slot := range []string{"pane", "detail", "pane_actions", "detail_header"} {
		if alias := aliases[slot]; alias != "" {
			fmt.Fprintf(&b, "  %s: %s,\n", tsName(slot), alias)
		}
	}
	b.WriteString("});\n\n")
	method := reactOperationClientMethod(page.operation, page.binding, bindings)
	fmt.Fprintf(&b, "export function %sPage({ client: providedClient }: { readonly client?: %sClient } = {}) {\n", goName(page.split.Name), goName(target.Name))
	fmt.Fprintf(&b, "  const defaultClient = useMemo(() => new %sClient({ baseUrl: url(new URL(\"/api/\", globalThis.location.origin).toString()), authentication: { credentials: \"include\" } }), []);\n", goName(target.Name))
	b.WriteString("  const client = providedClient ?? defaultClient;\n")
	fmt.Fprintf(&b, "  const load = useCallback(async (): Promise<SplitPageState<%s>> => {\n    try {\n", resultType)
	fmt.Fprintf(&b, "      const outcome = await client.%s({});\n", method)
	b.WriteString("      if (outcome.kind === \"result\") return { kind: \"result\", data: outcome.value };\n")
	b.WriteString("      return { kind: \"error\", name: outcome.name, problem: outcome.problem };\n")
	b.WriteString("    } catch (cause) {\n")
	b.WriteString("      if (cause instanceof SceneryClientError) return { kind: \"error\", name: cause.code, problem: { code: cause.code, message: cause.message } };\n")
	b.WriteString("      return { kind: \"error\", name: \"unexpected\", problem: { code: \"unexpected\", message: cause instanceof Error ? cause.message : \"Unexpected error\" } };\n")
	b.WriteString("    }\n  }, [client]);\n")
	fmt.Fprintf(&b, "  const queryParameter = %s;\n", strconv.Quote(defaultString(stringValue(page.split.Spec["query_parameter"]), "selected")))
	b.WriteString("  const [state, setState] = useState<SplitPageState<" + resultType + ">>({ kind: \"loading\" });\n")
	b.WriteString("  const [selection, setSelection] = useState(() => typeof globalThis.location === \"undefined\" ? \"\" : new URLSearchParams(globalThis.location.search).get(queryParameter) ?? \"\");\n")
	b.WriteString("  useEffect(() => { let active = true; void load().then((next) => { if (active) setState(next); }); return () => { active = false; }; }, [load]);\n")
	b.WriteString("  const onSelectionChange = useCallback((next: string) => { setSelection(next); if (typeof globalThis.location !== \"undefined\") { const nextURL = new URL(globalThis.location.href); nextURL.searchParams.set(queryParameter, next); globalThis.history.pushState({}, \"\", nextURL); } }, [queryParameter]);\n")
	b.WriteString("  const slotProps: SplitPageSlotProps<" + resultType + "> = { state, selection, onSelectionChange };\n")
	fmt.Fprintf(&b, "  return <SplitPage ariaLabel=%s paneLabel=%s paneTitle=%s", strconv.Quote(defaultString(stringValue(page.split.Spec["aria_label"]), stringValue(page.split.Spec["title"]))), strconv.Quote(defaultString(stringValue(page.split.Spec["pane_label"]), stringValue(page.split.Spec["title"]))), strconv.Quote(stringValue(page.split.Spec["title"])))
	if aliases["pane_actions"] != "" {
		b.WriteString(" paneActions={<slots.paneActions {...slotProps} />}")
	}
	b.WriteString(" pane={<slots.pane {...slotProps} />}")
	if aliases["detail_header"] != "" {
		b.WriteString(" detailHeader={<slots.detailHeader {...slotProps} />}")
	}
	b.WriteString("><slots.detail {...slotProps} /></SplitPage>;\n}\n")
	return b.String(), nil
}

func renderReactTablePage(result *Result, target Resource, reactRoot string, page reactTablePage, bindings []Resource) (string, error) {
	resources := resourcesByAddress(result.Manifest)
	fields := map[string]map[string]any{}
	for _, field := range namedChildren(page.record.Spec, "field") {
		fields[stringValue(field["name"])] = field
	}
	components := map[string]Resource{}
	collect := func(value any) {
		if value == nil {
			return
		}
		address := resolveResourceRef(page.table, refString(value), "react_component")
		if component := resources[address]; component.Address != "" {
			components[address] = component
		}
	}
	for _, kind := range []string{"column", "filter", "toolbar", "empty"} {
		for _, item := range orderedChildren(page.table.Spec, kind) {
			collect(item["component"])
		}
	}
	componentAddresses := make([]string, 0, len(components))
	for address := range components {
		componentAddresses = append(componentAddresses, address)
	}
	sort.Strings(componentAddresses)

	var b strings.Builder
	b.WriteString("// Code generated by Scenery. DO NOT EDIT.\n")
	b.WriteString("import { useCallback, useMemo } from \"react\";\n")
	clientImports := []string{goName(target.Name) + "Client", "SceneryClientError"}
	for _, filter := range orderedChildren(page.table.Spec, "filter") {
		field := fields[stringValue(filter["name"])]
		if field != nil && !strings.HasPrefix(typeExpression(field["type"]), "enum.") {
			clientImports = append(clientImports, "dateTime")
			break
		}
	}
	clientImports = append(clientImports, "url")
	fmt.Fprintf(&b, "import { %s } from \"../index.js\";\n", strings.Join(clientImports, ", "))
	fmt.Fprintf(&b, "import type { %s", goName(page.record.Name))
	typeImports := reactPageTypeImports(page, fields)
	for _, name := range typeImports {
		fmt.Fprintf(&b, ", %s", name)
	}
	b.WriteString(" } from \"../index.js\";\n")
	b.WriteString("import { TablePage, defineTablePageSlots } from \"./scenery-ui/index.js\";\n")
	uiTypeImports := []string{"TablePageQuery", "TablePageResult"}
	for _, column := range orderedChildren(page.table.Spec, "column") {
		if column["component"] != nil {
			uiTypeImports = append([]string{"TablePageCellProps"}, uiTypeImports...)
			break
		}
	}
	for _, filter := range orderedChildren(page.table.Spec, "filter") {
		field := fields[stringValue(filter["name"])]
		if filter["component"] != nil && field != nil && strings.HasPrefix(typeExpression(field["type"]), "enum.") {
			uiTypeImports = append([]string{"TablePageFilterProps"}, uiTypeImports...)
			break
		}
	}
	fmt.Fprintf(&b, "import type { %s } from \"./scenery-ui/index.js\";\n", strings.Join(uiTypeImports, ", "))
	aliases := map[string]string{}
	for index, address := range componentAddresses {
		component := components[address]
		module, err := reactComponentImport(result, reactRoot, component)
		if err != nil {
			return "", err
		}
		alias := fmt.Sprintf("SceneryOverride%d", index+1)
		aliases[address] = alias
		fmt.Fprintf(&b, "import { %s as %s } from %s;\n", stringValue(component.Spec["export"]), alias, strconv.Quote(module))
	}
	b.WriteString("\n")
	rowType := goName(page.record.Name)
	for _, column := range orderedChildren(page.table.Spec, "column") {
		if column["component"] == nil {
			continue
		}
		field := stringValue(column["name"])
		alias := aliases[resolveResourceRef(page.table, refString(column["component"]), "react_component")]
		fmt.Fprintf(&b, "function %s%sCell(props: TablePageCellProps<%s, %s[%s]>) { return <%s row={props.row} value={props.row.%s} />; }\n", goName(page.table.Name), goName(field), rowType, rowType, strconv.Quote(tsName(field)), alias, tsName(field))
	}
	for _, filter := range orderedChildren(page.table.Spec, "filter") {
		if filter["component"] == nil {
			continue
		}
		field := stringValue(filter["name"])
		alias := aliases[resolveResourceRef(page.table, refString(filter["component"]), "react_component")]
		values := enumWireValues(resources, page.record.Module, fields[field]["type"])
		if len(values) > 0 {
			typeName := tsType(fields[field]["type"])
			fmt.Fprintf(&b, "function %s%sFilter(props: TablePageFilterProps<string>) { const value = props.value !== undefined && %s ? props.value : undefined; return <%s label={props.label} value={value} onChange={props.onChange} />; }\n", goName(page.table.Name), goName(field), reactLiteralPredicate("props.value", values), alias)
			_ = typeName // the imported enum type is exercised by the generated list input.
		} else {
			fmt.Fprintf(&b, "const %s%sFilter = %s;\n", goName(page.table.Name), goName(field), alias)
		}
	}

	cellKeys, filterKeys := []string{}, []string{}
	for _, column := range orderedChildren(page.table.Spec, "column") {
		if column["component"] != nil {
			cellKeys = append(cellKeys, strconv.Quote(tsName(stringValue(column["name"]))))
		}
	}
	for _, filter := range orderedChildren(page.table.Spec, "filter") {
		if filter["component"] != nil {
			filterKeys = append(filterKeys, strconv.Quote(stringValue(filter["name"])))
		}
	}
	fmt.Fprintf(&b, "\nconst slots = defineTablePageSlots<%s, %s, %s>()({\n", rowType, unionOrNever(cellKeys), unionOrNever(filterKeys))
	if len(cellKeys) > 0 {
		b.WriteString("  cells: {\n")
		for _, column := range orderedChildren(page.table.Spec, "column") {
			if column["component"] != nil {
				field := stringValue(column["name"])
				fmt.Fprintf(&b, "    %s: %s%sCell,\n", tsName(field), goName(page.table.Name), goName(field))
			}
		}
		b.WriteString("  },\n")
	}
	if len(filterKeys) > 0 {
		b.WriteString("  filters: {\n")
		for _, filter := range orderedChildren(page.table.Spec, "filter") {
			if filter["component"] != nil {
				field := stringValue(filter["name"])
				fmt.Fprintf(&b, "    %s: %s%sFilter,\n", tsName(field), goName(page.table.Name), goName(field))
			}
		}
		b.WriteString("  },\n")
	}
	for _, slot := range []string{"toolbar", "empty"} {
		for _, value := range orderedChildren(page.table.Spec, slot) {
			if value["component"] != nil {
				alias := aliases[resolveResourceRef(page.table, refString(value["component"]), "react_component")]
				fmt.Fprintf(&b, "  %s: %s,\n", slot, alias)
			}
		}
	}
	b.WriteString("});\n\n")

	method := reactClientMethod(page, bindings)
	fmt.Fprintf(&b, "export function %sPage({ client: providedClient }: { readonly client?: %sClient } = {}) {\n", goName(page.table.Name), goName(target.Name))
	fmt.Fprintf(&b, "  const defaultClient = useMemo(() => new %sClient({ baseUrl: url(new URL(\"/api/\", globalThis.location.origin).toString()), authentication: { credentials: \"include\" } }), []);\n", goName(target.Name))
	b.WriteString("  const client = providedClient ?? defaultClient;\n")
	fmt.Fprintf(&b, "  const load = useCallback(async (query: TablePageQuery): Promise<TablePageResult<%s>> => {\n", rowType)
	b.WriteString("    try {\n")
	fmt.Fprintf(&b, "    const outcome = await client.%s({\n", method)
	for _, filter := range orderedChildren(page.table.Spec, "filter") {
		field := stringValue(filter["name"])
		values := enumWireValues(resources, page.record.Module, fields[field]["type"])
		if len(values) > 0 {
			fmt.Fprintf(&b, "      %s: Array.isArray(query.filters[%s]) ? query.filters[%s].filter((value): value is %s => %s) : undefined,\n", tsName(field), strconv.Quote(field), strconv.Quote(field), tsType(fields[field]["type"]), reactLiteralPredicate("value", values))
		} else {
			fmt.Fprintf(&b, "      %sFrom: typeof query.filters[%s] === \"string\" ? dateTime(query.filters[%s]) : undefined,\n", tsName(field), strconv.Quote(field+"_from"), strconv.Quote(field+"_from"))
			fmt.Fprintf(&b, "      %sTo: typeof query.filters[%s] === \"string\" ? dateTime(query.filters[%s]) : undefined,\n", tsName(field), strconv.Quote(field+"_to"), strconv.Quote(field+"_to"))
		}
	}
	sorts := stringValues(page.crud.Spec["list"].(map[string]any)["sorts"])
	fmt.Fprintf(&b, "      sort: query.sort !== undefined && %s ? query.sort : undefined,\n", reactLiteralPredicate("query.sort", sorts))
	b.WriteString("      direction: query.direction,\n      cursor: query.cursor,\n      limit: BigInt(query.limit),\n")
	b.WriteString("    });\n")
	b.WriteString("      if (outcome.kind === \"result\") return { kind: \"result\", items: outcome.value.items, nextCursor: outcome.value.nextCursor };\n")
	b.WriteString("      return { kind: \"error\", name: outcome.name, problem: outcome.problem };\n")
	b.WriteString("    } catch (cause) {\n")
	b.WriteString("      if (cause instanceof SceneryClientError) return { kind: \"error\", name: cause.code, problem: { code: cause.code, message: cause.message } };\n")
	b.WriteString("      throw cause;\n")
	b.WriteString("    }\n")
	b.WriteString("  }, [client]);\n")
	fmt.Fprintf(&b, "  return <TablePage<%s> title=%s", rowType, strconv.Quote(stringValue(page.table.Spec["title"])))
	if description := stringValue(page.table.Spec["description"]); description != "" {
		fmt.Fprintf(&b, " description=%s", strconv.Quote(description))
	}
	b.WriteString(" columns={[\n")
	for _, column := range orderedChildren(page.table.Spec, "column") {
		field := stringValue(column["name"])
		label := defaultString(stringValue(column["label"]), humanLabel(field))
		appearance := defaultString(stringValue(column["appearance"]), "auto")
		fmt.Fprintf(&b, "    { field: %s, label: %s, appearance: %s", strconv.Quote(tsName(field)), strconv.Quote(label), strconv.Quote(appearance))
		if column["component"] != nil {
			fmt.Fprintf(&b, ", component: slots.cells.%s", tsName(field))
		}
		b.WriteString(" },\n")
	}
	b.WriteString("  ]} filters={[\n")
	for _, filter := range orderedChildren(page.table.Spec, "filter") {
		field := stringValue(filter["name"])
		label := defaultString(stringValue(filter["label"]), humanLabel(field))
		values := enumWireValues(resources, page.record.Module, fields[field]["type"])
		if len(values) > 0 {
			fmt.Fprintf(&b, "    { field: %s, label: %s, kind: \"enum\", options: [%s]", strconv.Quote(field), strconv.Quote(label), quotedList(values))
		} else {
			fmt.Fprintf(&b, "    { field: %s, label: %s, kind: \"datetime\"", strconv.Quote(field), strconv.Quote(label))
		}
		if filter["component"] != nil {
			fmt.Fprintf(&b, ", component: slots.filters.%s", tsName(field))
		}
		b.WriteString(" },\n")
	}
	b.WriteString("  ]} sorts={[\n")
	for _, sortSpec := range orderedChildren(page.table.Spec, "sort") {
		field := stringValue(sortSpec["name"])
		fmt.Fprintf(&b, "    { field: %s, label: %s", strconv.Quote(field), strconv.Quote(defaultString(stringValue(sortSpec["label"]), humanLabel(field))))
		if direction := stringValue(sortSpec["default"]); direction != "" {
			fmt.Fprintf(&b, ", default: %s", strconv.Quote(direction))
		}
		b.WriteString(" },\n")
	}
	b.WriteString("  ]}")
	if rowLink := stringValue(page.table.Spec["row_link"]); rowLink != "" {
		fmt.Fprintf(&b, " rowLink={(row) => %s}", renderReactRowLink(rowLink))
	}
	pageSize, _ := integerValue(page.table.Spec["page_size"])
	fmt.Fprintf(&b, " pageSize={%d} load={load} slots={slots} />;\n}\n", pageSize)
	return b.String(), nil
}

func reactPageTypeImports(page reactTablePage, fields map[string]map[string]any) []string {
	set := map[string]bool{}
	for _, filter := range orderedChildren(page.table.Spec, "filter") {
		field := fields[stringValue(filter["name"])]
		if field != nil && strings.HasPrefix(typeExpression(field["type"]), "enum.") {
			set[tsType(field["type"])] = true
		}
	}
	result := make([]string, 0, len(set))
	for name := range set {
		if name != goName(page.record.Name) {
			result = append(result, name)
		}
	}
	sort.Strings(result)
	return result
}

func reactClientMethod(page reactTablePage, bindings []Resource) string {
	return reactOperationClientMethod(page.operation, page.binding, bindings)
}

func reactOperationClientMethod(operation, selectedBinding Resource, bindings []Resource) string {
	count := 0
	for _, binding := range bindings {
		if lastRef(refString(binding.Spec["operation"])) == operation.Name {
			count++
		}
	}
	method := tsName(operation.Name)
	if count > 1 {
		method += "Via" + goName(selectedBinding.Name)
	}
	return method
}

func reactComponentImport(result *Result, reactRoot string, component Resource) (string, error) {
	base := result.Root
	if component.Module != "app" {
		for _, resource := range result.Manifest.Resources {
			if resource.Kind == "scenery.module" && moduleInstancePath(resource) == component.Module {
				base = filepath.Join(result.Root, filepath.FromSlash(defaultString(stringValue(resource.Spec["workspace_package_root"]), stringValue(resource.Spec["source"]))))
				break
			}
		}
	}
	path := filepath.Join(base, filepath.FromSlash(stringValue(component.Spec["module"])))
	relative, err := filepath.Rel(reactRoot, path)
	if err != nil {
		return "", fmt.Errorf("react_component %s import path: %w", component.Address, err)
	}
	extension := filepath.Ext(relative)
	if extension == ".ts" || extension == ".tsx" || extension == ".jsx" {
		relative = strings.TrimSuffix(relative, extension) + ".js"
	}
	relative = filepath.ToSlash(relative)
	if !strings.HasPrefix(relative, ".") {
		relative = "./" + relative
	}
	return relative, nil
}

func reactLiteralPredicate(expression string, values []string) string {
	if len(values) == 0 {
		return "false"
	}
	parts := make([]string, len(values))
	for index, value := range values {
		parts[index] = expression + " === " + strconv.Quote(value)
	}
	return strings.Join(parts, " || ")
}

func renderReactRowLink(template string) string {
	expression := strconv.Quote(template)
	for _, match := range httpPathParameterPattern.FindAllStringSubmatch(template, -1) {
		expression = "(" + expression + ").replace(" + strconv.Quote("{"+match[1]+"}") + ", encodeURIComponent(String(row." + tsName(match[1]) + ")))"
	}
	return expression
}

func humanLabel(value string) string {
	parts := strings.Fields(strings.ReplaceAll(value, "_", " "))
	for index := range parts {
		parts[index] = strings.ToUpper(parts[index][:1]) + parts[index][1:]
	}
	return strings.Join(parts, " ")
}

func unionOrNever(values []string) string {
	if len(values) == 0 {
		return "never"
	}
	return strings.Join(values, " | ")
}

func quotedList(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = strconv.Quote(value)
	}
	return strings.Join(quoted, ", ")
}
