package generate

import (
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// reachableAssistantSurfaces returns only the assistant surfaces that name
// this TypeScript target.  An assistant implementation is deliberately not
// consulted here: the browser contract is owned by the public surface and
// must remain independent of its helper adapter.
func reachableAssistantSurfaces(resources []Resource, target Resource) []Resource {
	var result []Resource
	for _, resource := range resources {
		if resource.Kind != "scenery.assistant" {
			continue
		}
		surface, ok := resource.Spec["surface"].(map[string]any)
		if !ok || surface == nil {
			continue
		}
		client := resolveResourceRef(resource, refOrString(surface["client"]), "typescript_client")
		if client == target.Address || client == target.Module+"/typescript_client/"+target.Name || lastRef(client) == target.Name {
			if strings.TrimSpace(stringValue(surface["path"])) == "" {
				continue
			}
			result = append(result, resource)
		}
	}
	sort.Slice(result, func(i, j int) bool {
		if result[i].Name != result[j].Name {
			return result[i].Name < result[j].Name
		}
		return result[i].Address < result[j].Address
	})
	return result
}

func renderTypeScriptAssistantFile(target Resource, assistants []Resource) string {
	var b strings.Builder
	b.WriteString("// Code generated by Scenery. DO NOT EDIT.\n")
	b.WriteString("import * as Runtime from \"./runtime.js\";\nimport type { JsonValue } from \"./types.js\";\n\n")
	b.WriteString(renderAssistantTypeScriptContracts())
	b.WriteString("\n")

	for _, assistant := range assistants {
		name := assistant.Name
		if name == "" {
			name = assistantNameFromCanonicalAddress(assistant.Address)
		}
		surface, _ := assistant.Spec["surface"].(map[string]any)
		path := strings.TrimSuffix(strings.TrimSpace(stringValue(surface["path"])), "/")
		fmt.Fprintf(&b, "const %sAssistantPath = %s;\n", assistantConstantName(name), strconv.Quote(path))
	}
	if len(assistants) > 0 {
		b.WriteString("\n")
	}

	b.WriteString(renderAssistantTypeScriptImplementation())
	b.WriteString("\n")
	b.WriteString("export interface AssistantClients {\n")
	for _, assistant := range assistants {
		name := assistant.Name
		if name == "" {
			name = assistantNameFromCanonicalAddress(assistant.Address)
		}
		fmt.Fprintf(&b, "  readonly %s: AssistantConversationClient;\n", assistantPropertyName(name))
	}
	b.WriteString("}\n\n")
	b.WriteString("export function createAssistantClients(options: AssistantTransportOptions): AssistantClients {\n  return Object.freeze({\n")
	for _, assistant := range assistants {
		name := assistant.Name
		if name == "" {
			name = assistantNameFromCanonicalAddress(assistant.Address)
		}
		fmt.Fprintf(&b, "    %s: createAssistantConversationClient(%sAssistantPath, options, %s),\n", assistantPropertyName(name), assistantConstantName(name), strconv.Quote(name))
	}
	b.WriteString("  }) as AssistantClients;\n}\n")
	return b.String()
}

func assistantConstantName(name string) string {
	return "assistantPath" + goName(name)
}

func assistantPropertyName(name string) string {
	if isTypeScriptIdentifier(name) {
		return name
	}
	return strconv.Quote(name)
}

func isTypeScriptIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for index, r := range value {
		if !(r == '_' || r == '$' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || index > 0 && r >= '0' && r <= '9') {
			return false
		}
	}
	return true
}

func renderAssistantTypeScriptContracts() string {
	return `export type AssistantEventType =
  | "assistant.run.started"
  | "assistant.message.delta"
  | "assistant.message.completed"
  | "assistant.capability.proposed"
  | "assistant.approval.required"
  | "assistant.capability.started"
  | "assistant.capability.completed"
  | "assistant.run.completed"
  | "assistant.run.cancelled"
  | "assistant.run.failed"
  | "assistant.runtime.restarting";

export interface AssistantRunStarted { readonly type: "assistant.run.started"; readonly assistant: string; readonly conversationId: string; readonly runId: string; readonly sequence: number; readonly occurredAt: string; readonly data: { readonly state: "started" } }
export interface AssistantMessageDelta { readonly type: "assistant.message.delta"; readonly assistant: string; readonly conversationId: string; readonly runId: string; readonly sequence: number; readonly occurredAt: string; readonly data: { readonly text: string } }
export interface AssistantMessageCompleted { readonly type: "assistant.message.completed"; readonly assistant: string; readonly conversationId: string; readonly runId: string; readonly sequence: number; readonly occurredAt: string; readonly data: { readonly text: string } }
export interface AssistantCapabilityProposed { readonly type: "assistant.capability.proposed"; readonly assistant: string; readonly conversationId: string; readonly runId: string; readonly sequence: number; readonly occurredAt: string; readonly data: { readonly capability: string; readonly approvalId: string; readonly input: JsonValue } }
export interface AssistantApprovalRequired { readonly type: "assistant.approval.required"; readonly assistant: string; readonly conversationId: string; readonly runId: string; readonly sequence: number; readonly occurredAt: string; readonly data: { readonly capability: string; readonly approvalId: string } }
export interface AssistantCapabilityStarted { readonly type: "assistant.capability.started"; readonly assistant: string; readonly conversationId: string; readonly runId: string; readonly sequence: number; readonly occurredAt: string; readonly data: { readonly capability: string } }
export interface AssistantCapabilityCompleted { readonly type: "assistant.capability.completed"; readonly assistant: string; readonly conversationId: string; readonly runId: string; readonly sequence: number; readonly occurredAt: string; readonly data: { readonly capability: string; readonly state: "completed" } }
export interface AssistantRunCompleted { readonly type: "assistant.run.completed"; readonly assistant: string; readonly conversationId: string; readonly runId: string; readonly sequence: number; readonly occurredAt: string; readonly data: { readonly state: "completed" } }
export interface AssistantRunCancelled { readonly type: "assistant.run.cancelled"; readonly assistant: string; readonly conversationId: string; readonly runId: string; readonly sequence: number; readonly occurredAt: string; readonly data: { readonly state: "cancelled" } }
export interface AssistantRunFailed { readonly type: "assistant.run.failed"; readonly assistant: string; readonly conversationId: string; readonly runId: string; readonly sequence: number; readonly occurredAt: string; readonly data: { readonly code: string; readonly message: string } }
export interface AssistantRuntimeRestarting { readonly type: "assistant.runtime.restarting"; readonly assistant: string; readonly conversationId: string; readonly runId: string; readonly sequence: number; readonly occurredAt: string; readonly data: { readonly state: "restarting" } }

export type AssistantEvent =
  | AssistantRunStarted
  | AssistantMessageDelta
  | AssistantMessageCompleted
  | AssistantCapabilityProposed
  | AssistantApprovalRequired
  | AssistantCapabilityStarted
  | AssistantCapabilityCompleted
  | AssistantRunCompleted
  | AssistantRunCancelled
  | AssistantRunFailed
  | AssistantRuntimeRestarting;

export interface AssistantMessage { readonly role: "user"; readonly content: string }
export interface CreateConversationInput { readonly message: string | AssistantMessage }
export interface SendTurnInput { readonly message: string | AssistantMessage }
export interface AssistantConversation { readonly conversationId: string; readonly runId: string; readonly eventsUrl: string }
export interface AssistantRun { readonly runId: string }
export type AssistantApprovalDecision = "approve" | "deny";
export interface AssistantRequestOptions { readonly signal?: AbortSignal; readonly headers?: Readonly<Record<string, string>> }
export interface AssistantStreamOptions extends AssistantRequestOptions { readonly after?: number }
export interface AssistantTransportOptions { readonly baseUrl: string; readonly fetch?: typeof globalThis.fetch; readonly defaultHeaders?: Readonly<Record<string, string>>; readonly authentication?: Runtime.AuthenticationOptions }
export interface AssistantConversationClient {
  readonly name: string;
  createConversation(input: CreateConversationInput, options?: AssistantRequestOptions): Promise<AssistantConversation>;
  sendTurn(conversationId: string, input: SendTurnInput, options?: AssistantRequestOptions): Promise<AssistantRun>;
  streamEvents(conversationId: string, options?: AssistantStreamOptions): AsyncIterable<AssistantEvent>;
  resolveApproval(conversationId: string, approvalId: string, decision: AssistantApprovalDecision, options?: AssistantRequestOptions): Promise<void>;
  cancelRun(conversationId: string, runId: string, options?: AssistantRequestOptions): Promise<void>;
}
`
}

func renderAssistantTypeScriptImplementation() string {
	return strings.ReplaceAll(`
const assistantEventTypes = new Set<string>([
  "assistant.run.started", "assistant.message.delta", "assistant.message.completed", "assistant.capability.proposed",
  "assistant.approval.required", "assistant.capability.started", "assistant.capability.completed", "assistant.run.completed",
  "assistant.run.cancelled", "assistant.run.failed", "assistant.runtime.restarting",
]);
const assistantRunID = /^run_[0-9a-f]+$/;
const assistantConversationID = /^conv1_[0-9a-f]+$/;
const assistantApprovalID = /^appr1_[0-9a-f]+$/;
const assistantMaxMessageBytes = 64 * 1024;
const assistantMaxEventDataBytes = 1024 * 1024;
const assistantBackoff = [100, 250, 500, 1000, 2000] as const;

function assistantFailure(binding: string, message: string, cause?: unknown): Runtime.SceneryClientError {
  return new Runtime.SceneryClientError("contract_violation", binding, message, cause);
}

function assistantObject(value: unknown, binding: string, label: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) throw assistantFailure(binding, §${label} must be an object§);
  return value as Record<string, unknown>;
}

function assistantExactKeys(value: Record<string, unknown>, keys: readonly string[], binding: string, label: string): void {
  const expected = new Set(keys);
  const actual = Object.keys(value);
  if (actual.length !== expected.size || actual.some((key) => !expected.has(key))) throw assistantFailure(binding, §${label} has unknown or missing fields§);
}

function assistantString(value: unknown, binding: string, label: string, maximum = assistantMaxMessageBytes): string {
  if (typeof value !== "string" || value.length === 0 || new TextEncoder().encode(value).length > maximum) throw assistantFailure(binding, §${label} must be a bounded string§);
  return value;
}

function assistantText(value: unknown, binding: string, label: string): string {
  if (typeof value !== "string" || new TextEncoder().encode(value).length > assistantMaxMessageBytes) throw assistantFailure(binding, §${label} must be a bounded string§);
  return value;
}

function assistantSequence(value: unknown, binding: string): number {
  if (!Runtime.isJsonNumber(value)) throw assistantFailure(binding, "event sequence must be an exact JSON integer");
  const encoded = Runtime.encodeJSON(value as JsonValue);
  if (!/^[1-9][0-9]*$/.test(encoded)) throw assistantFailure(binding, "event sequence must be a positive integer");
  const parsed = Number(encoded);
  if (!Number.isSafeInteger(parsed)) throw assistantFailure(binding, "event sequence exceeds the safe integer range");
  return parsed;
}

function assistantPathSegment(value: string, binding: string, label: string): string {
  if (value.length === 0 || value.includes("/") || value.includes("\\") || value === "." || value === "..") throw new Runtime.SceneryClientError("invalid_input", binding, §${label} is invalid§);
  return encodeURIComponent(value);
}

function assistantMessage(value: string | AssistantMessage, binding: string): { readonly role: "user"; readonly content: string } {
  if (typeof value === "string") return { role: "user", content: assistantString(value, binding, "message") };
  const source = assistantObject(value, binding, "message");
  assistantExactKeys(source, ["role", "content"], binding, "message");
  if (source.role !== "user") throw new Runtime.SceneryClientError("invalid_input", binding, "message role must be user");
  return { role: "user", content: assistantString(source.content, binding, "message") };
}

function assistantURL(baseUrl: string, path: string, binding: string): string {
  if (!path.startsWith("/") || path.startsWith("//") || path.includes("\\") || path.includes("?") || path.includes("#")) throw assistantFailure(binding, "assistant URL is not a canonical path");
  try { return new URL(path, baseUrl.endsWith("/") ? baseUrl : §${baseUrl}/§).toString(); } catch (cause) { throw assistantFailure(binding, "assistant base URL is invalid", cause); }
}

function assistantHeaders(defaultHeaders: Readonly<Record<string, string>> | undefined, options: AssistantRequestOptions | undefined, authentication: Runtime.AuthenticationOptions | undefined, binding: string): Headers {
  const headers = Runtime.mergeHeaders(defaultHeaders, options?.headers, binding);
  if (authentication?.authorization !== undefined) headers.set("authorization", authentication.authorization);
  headers.set("content-type", "application/json");
  return headers;
}

async function assistantRequest(fetcher: typeof globalThis.fetch, url: string, init: RequestInit, binding: string, signal?: AbortSignal): Promise<Response> {
  if (signal?.aborted) throw new Runtime.SceneryClientError("cancelled", binding, "request cancelled");
  try {
    const response = await fetcher(url, init);
    if (response.ok) return response;
    let code = "internal";
    let message = §assistant request failed (${response.status})§;
    try {
      const parsed = Runtime.parseExactJSON(await response.text());
      const body = assistantObject(parsed, binding, "error");
      assistantExactKeys(body, ["code", "message"], binding, "error");
      code = assistantString(body.code, binding, "error.code", 256);
      message = assistantString(body.message, binding, "error.message", 8192);
    } catch (cause) {
      if (cause instanceof Runtime.SceneryClientError && cause.code === "cancelled") throw cause;
    }
    throw new Runtime.SceneryClientError(code, binding, message);
  } catch (cause) {
    if (cause instanceof Runtime.SceneryClientError) throw cause;
    throw new Runtime.SceneryClientError(signal?.aborted ? "cancelled" : "network", binding, "request failed", cause);
  }
}

async function assistantJSON(response: Response, binding: string): Promise<Record<string, unknown>> {
  const contentType = response.headers.get("content-type")?.toLowerCase() ?? "";
  if (!/^application\/json(?:\s*;|$)/.test(contentType)) throw assistantFailure(binding, "assistant response content type is invalid");
  const parsed = Runtime.parseExactJSON(await response.text());
  return assistantObject(parsed, binding, "response");
}

function assistantConversation(response: Record<string, unknown>, binding: string): AssistantConversation {
  assistantExactKeys(response, ["conversation_id", "run_id", "events_url"], binding, "conversation");
  const conversationId = assistantString(response.conversation_id, binding, "conversation_id", 16384);
  const runId = assistantString(response.run_id, binding, "run_id", 16384);
  const eventsUrl = assistantString(response.events_url, binding, "events_url", 16384);
  if (!assistantConversationID.test(conversationId) || (conversationId.length - 6) % 2 !== 0) throw assistantFailure(binding, "conversation_id is invalid");
  if (!assistantRunID.test(runId) || (runId.length - 4) % 2 !== 0) throw assistantFailure(binding, "run_id is invalid");
  if (!eventsUrl.startsWith("/") || eventsUrl.startsWith("//") || eventsUrl.includes("//") || eventsUrl.includes("?") || eventsUrl.includes("#") || eventsUrl.includes("\\") || eventsUrl.includes("%") || eventsUrl.includes("/../") || eventsUrl.endsWith("/..")) throw assistantFailure(binding, "events_url is invalid");
  return Object.freeze({ conversationId, runId, eventsUrl });
}

function assistantRun(response: Record<string, unknown>, binding: string): AssistantRun {
  assistantExactKeys(response, ["run_id"], binding, "run");
  const runId = assistantString(response.run_id, binding, "run_id", 16384);
  if (!assistantRunID.test(runId) || (runId.length - 4) % 2 !== 0) throw assistantFailure(binding, "run_id is invalid");
  return Object.freeze({ runId });
}

function assistantDecodeEvent(line: string, expectedAssistant: string, expectedConversation: string, binding: string): AssistantEvent {
  if (new TextEncoder().encode(line).length > assistantMaxEventDataBytes + 4096) throw assistantFailure(binding, "assistant event line exceeds its limit");
  const parsed = Runtime.parseExactJSON(line);
  const value = assistantObject(parsed, binding, "event");
  assistantExactKeys(value, ["type", "assistant", "conversation_id", "run_id", "sequence", "occurred_at", "data"], binding, "event");
  const type = assistantString(value.type, binding, "event.type", 128) as AssistantEventType;
  if (!assistantEventTypes.has(type)) throw assistantFailure(binding, "event type is unsupported");
  const assistant = assistantString(value.assistant, binding, "event.assistant", 256);
  const conversationId = assistantString(value.conversation_id, binding, "event.conversation_id", 16384);
  const runId = assistantString(value.run_id, binding, "event.run_id", 16384);
  const sequence = assistantSequence(value.sequence, binding);
  const occurredAt = assistantString(value.occurred_at, binding, "event.occurred_at", 128);
  if (assistant !== expectedAssistant || conversationId !== expectedConversation || !assistantConversationID.test(conversationId) || !assistantRunID.test(runId) || (runId.length - 4) % 2 !== 0 || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?Z$/.test(occurredAt) || !Number.isFinite(Date.parse(occurredAt))) throw assistantFailure(binding, "event envelope is invalid");
  const data = assistantObject(value.data, binding, "event.data");
  if (new TextEncoder().encode(JSON.stringify(data)).length > assistantMaxEventDataBytes) throw assistantFailure(binding, "event.data exceeds its limit");
  const text = () => { assistantExactKeys(data, ["text"], binding, "event.data"); return { text: assistantText(data.text, binding, "event.data.text") }; };
  const state = <T extends "started" | "completed" | "cancelled" | "restarting">(expected: T) => { assistantExactKeys(data, ["state"], binding, "event.data"); if (data.state !== expected) throw assistantFailure(binding, "event.data state is invalid"); return { state: expected }; };
  const capability = () => { assistantExactKeys(data, ["capability"], binding, "event.data"); return { capability: assistantString(data.capability, binding, "event.data.capability") }; };
  let decoded: AssistantEvent["data"];
  switch (type) {
    case "assistant.run.started": decoded = state("started"); break;
    case "assistant.message.delta": decoded = text(); break;
    case "assistant.message.completed": decoded = text(); break;
    case "assistant.capability.proposed": {
      assistantExactKeys(data, ["capability", "approval_id", "input"], binding, "event.data");
      const approvalId = assistantString(data.approval_id, binding, "event.data.approval_id", 16384);
      if (!assistantApprovalID.test(approvalId) || (approvalId.length - 6) % 2 !== 0) throw assistantFailure(binding, "event.data approval_id is invalid");
      decoded = { capability: assistantString(data.capability, binding, "event.data.capability"), approvalId, input: data.input as JsonValue }; break;
    }
    case "assistant.approval.required": {
      assistantExactKeys(data, ["capability", "approval_id"], binding, "event.data");
      const approvalId = assistantString(data.approval_id, binding, "event.data.approval_id", 16384);
      if (!assistantApprovalID.test(approvalId) || (approvalId.length - 6) % 2 !== 0) throw assistantFailure(binding, "event.data approval_id is invalid");
      decoded = { capability: assistantString(data.capability, binding, "event.data.capability"), approvalId }; break;
    }
    case "assistant.capability.started": decoded = capability(); break;
    case "assistant.capability.completed": {
      assistantExactKeys(data, ["capability", "state"], binding, "event.data");
      if (data.state !== "completed") throw assistantFailure(binding, "event.data state is invalid");
      decoded = { capability: assistantString(data.capability, binding, "event.data.capability"), state: "completed" }; break;
    }
    case "assistant.run.completed": decoded = state("completed"); break;
    case "assistant.run.cancelled": decoded = state("cancelled"); break;
    case "assistant.runtime.restarting": decoded = state("restarting"); break;
    case "assistant.run.failed": assistantExactKeys(data, ["code", "message"], binding, "event.data"); decoded = { code: assistantString(data.code, binding, "event.data.code", 256), message: assistantString(data.message, binding, "event.data.message", 8192) }; break;
    default: throw assistantFailure(binding, "event type is unsupported");
  }
  return Object.freeze({ type, assistant, conversationId, runId, sequence, occurredAt, data: Object.freeze(decoded) }) as AssistantEvent;
}

async function assistantSleep(milliseconds: number, signal?: AbortSignal): Promise<void> {
  if (signal?.aborted) throw new Runtime.SceneryClientError("cancelled", "", "stream cancelled");
  await new Promise<void>((resolve, reject) => {
    let timer: ReturnType<typeof setTimeout> | undefined;
    const cleanup = () => { if (timer !== undefined) clearTimeout(timer); signal?.removeEventListener("abort", abort); };
    const abort = () => { cleanup(); reject(new Runtime.SceneryClientError("cancelled", "", "stream cancelled")); };
    timer = setTimeout(() => { cleanup(); resolve(); }, milliseconds);
    signal?.addEventListener("abort", abort, { once: true });
  });
}

function assistantDecodeChunk(decoder: TextDecoder, chunk: Uint8Array | undefined, stream: boolean, binding: string): string {
  try { return decoder.decode(chunk, { stream }); } catch (cause) { throw assistantFailure(binding, "assistant event stream is not valid UTF-8", cause); }
}

class GeneratedAssistantConversationClient implements AssistantConversationClient {
  readonly name: string;
  readonly #path: string;
  readonly #baseUrl: string;
  readonly #fetch: typeof globalThis.fetch;
  readonly #headers: Readonly<Record<string, string>>;
  readonly #authentication?: Runtime.AuthenticationOptions;
  constructor(path: string, name: string, options: AssistantTransportOptions) {
    this.name = name;
    this.#path = path;
    this.#baseUrl = options.baseUrl.replace(/\/$/, "");
    this.#fetch = options.fetch ?? globalThis.fetch.bind(globalThis);
    this.#headers = Object.freeze({ ...(options.defaultHeaders ?? {}) });
    this.#authentication = options.authentication === undefined ? undefined : Object.freeze({ ...options.authentication });
  }
  async createConversation(input: CreateConversationInput, options: AssistantRequestOptions = {}): Promise<AssistantConversation> {
    const binding = §assistant/${this.name}/conversation.create§;
	const response = await assistantRequest(this.#fetch, assistantURL(this.#baseUrl, §${this.#path}/v1/conversations§, binding), { method: "POST", signal: options.signal, headers: assistantHeaders(this.#headers, options, this.#authentication, binding), body: JSON.stringify({ message: assistantMessage(input.message, binding) }), credentials: this.#authentication?.credentials }, binding, options.signal);
    return assistantConversation(await assistantJSON(response, binding), binding);
  }
  async sendTurn(conversationId: string, input: SendTurnInput, options: AssistantRequestOptions = {}): Promise<AssistantRun> {
    const binding = §assistant/${this.name}/conversation.turn§;
    const id = assistantPathSegment(conversationId, binding, "conversation_id");
    if (!assistantConversationID.test(conversationId)) throw new Runtime.SceneryClientError("invalid_input", binding, "conversation_id is invalid");
	const response = await assistantRequest(this.#fetch, assistantURL(this.#baseUrl, §${this.#path}/v1/conversations/${id}/turns§, binding), { method: "POST", signal: options.signal, headers: assistantHeaders(this.#headers, options, this.#authentication, binding), body: JSON.stringify({ message: assistantMessage(input.message, binding) }), credentials: this.#authentication?.credentials }, binding, options.signal);
    return assistantRun(await assistantJSON(response, binding), binding);
  }
  async *streamEvents(conversationId: string, options: AssistantStreamOptions = {}): AsyncIterable<AssistantEvent> {
    const binding = §assistant/${this.name}/conversation.events§;
    if (!assistantConversationID.test(conversationId)) throw new Runtime.SceneryClientError("invalid_input", binding, "conversation_id is invalid");
    let cursor = options.after ?? 0;
    if (!Number.isSafeInteger(cursor) || cursor < 0) throw new Runtime.SceneryClientError("invalid_input", binding, "after must be a non-negative safe integer");
    let backoffIndex = 0;
    while (!options.signal?.aborted) {
      const controller = new AbortController();
      const abort = () => controller.abort();
      options.signal?.addEventListener("abort", abort, { once: true });
      let reader: ReadableStreamDefaultReader<Uint8Array> | undefined;
      try {
        const path = §${this.#path}/v1/conversations/${encodeURIComponent(conversationId)}/events§;
        const headers = Runtime.mergeHeaders(this.#headers, options.headers, binding);
        if (this.#authentication?.authorization !== undefined) headers.set("authorization", this.#authentication.authorization);
        const response = await assistantRequest(this.#fetch, §${assistantURL(this.#baseUrl, path, binding)}?after=${cursor}§, { method: "GET", signal: controller.signal, headers, credentials: this.#authentication?.credentials }, binding, options.signal);
        const contentType = response.headers.get("content-type")?.toLowerCase() ?? "";
        if (!/^application\/x-ndjson(?:\s*;|$)/.test(contentType)) throw assistantFailure(binding, "assistant event stream content type is invalid");
        if (response.body === null) throw assistantFailure(binding, "assistant event stream has no body");
        reader = response.body.getReader();
        const decoder = new TextDecoder("utf-8", { fatal: true });
        let pending = "";
        let yielded = false;
        while (true) {
          const chunk = await reader.read();
          if (chunk.done) break;
          pending += assistantDecodeChunk(decoder, chunk.value, true, binding);
          if (new TextEncoder().encode(pending).length > assistantMaxEventDataBytes + 4096) throw assistantFailure(binding, "assistant event line exceeds its limit");
          let newline = pending.indexOf("\n");
          while (newline >= 0) {
            const line = pending.slice(0, newline).replace(/\r$/, "");
            pending = pending.slice(newline + 1);
            if (line.trim() === "") throw assistantFailure(binding, "assistant event stream contains an empty line");
            const event = assistantDecodeEvent(line, this.name, conversationId, binding);
            if (event.sequence > cursor) { cursor = event.sequence; yielded = true; yield event; }
            newline = pending.indexOf("\n");
          }
        }
        pending += assistantDecodeChunk(decoder, undefined, false, binding);
        if (pending.trim() !== "") {
          const event = assistantDecodeEvent(pending, this.name, conversationId, binding);
          if (event.sequence > cursor) { cursor = event.sequence; yielded = true; yield event; }
        }
        await reader.cancel();
        reader = undefined;
        backoffIndex = yielded ? 0 : Math.min(backoffIndex + 1, assistantBackoff.length - 1);
        if (!yielded) await assistantSleep(assistantBackoff[backoffIndex]!, options.signal);
      } catch (cause) {
        if (options.signal?.aborted || controller.signal.aborted) throw new Runtime.SceneryClientError("cancelled", binding, "stream cancelled");
        if (cause instanceof Runtime.SceneryClientError && cause.code !== "network" && cause.code !== "unavailable") throw cause;
        await assistantSleep(assistantBackoff[backoffIndex]!, options.signal);
        backoffIndex = Math.min(backoffIndex + 1, assistantBackoff.length - 1);
      } finally {
        if (reader !== undefined) { void reader.cancel(); reader = undefined; }
        options.signal?.removeEventListener("abort", abort);
      }
    }
    throw new Runtime.SceneryClientError("cancelled", binding, "stream cancelled");
  }
  async resolveApproval(conversationId: string, approvalId: string, decision: AssistantApprovalDecision, options: AssistantRequestOptions = {}): Promise<void> {
    const binding = §assistant/${this.name}/conversation.approval§;
    if (!assistantConversationID.test(conversationId) || !assistantApprovalID.test(approvalId)) throw new Runtime.SceneryClientError("invalid_input", binding, "assistant identifier is invalid");
    if (decision !== "approve" && decision !== "deny") throw new Runtime.SceneryClientError("invalid_input", binding, "approval decision is invalid");
	const response = await assistantRequest(this.#fetch, assistantURL(this.#baseUrl, §${this.#path}/v1/conversations/${encodeURIComponent(conversationId)}/approvals/${encodeURIComponent(approvalId)}§, binding), { method: "POST", signal: options.signal, headers: assistantHeaders(this.#headers, options, this.#authentication, binding), body: JSON.stringify({ decision }), credentials: this.#authentication?.credentials }, binding, options.signal);
    const body = await assistantJSON(response, binding);
    assistantExactKeys(body, ["approval_id", "decision"], binding, "approval");
    if (body.approval_id !== approvalId || body.decision !== decision) throw assistantFailure(binding, "approval response contradicts the request");
  }
  async cancelRun(conversationId: string, runId: string, options: AssistantRequestOptions = {}): Promise<void> {
    const binding = §assistant/${this.name}/conversation.cancel§;
    if (!assistantConversationID.test(conversationId) || !assistantRunID.test(runId)) throw new Runtime.SceneryClientError("invalid_input", binding, "assistant identifier is invalid");
	const response = await assistantRequest(this.#fetch, assistantURL(this.#baseUrl, §${this.#path}/v1/conversations/${encodeURIComponent(conversationId)}/runs/${encodeURIComponent(runId)}/cancel§, binding), { method: "POST", signal: options.signal, headers: assistantHeaders(this.#headers, options, this.#authentication, binding), credentials: this.#authentication?.credentials }, binding, options.signal);
    const body = await assistantJSON(response, binding);
    assistantExactKeys(body, ["run_id", "state"], binding, "cancel");
    if (body.run_id !== runId || body.state !== "cancelled") throw assistantFailure(binding, "cancel response contradicts the request");
  }
}

function createAssistantConversationClient(path: string, options: AssistantTransportOptions, name: string): AssistantConversationClient {
  return new GeneratedAssistantConversationClient(path, name, options);
}

export function createAssistantClient(name: string, options: AssistantTransportOptions, paths: Readonly<Record<string, string>>): AssistantConversationClient {
  const path = paths[name];
  if (path === undefined) throw new Runtime.SceneryClientError("invalid_options", §assistant/${name}§, "assistant is not reachable from this client");
  return createAssistantConversationClient(path, options, name);
}
`, "§", "`")
}

func renderReactAssistantAdapter(assistants []Resource) string {
	var b strings.Builder
	b.WriteString("// Code generated by Scenery. DO NOT EDIT.\n")
	b.WriteString("import { useCallback, useEffect, useMemo, useState } from \"react\";\n")
	b.WriteString("import * as Runtime from \"../runtime.js\";\n")
	b.WriteString("import { createAssistantClient, type AssistantConversationClient, type AssistantEvent, type AssistantRequestOptions, type AssistantTransportOptions } from \"../assistant.js\";\n\n")
	b.WriteString("export type SceneryAssistantName = ")
	for index, assistant := range assistants {
		if index > 0 {
			b.WriteString(" | ")
		}
		b.WriteString(strconv.Quote(assistant.Name))
	}
	b.WriteString(";\n")
	b.WriteString("export interface SceneryAssistantState { readonly name: SceneryAssistantName; readonly client: AssistantConversationClient; readonly conversationId?: string; readonly runId?: string; readonly events: readonly AssistantEvent[]; readonly pending: boolean; readonly error?: unknown; readonly createConversation: (message: string, options?: AssistantRequestOptions) => Promise<void>; readonly sendTurn: (message: string, options?: AssistantRequestOptions) => Promise<void>; readonly resolveApproval: (approvalId: string, decision: \"approve\" | \"deny\", options?: AssistantRequestOptions) => Promise<void>; readonly cancelRun: (runId?: string, options?: AssistantRequestOptions) => Promise<void> }\n\n")
	b.WriteString("export function useSceneryAssistant(name: SceneryAssistantName, providedClient?: AssistantConversationClient, transport?: AssistantTransportOptions): SceneryAssistantState {\n")
	b.WriteString("  const client = useMemo(() => providedClient ?? createAssistantClient(name, transport ?? { baseUrl: typeof globalThis.location === \"undefined\" ? \"http://localhost\" : globalThis.location.origin, authentication: { credentials: \"include\" } }, {\n")
	for _, assistant := range assistants {
		path := ""
		if surface, ok := assistant.Spec["surface"].(map[string]any); ok {
			path = strings.TrimSuffix(stringValue(surface["path"]), "/")
		}
		fmt.Fprintf(&b, "    %s: %s,\n", strconv.Quote(assistant.Name), strconv.Quote(path))
	}
	b.WriteString("  }), [name, providedClient, transport]);\n")
	b.WriteString("  const [conversationId, setConversationId] = useState<string>();\n  const [runId, setRunId] = useState<string>();\n  const [events, setEvents] = useState<readonly AssistantEvent[]>([]);\n  const [pending, setPending] = useState(false);\n  const [error, setError] = useState<unknown>();\n")
	b.WriteString("  const createConversation = useCallback(async (message: string, options: AssistantRequestOptions = {}) => { setPending(true); setError(undefined); try { const conversation = await client.createConversation({ message }, options); setConversationId(conversation.conversationId); setRunId(conversation.runId); setEvents([]); } catch (cause) { setError(cause); throw cause; } finally { setPending(false); } }, [client]);\n")
	b.WriteString("  const sendTurn = useCallback(async (message: string, options: AssistantRequestOptions = {}) => { if (conversationId === undefined) throw new Error(\"assistant conversation is not open\"); setPending(true); setError(undefined); try { const run = await client.sendTurn(conversationId, { message }, options); setRunId(run.runId); } catch (cause) { setError(cause); throw cause; } finally { setPending(false); } }, [client, conversationId]);\n")
	b.WriteString("  const resolveApproval = useCallback(async (approvalId: string, decision: \"approve\" | \"deny\", options: AssistantRequestOptions = {}) => { if (conversationId === undefined) throw new Error(\"assistant conversation is not open\"); await client.resolveApproval(conversationId, approvalId, decision, options); }, [client, conversationId]);\n")
	b.WriteString("  const cancelRun = useCallback(async (requestedRunId?: string, options: AssistantRequestOptions = {}) => { if (conversationId === undefined || (requestedRunId ?? runId) === undefined) throw new Error(\"assistant run is not open\"); await client.cancelRun(conversationId, requestedRunId ?? runId!, options); }, [client, conversationId, runId]);\n")
	b.WriteString("  useEffect(() => { if (conversationId === undefined) return; const controller = new AbortController(); let active = true; void (async () => { try { for await (const event of client.streamEvents(conversationId, { signal: controller.signal })) { if (!active) return; setEvents((current) => current.some((item) => item.sequence === event.sequence) ? current : [...current, event]); setRunId(event.runId); } } catch (cause) { if (active && !(cause instanceof Error && cause.name === \"AbortError\") && !(cause instanceof Runtime.SceneryClientError && cause.code === \"cancelled\")) setError(cause); } })(); return () => { active = false; controller.abort(); }; }, [client, conversationId]);\n")
	b.WriteString("  return { name, client, conversationId, runId, events, pending, error, createConversation, sendTurn, resolveApproval, cancelRun };\n}\n")
	return b.String()
}

func assistantGeneratedPath(root string) string { return filepath.Join(root, "assistant.ts") }
