// Code generated by Scenery vNext. DO NOT EDIT.
package scenerycontract

import (
	"encoding/json"
	"fmt"
	scenery "scenery.sh"
)

var _ = scenery.Problem{}

type ProcessMode string

const (
	ProcessModeAll      ProcessMode = "all"
	ProcessModeRoofOnly ProcessMode = "roof-only"
)

func (value ProcessMode) IsKnown() bool {
	switch value {
	case ProcessModeAll:
		return true
	case ProcessModeRoofOnly:
		return true
	default:
		return false
	}
}

func (value ProcessMode) MarshalJSON() ([]byte, error) {
	if !value.IsKnown() {
		return nil, fmt.Errorf("unknown closed enum value %q", value)
	}
	return scenery.MarshalContractValue(string(value), "string")
}

func (value *ProcessMode) UnmarshalJSON(data []byte) error {
	var decoded string
	if err := scenery.UnmarshalContractValue(data, &decoded, "string"); err != nil {
		return err
	}
	*value = ProcessMode(decoded)
	if !value.IsKnown() {
		return fmt.Errorf("unknown closed enum value %q", decoded)
	}
	return nil
}

type ProcessSceneInput struct {
	SceneId string `json:"scene_id"`
}

func (value ProcessSceneInput) MarshalJSON() ([]byte, error) {
	if err := value.Validate(); err != nil {
		return nil, err
	}
	object := map[string]json.RawMessage{}
	rawSceneId, err := scenery.MarshalContractValue(value.SceneId, "string")
	if err != nil {
		return nil, fmt.Errorf("encode field scene_id: %w", err)
	}
	object["scene_id"] = rawSceneId
	encoded, err := json.Marshal(object)
	if err != nil {
		return nil, err
	}
	return scenery.MarshalContractValue(scenery.JSON(encoded), "json")
}

func (value *ProcessSceneInput) UnmarshalJSON(data []byte) error {
	object, err := scenery.DecodeJSONObject(data)
	if err != nil {
		return err
	}
	*value = ProcessSceneInput{}
	rawSceneId, exists := object["scene_id"]
	if !exists {
		return fmt.Errorf("missing required field scene_id")
	}
	if err := unmarshalGeneratedContractValue(rawSceneId, &value.SceneId, "string"); err != nil {
		return fmt.Errorf("decode field scene_id: %w", err)
	}
	delete(object, "scene_id")
	for key := range object {
		return fmt.Errorf("unknown field %q", key)
	}
	return value.Validate()
}

func (value ProcessSceneInput) Validate() error {
	if err := scenery.ValidateContractValue(value.SceneId, "string", scenery.ContractConstraints{}); err != nil {
		return fmt.Errorf("validate field scene_id: %w", err)
	}
	return nil
}

type ProcessSceneResult struct {
	Status string `json:"status"`
}

func (value ProcessSceneResult) MarshalJSON() ([]byte, error) {
	if err := value.Validate(); err != nil {
		return nil, err
	}
	object := map[string]json.RawMessage{}
	rawStatus, err := scenery.MarshalContractValue(value.Status, "string")
	if err != nil {
		return nil, fmt.Errorf("encode field status: %w", err)
	}
	object["status"] = rawStatus
	encoded, err := json.Marshal(object)
	if err != nil {
		return nil, err
	}
	return scenery.MarshalContractValue(scenery.JSON(encoded), "json")
}

func (value *ProcessSceneResult) UnmarshalJSON(data []byte) error {
	object, err := scenery.DecodeJSONObject(data)
	if err != nil {
		return err
	}
	*value = ProcessSceneResult{}
	rawStatus, exists := object["status"]
	if !exists {
		return fmt.Errorf("missing required field status")
	}
	if err := unmarshalGeneratedContractValue(rawStatus, &value.Status, "string"); err != nil {
		return fmt.Errorf("decode field status: %w", err)
	}
	delete(object, "status")
	for key := range object {
		return fmt.Errorf("unknown field %q", key)
	}
	return value.Validate()
}

func (value ProcessSceneResult) Validate() error {
	if err := scenery.ValidateContractValue(value.Status, "string", scenery.ContractConstraints{}); err != nil {
		return fmt.Errorf("validate field status: %w", err)
	}
	return nil
}

type ReadyState struct {
	Message string `json:"message"`
}

func (value ReadyState) MarshalJSON() ([]byte, error) {
	if err := value.Validate(); err != nil {
		return nil, err
	}
	object := map[string]json.RawMessage{}
	rawMessage, err := scenery.MarshalContractValue(value.Message, "string")
	if err != nil {
		return nil, fmt.Errorf("encode field message: %w", err)
	}
	object["message"] = rawMessage
	encoded, err := json.Marshal(object)
	if err != nil {
		return nil, err
	}
	return scenery.MarshalContractValue(scenery.JSON(encoded), "json")
}

func (value *ReadyState) UnmarshalJSON(data []byte) error {
	object, err := scenery.DecodeJSONObject(data)
	if err != nil {
		return err
	}
	*value = ReadyState{}
	rawMessage, exists := object["message"]
	if !exists {
		return fmt.Errorf("missing required field message")
	}
	if err := unmarshalGeneratedContractValue(rawMessage, &value.Message, "string"); err != nil {
		return fmt.Errorf("decode field message: %w", err)
	}
	delete(object, "message")
	for key := range object {
		return fmt.Errorf("unknown field %q", key)
	}
	return value.Validate()
}

func (value ReadyState) Validate() error {
	if err := scenery.ValidateContractValue(value.Message, "string", scenery.ContractConstraints{MinLength: scenery.ContractIntConstraint(1)}); err != nil {
		return fmt.Errorf("validate field message: %w", err)
	}
	return nil
}

type WireProfile struct {
	Count         int64                   `json:"count"`
	Mode          ProcessMode             `json:"mode"`
	State         ProcessState            `json:"state"`
	Tags          scenery.Set[string]     `json:"tags"`
	UnknownFields map[string]scenery.JSON `json:"-"`
}

func (value WireProfile) MarshalJSON() ([]byte, error) {
	if err := value.Validate(); err != nil {
		return nil, err
	}
	object := map[string]json.RawMessage{}
	rawCount, err := scenery.MarshalContractValue(value.Count, "int64")
	if err != nil {
		return nil, fmt.Errorf("encode field count: %w", err)
	}
	object["count"] = rawCount
	rawMode, err := scenery.MarshalContractValue(value.Mode, "enum.process_mode")
	if err != nil {
		return nil, fmt.Errorf("encode field mode: %w", err)
	}
	object["mode"] = rawMode
	rawState, err := scenery.MarshalContractValue(value.State, "union.process_state")
	if err != nil {
		return nil, fmt.Errorf("encode field state: %w", err)
	}
	object["state"] = rawState
	rawTags, err := scenery.MarshalContractValue(value.Tags, "set(string)")
	if err != nil {
		return nil, fmt.Errorf("encode field tags: %w", err)
	}
	object["tags"] = rawTags
	for key, raw := range value.UnknownFields {
		if _, exists := object[key]; exists {
			return nil, fmt.Errorf("unknown field %q collides with a declared wire name", key)
		}
		canonical, err := scenery.MarshalContractValue(raw, "json")
		if err != nil {
			return nil, fmt.Errorf("encode unknown field %q: %w", key, err)
		}
		object[key] = append(json.RawMessage(nil), canonical...)
	}
	encoded, err := json.Marshal(object)
	if err != nil {
		return nil, err
	}
	return scenery.MarshalContractValue(scenery.JSON(encoded), "json")
}

func (value *WireProfile) UnmarshalJSON(data []byte) error {
	object, err := scenery.DecodeJSONObject(data)
	if err != nil {
		return err
	}
	*value = WireProfile{}
	rawCount, exists := object["count"]
	if !exists {
		return fmt.Errorf("missing required field count")
	}
	if err := unmarshalGeneratedContractValue(rawCount, &value.Count, "int64"); err != nil {
		return fmt.Errorf("decode field count: %w", err)
	}
	delete(object, "count")
	rawMode, exists := object["mode"]
	if !exists {
		return fmt.Errorf("missing required field mode")
	}
	if err := unmarshalGeneratedContractValue(rawMode, &value.Mode, "enum.process_mode"); err != nil {
		return fmt.Errorf("decode field mode: %w", err)
	}
	delete(object, "mode")
	rawState, exists := object["state"]
	if !exists {
		return fmt.Errorf("missing required field state")
	}
	if err := unmarshalGeneratedContractValue(rawState, &value.State, "union.process_state"); err != nil {
		return fmt.Errorf("decode field state: %w", err)
	}
	delete(object, "state")
	rawTags, exists := object["tags"]
	if !exists {
		return fmt.Errorf("missing required field tags")
	}
	if err := unmarshalGeneratedContractValue(rawTags, &value.Tags, "set(string)"); err != nil {
		return fmt.Errorf("decode field tags: %w", err)
	}
	delete(object, "tags")
	value.UnknownFields = make(map[string]scenery.JSON, len(object))
	for key, raw := range object {
		value.UnknownFields[key] = append(scenery.JSON(nil), raw...)
	}
	return value.Validate()
}

func (value WireProfile) Validate() error {
	if err := scenery.ValidateContractValue(value.Count, "int64", scenery.ContractConstraints{Minimum: scenery.ContractStringConstraint("1"), Maximum: scenery.ContractStringConstraint("100")}); err != nil {
		return fmt.Errorf("validate field count: %w", err)
	}
	if err := scenery.ValidateContractValue(value.Mode, "enum.process_mode", scenery.ContractConstraints{}); err != nil {
		return fmt.Errorf("validate field mode: %w", err)
	}
	if err := scenery.ValidateContractValue(value.State, "union.process_state", scenery.ContractConstraints{}); err != nil {
		return fmt.Errorf("validate field state: %w", err)
	}
	if err := scenery.ValidateContractValue(value.Tags, "set(string)", scenery.ContractConstraints{UniqueItems: true}); err != nil {
		return fmt.Errorf("validate field tags: %w", err)
	}
	return nil
}

type ProcessState interface{ isProcessState() }

type ProcessStateReady struct{ Value ReadyState }

func (ProcessStateReady) isProcessState() {}
func (value ProcessStateReady) MarshalJSON() ([]byte, error) {
	return marshalProcessStateVariant("ready", value.Value, "record.ready_state")
}

type ProcessStateUnknown struct {
	Tag     string
	Payload scenery.JSON
}

func (ProcessStateUnknown) isProcessState() {}
func (value ProcessStateUnknown) MarshalJSON() ([]byte, error) {
	return marshalProcessStateVariant(value.Tag, value.Payload, "json")
}

func marshalProcessStateVariant(tag string, payload any, payloadType string) ([]byte, error) {
	if tag == "" {
		return nil, fmt.Errorf("union tag is required")
	}
	payloadBytes, err := scenery.MarshalContractValue(payload, payloadType)
	if err != nil {
		return nil, err
	}
	object, err := scenery.DecodeJSONObject(payloadBytes)
	if err != nil {
		return nil, fmt.Errorf("union payload must be a record: %w", err)
	}
	if _, exists := object["kind"]; exists {
		return nil, fmt.Errorf("union discriminator collision")
	}
	tagBytes, err := scenery.MarshalContractValue(tag, "string")
	if err != nil {
		return nil, err
	}
	object["kind"] = tagBytes
	encoded, err := json.Marshal(object)
	if err != nil {
		return nil, err
	}
	return scenery.MarshalContractValue(scenery.JSON(encoded), "json")
}

func MarshalProcessStateJSON(value ProcessState) ([]byte, error) {
	switch typed := value.(type) {
	case ProcessStateReady:
		return typed.MarshalJSON()
	case *ProcessStateReady:
		if typed == nil {
			return nil, fmt.Errorf("nil union variant")
		}
		return typed.MarshalJSON()
	case ProcessStateUnknown:
		return typed.MarshalJSON()
	case *ProcessStateUnknown:
		if typed == nil {
			return nil, fmt.Errorf("nil union variant")
		}
		return typed.MarshalJSON()
	default:
		return nil, fmt.Errorf("unknown union value %T", value)
	}
}

func UnmarshalProcessStateJSON(data []byte) (ProcessState, error) {
	object, err := scenery.DecodeJSONObject(data)
	if err != nil {
		return nil, err
	}
	tagBytes, exists := object["kind"]
	if !exists {
		return nil, fmt.Errorf("missing union discriminator kind")
	}
	var tag string
	if err := scenery.UnmarshalContractValue(tagBytes, &tag, "string"); err != nil {
		return nil, fmt.Errorf("decode union discriminator: %w", err)
	}
	delete(object, "kind")
	encoded, err := json.Marshal(object)
	if err != nil {
		return nil, err
	}
	payload, err := scenery.MarshalContractValue(scenery.JSON(encoded), "json")
	if err != nil {
		return nil, err
	}
	switch tag {
	case "ready":
		var value ReadyState
		if err := unmarshalGeneratedContractValue(payload, &value, "record.ready_state"); err != nil {
			return nil, err
		}
		return ProcessStateReady{Value: value}, nil
	default:
		return ProcessStateUnknown{Tag: tag, Payload: append(scenery.JSON(nil), payload...)}, nil
	}
}

func unmarshalGeneratedContractValue(data []byte, target any, typeExpression string) error {
	return scenery.UnmarshalContractValueWithNamed(data, target, typeExpression, func(typeName string, data []byte) (any, error) {
		switch typeName {
		case "union.process_state", "house/union/process_state":
			return UnmarshalProcessStateJSON(data)
		default:
			return nil, fmt.Errorf("unknown generated named type %s", typeName)
		}
	})
}
